import time

from fastapi.testclient import TestClient

from scene_pilot.core.app import create_app
from scene_pilot.core.settings import AppSettings, FeatureFlags
from scene_pilot.models import Candidate, Skill
from scene_pilot.repositories import AgentRunRepository, AgentWorkItemRepository, TaskQueueRepository
from scene_pilot.runtime.models import LLMResponse
from scene_pilot.runtime.providers import ScriptedProvider
from scene_pilot.services.runtime_control import RuntimeControlService


def test_autonomy_loop_disabled_by_default(tmp_path):
    app = create_app(
        AppSettings(
            data_dir=str(tmp_path / "data"),
            database_url=f"sqlite:///{tmp_path / 'recruit-agent.db'}",
        )
    )

    with TestClient(app) as client:
        autonomy = client.app.state.autonomy_loop
        assert autonomy.enabled is False
        assert autonomy.is_running() is False


def test_autonomy_loop_processes_enqueued_task_when_enabled(tmp_path):
    app = create_app(
        AppSettings(
            data_dir=str(tmp_path / "data"),
            database_url=f"sqlite:///{tmp_path / 'recruit-agent.db'}",
            feature_flags=FeatureFlags(enable_autonomy=True),
        )
    )
    container = app.state.bootstrap_container
    container.agent_control.agent_loop.provider = ScriptedProvider(
        provider_name="scripted-autonomy-test",
        responses=[
            LLMResponse(
                content="Structured screening result generated by autonomy loop test runtime.",
                result_data={"status": "pass", "summary": "Autonomy workflow result", "overall": 1.0},
            )
        ]
        * 32,
    )
    with container.session_factory() as session:
        candidate = Candidate(
            name="Autonomy Candidate",
            platform="boss",
            platform_candidate_id="boss_autonomy_001",
            status="screening",
        )
        session.add(candidate)
        session.commit()
        session.refresh(candidate)

    container.agent_control.enqueue_task(
        "candidate_probe",
        candidate_id=candidate.id,
        payload={"jd_criteria": "Python"},
        priority=250,
    )

    with TestClient(app) as client:
        autonomy = client.app.state.autonomy_loop
        assert autonomy.enabled is True
        assert autonomy.is_running() is True

        deadline = time.monotonic() + 2
        while time.monotonic() < deadline:
            if container.scheduler.history and client.get("/api/agent").json()["queueDepth"] == 0:
                break
            time.sleep(0.05)

        assert container.scheduler.history
        assert container.scheduler.history[0].result.status == "completed"
        assert client.get("/api/agent").json()["queueDepth"] == 0

    assert app.state.autonomy_loop.is_running() is False


def test_autonomy_loop_runs_periodic_skill_health_sweep(tmp_path):
    app = create_app(
        AppSettings(
            data_dir=str(tmp_path / "data"),
            database_url=f"sqlite:///{tmp_path / 'recruit-agent.db'}",
            feature_flags=FeatureFlags(enable_autonomy=True, enable_skill_health_autonomy=True),
            skill_health_autonomy_interval_seconds=1,
        )
    )
    container = app.state.bootstrap_container
    with container.session_factory() as session:
        skill = Skill(
            skill_id="autonomy-health-skill",
            name="Autonomy Health Skill",
            status="active",
            platform="runtime-scene",
            strategy={"prompt": "screen"},
            health_check_config={"required_strategy_keys": ["prompt", "rubric"]},
        )
        session.add(skill)
        session.commit()

    with TestClient(app) as client:
        autonomy = client.app.state.autonomy_loop
        assert autonomy.enabled is True
        assert autonomy.health_sweep_enabled is True

        deadline = time.monotonic() + 2
        while time.monotonic() < deadline:
            with container.session_factory() as session:
                refreshed = session.query(Skill).filter(Skill.skill_id == "autonomy-health-skill").first()
                if refreshed is not None and refreshed.status == "degraded":
                    break
            time.sleep(0.05)

        with container.session_factory() as session:
            refreshed = session.query(Skill).filter(Skill.skill_id == "autonomy-health-skill").first()
            assert refreshed is not None
            assert refreshed.status == "degraded"
            assert refreshed.last_health_status == "warning"

        assert any(event.source == "skill_health" for event in container.events.snapshot())


def test_runtime_recovery_restores_recently_interrupted_run_on_restart(tmp_path):
    database_url = f"sqlite:///{tmp_path / 'recruit-agent.db'}"
    data_dir = str(tmp_path / "data")

    app = create_app(
        AppSettings(
            data_dir=data_dir,
            database_url=database_url,
        )
    )
    container = app.state.bootstrap_container

    with container.session_factory() as session:
        candidate = Candidate(
            name="Recovery Candidate",
            platform="boss",
            platform_candidate_id="boss_recovery_001",
            status="screening",
            jd_id="jd-recovery",
        )
        session.add(candidate)
        session.commit()
        session.refresh(candidate)

    task = container.agent_control.enqueue_task(
        "candidate_probe",
        candidate_id=candidate.id,
        payload={"jd_criteria": "Recovery path"},
        priority=260,
    )

    claimed = container.scheduler.queue.get()
    assert claimed is not None
    assert claimed.task_id == task.task_id

    with container.session_factory() as session:
        RuntimeControlService(
            session,
            settings=container.settings,
            live_events=container.events,
        ).begin_run(claimed)

        queue_item = TaskQueueRepository(session).get(task.task_id)
        assert queue_item is not None
        assert queue_item.status == "running"

        runtime_run = AgentRunRepository(session).by_queue_task_id(task.task_id)
        assert runtime_run is not None
        assert runtime_run.status == "running"

        work_item = AgentWorkItemRepository(session).by_queue_task_id(task.task_id)
        assert work_item is not None
        assert work_item.status == "running"

    recovered_app = create_app(
        AppSettings(
            data_dir=data_dir,
            database_url=database_url,
        )
    )
    recovered_container = recovered_app.state.bootstrap_container
    recovered_container.agent_control.agent_loop.provider = ScriptedProvider(
        provider_name="scripted-recovery-test",
        responses=[
            LLMResponse(
                content="Recovered runtime completed successfully.",
                result_data={"status": "pass", "summary": "Recovered run result", "overall": 1.0},
            )
        ]
        * 16,
    )

    with recovered_container.session_factory() as session:
        queue_item = TaskQueueRepository(session).get(task.task_id)
        assert queue_item is not None
        assert queue_item.status == "pending"

        runtime_run = AgentRunRepository(session).by_queue_task_id(task.task_id)
        assert runtime_run is not None
        assert runtime_run.status == "queued"
        assert runtime_run.runtime_metadata["recovery_mode"] in {"requeued", "rebuilt_queue_task"}

        work_item = AgentWorkItemRepository(session).by_queue_task_id(task.task_id)
        assert work_item is not None
        assert work_item.status == "queued"

    outcome = recovered_container.scheduler.run_once()
    assert outcome is not None
    assert outcome.result.status == "completed"

    with recovered_container.session_factory() as session:
        queue_item = TaskQueueRepository(session).get(task.task_id)
        assert queue_item is not None
        assert queue_item.status == "completed"

        runtime_run = AgentRunRepository(session).by_queue_task_id(task.task_id)
        assert runtime_run is not None
        assert runtime_run.status == "completed"

        work_item = AgentWorkItemRepository(session).by_queue_task_id(task.task_id)
        assert work_item is not None
        assert work_item.status == "completed"
