from __future__ import annotations

import os
import sys
import tempfile
from pathlib import Path
import unittest


SRC = Path(__file__).resolve().parents[1] / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

try:
    from fastapi.testclient import TestClient
except ModuleNotFoundError:
    TestClient = None  # type: ignore[assignment]

PLAYBOOKS_API_BASE = "/api/recruit-agent/playbooks"


@unittest.skipIf(TestClient is None, "FastAPI test dependencies are not installed")
class ApiWorkflowTests(unittest.TestCase):
    def setUp(self) -> None:
        from scene_pilot.models import ApprovalItem
        from scene_pilot.core.settings import load_settings
        from scene_pilot.runtime.models import LLMResponse
        from scene_pilot.runtime.providers import ScriptedProvider
        from scene_pilot.server import create_app

        self.tempdir = tempfile.TemporaryDirectory()
        os.environ["RECRUIT_AGENT_DATA_DIR"] = self.tempdir.name
        load_settings.cache_clear()
        self.client = TestClient(create_app())
        self.client.__enter__()
        container = self.client.app.state.container
        container.agent_control.agent_loop.provider = ScriptedProvider(
            provider_name="scripted-workflow-test",
            responses=[
                LLMResponse(
                    content="Structured screening result generated by workflow test runtime.",
                    result_data={"status": "pass", "summary": "Workflow test result", "overall": 1.0},
                )
            ]
            * 64,
        )
        created_candidate = self.client.post(
            "/api/candidates",
            json={
                "name": "Baseline Candidate",
                "platform": "site",
                "status": "discovered",
                "jd_id": "jd-baseline",
            },
        )
        if created_candidate.status_code != 201:
            raise RuntimeError(f"failed to bootstrap baseline candidate: {created_candidate.text}")
        self.default_candidate_id = created_candidate.json()["id"]
        with container.session_factory() as session:
            session.add(
                ApprovalItem(
                    target_type="runtime_checkpoint",
                    target_id="baseline-approval",
                    title="Baseline approval for workflow tests",
                    status="pending",
                    requested_by="test-suite",
                    payload={"source": "test"},
                )
            )
            session.commit()
        self._load_settings = load_settings

    def tearDown(self) -> None:
        self.client.__exit__(None, None, None)
        self.tempdir.cleanup()
        os.environ.pop("RECRUIT_AGENT_DATA_DIR", None)
        self._load_settings.cache_clear()

    def test_candidate_crud_and_approval(self) -> None:
        created = self.client.post(
            "/api/candidates",
            json={
                "name": "Test Candidate",
                "platform": "boss",
                "status": "discovered",
                "jd_id": "jd-test",
            },
        )
        self.assertEqual(created.status_code, 201)
        candidate_id = created.json()["id"]

        updated = self.client.patch(
            f"/api/candidates/{candidate_id}",
            json={"status": "screening", "current_stage_key": "candidate_probe"},
        )
        self.assertEqual(updated.status_code, 200)
        self.assertEqual(updated.json()["status"], "screening")

        approvals = self.client.get("/api/approvals")
        self.assertEqual(approvals.status_code, 200)
        approval_id = approvals.json()[0]["id"]
        approved = self.client.post(
            f"/api/approvals/{approval_id}/approve",
            json={"reviewer": "desktop-user", "reason": "Looks safe"},
        )
        self.assertEqual(approved.status_code, 200)
        self.assertEqual(approved.json()["status"], "approved")

    def test_agent_queue_and_run(self) -> None:
        dashboard = self.client.get("/api/dashboard")
        self.assertEqual(dashboard.status_code, 200)
        candidate_id = dashboard.json()["candidates"][0]["id"]

        queued = self.client.post(
            "/api/agent/tasks",
            json={
                "task_type": "candidate_probe",
                "priority": 150,
                "candidate_id": candidate_id,
                "payload": {"jd_criteria": "Python"},
            },
        )
        self.assertEqual(queued.status_code, 200)
        self.assertEqual(queued.json()["queue_depth"], 1)
        task_id = queued.json()["task_id"]

        run_once = self.client.post("/api/agent/run-once")
        self.assertEqual(run_once.status_code, 200)
        payload = run_once.json()
        self.assertTrue(payload["processed"])
        self.assertIn(payload["status"], {"completed", "idle"})

        agent_status = self.client.get("/api/agent")
        self.assertEqual(agent_status.status_code, 200)
        self.assertGreaterEqual(agent_status.json()["queueDepth"], 1)

        request_resume = self.client.post(
            "/api/agent/tasks",
            json={"task_type": "resume_collection", "priority": 300, "candidate_id": candidate_id},
        )
        self.assertEqual(request_resume.status_code, 200)
        self.assertGreaterEqual(request_resume.json()["queue_depth"], 2)

        direct_run = self.client.post("/api/agent/run-once")
        self.assertEqual(direct_run.status_code, 200)
        direct_payload = direct_run.json()
        self.assertTrue(direct_payload["processed"])
        self.assertEqual(direct_payload["status"], "completed")

        queue_snapshot = self.client.get("/api/agent/queue")
        self.assertEqual(queue_snapshot.status_code, 200)
        queue_item = next(item for item in queue_snapshot.json() if item["task_id"] == task_id)
        self.assertIn(queue_item["status"], {"completed", "failed", "pending", "running"})
        self.assertGreaterEqual(len(queue_item["queue_audit"]), 2)

        recover = self.client.post("/api/agent/queue/recover")
        self.assertEqual(recover.status_code, 200)
        self.assertIsInstance(recover.json()["by_status"], dict)

    def test_runtime_skill_draft_persists_learning_and_approval(self) -> None:
        from scene_pilot.runtime.models import LLMResponse
        from scene_pilot.runtime.providers import ScriptedProvider

        container = self.client.app.state.container
        container.agent_control.agent_loop.provider = ScriptedProvider(
            provider_name="scripted-learning",
            responses=[
                LLMResponse(
                    content="Drafted a sharper screening heuristic.",
                    result_data={
                        "status": "pass",
                        "learning": {
                            "content": "Track architecture ownership signals during screening.",
                            "tags": ["screening", "architecture"],
                        },
                    },
                    skill_draft={
                        "content": "Promote architecture ownership as a primary screening factor.",
                        "tags": ["screening", "skill"],
                        "skill_name": "architecture_screening_v2",
                        "summary": "Increase emphasis on architecture ownership evidence.",
                    },
                )
            ],
        )

        dashboard = self.client.get("/api/dashboard")
        candidate_id = dashboard.json()["candidates"][0]["id"]
        queued = self.client.post(
            "/api/agent/tasks",
            json={
                "task_type": "candidate_probe",
                "priority": 200,
                "candidate_id": candidate_id,
                "payload": {"jd_criteria": "Architecture"},
            },
        )
        task_id = queued.json()["task_id"]

        run_once = self.client.post("/api/agent/run-once")
        self.assertEqual(run_once.status_code, 200)
        self.assertEqual(run_once.json()["status"], "completed")

        learnings = self.client.get("/api/skills/learnings")
        self.assertEqual(learnings.status_code, 200)
        runtime_learning = next(
            item
            for item in learnings.json()
            if item["source_task_id"] == task_id and "skill_draft" in item["tags"]
        )
        self.assertIn("runtime", runtime_learning["tags"])

        approvals = self.client.get("/api/approvals?pending_only=true")
        self.assertEqual(approvals.status_code, 200)
        skill_draft_approval = next(
            item for item in approvals.json() if item["target_type"] == "skill_draft" and item["target_id"] == runtime_learning["id"]
        )
        self.assertEqual(skill_draft_approval["payload"]["task_id"], task_id)

        approved = self.client.post(
            f"/api/approvals/{skill_draft_approval['id']}/approve",
            json={"reviewer": "desktop-user", "reason": "Promote this runtime draft"},
        )
        self.assertEqual(approved.status_code, 200)
        self.assertEqual(approved.json()["status"], "approved")
        self.assertEqual(approved.json()["payload"]["promoted_skill"]["status"], "approved")
        promoted_skill_id = approved.json()["payload"]["promoted_skill"]["id"]

        skills = self.client.get("/api/skills")
        self.assertEqual(skills.status_code, 200)
        promoted_skill = next(item for item in skills.json() if item["id"] == promoted_skill_id)
        self.assertEqual(promoted_skill["bound_to_stage"], "candidate_probe")
        self.assertEqual(promoted_skill["status"], "approved")
        self.assertEqual(promoted_skill["platform"], "runtime-scene")

        event_sources = [event.source for event in container.events.snapshot()]
        self.assertIn("learning", event_sources)
        self.assertIn("approval", event_sources)

        approved = self.client.post(
            f"/api/approvals/{skill_draft_approval['id']}/approve",
            json={"reviewer": "desktop-user", "reason": "Looks production-ready"},
        )
        self.assertEqual(approved.status_code, 200)
        self.assertEqual(approved.json()["status"], "approved")
        self.assertEqual(approved.json()["payload"]["promoted_skill"]["status"], "approved")

        skills = self.client.get("/api/skills")
        self.assertEqual(skills.status_code, 200)
        promoted_skill = next(item for item in skills.json() if item["skill_id"].startswith("architecture_screening_v2"))
        self.assertEqual(promoted_skill["status"], "approved")

    def test_runtime_persists_session_skill_and_workflow_run(self) -> None:
        from scene_pilot.models import CandidateSession, DecisionLog, ExecutionTrace
        from scene_pilot.runtime.models import LLMResponse
        from scene_pilot.runtime.providers import ScriptedProvider

        container = self.client.app.state.container
        container.agent_control.agent_loop.provider = ScriptedProvider(
            provider_name="scripted-runtime-persistence",
            responses=[
                LLMResponse(
                    content="Applied the active screening playbook.",
                    result_data={"status": "pass", "overall": 88, "summary": "Strong backend depth."},
                )
            ],
        )

        created_skill = self.client.post(
            "/api/skills",
            json={
                "skill_id": "screening_active_v1",
                "name": "Screening Active V1",
                "status": "active",
                "platform": "boss",
                "bound_to_stage": "candidate_probe",
                "strategy": {"summary": "Prioritize architecture ownership."},
                "execution_hints": {"style": "structured"},
            },
        )
        self.assertEqual(created_skill.status_code, 201)

        dashboard = self.client.get("/api/dashboard")
        candidate_id = dashboard.json()["candidates"][0]["id"]

        queued = self.client.post(
            "/api/agent/tasks",
            json={
                "task_type": "candidate_probe",
                "priority": 240,
                "candidate_id": candidate_id,
                "payload": {"jd_criteria": "Distributed systems"},
            },
        )
        self.assertEqual(queued.status_code, 200)
        task_id = queued.json()["task_id"]

        first_run = self.client.post("/api/agent/run-once")
        self.assertEqual(first_run.status_code, 200)
        self.assertEqual(first_run.json()["status"], "completed")

        agent_status = self.client.get("/api/agent")
        self.assertEqual(agent_status.status_code, 200)
        self.assertGreaterEqual(agent_status.json()["queueDepth"], 1)

        second_run = self.client.post("/api/agent/run-once")
        self.assertEqual(second_run.status_code, 200)
        self.assertEqual(second_run.json()["status"], "failed")

        with container.session_factory() as session:
            traces = session.query(ExecutionTrace).filter(ExecutionTrace.candidate_id == candidate_id).all()
            trace = next((item for item in traces if (item.raw_trace or {}).get("task_snapshot", {}).get("task_id") == task_id), None)
            self.assertIsNotNone(trace)
            self.assertEqual(trace.status, "completed")
            self.assertEqual(trace.raw_trace["task_snapshot"]["task_id"], task_id)
            self.assertEqual(trace.distilled_trace["attempt"]["task_type"], "candidate_probe")
            self.assertEqual(trace.raw_trace["session_context"]["candidate"]["id"], candidate_id)

            candidate_session = session.query(CandidateSession).filter(CandidateSession.candidate_id == candidate_id).first()
            self.assertIsNotNone(candidate_session)
            self.assertEqual(candidate_session.status, "active")
            self.assertEqual(candidate_session.facts["active_skill"]["skill_id"], "screening_active_v1")
            self.assertEqual(candidate_session.facts["last_result_status"], "pass")
            self.assertEqual(candidate_session.facts["last_execution_status"], "completed")
            self.assertEqual(candidate_session.facts["adaptive_stage"], "candidate_probe")
            self.assertIsNotNone(candidate_session.facts["goal_spec_id"])

            decision_log = session.query(DecisionLog).filter(DecisionLog.task_id == task_id).first()
            self.assertIsNotNone(decision_log)
            self.assertEqual(decision_log.decision_type, "candidate_probe")
            self.assertEqual(decision_log.decision, "pass")

    def test_runtime_endpoints_expose_session_runs_and_events(self) -> None:
        from scene_pilot.runtime.models import LLMResponse
        from scene_pilot.runtime.providers import ScriptedProvider

        container = self.client.app.state.container
        container.agent_control.agent_loop.provider = ScriptedProvider(
            provider_name="scripted-runtime-control",
            responses=[
                LLMResponse(
                    content="Completed screening with structured context.",
                    result_data={"status": "pass", "summary": "Context manifest attached."},
                )
            ],
        )

        dashboard = self.client.get("/api/dashboard")
        candidate_id = dashboard.json()["candidates"][0]["id"]

        queued = self.client.post(
            "/api/agent/tasks",
            json={
                "task_type": "candidate_probe",
                "priority": 220,
                "candidate_id": candidate_id,
                "payload": {"jd_criteria": "Runtime context"},
            },
        )
        self.assertEqual(queued.status_code, 200)
        task_id = queued.json()["task_id"]

        run_once = self.client.post("/api/agent/run-once")
        self.assertEqual(run_once.status_code, 200)
        self.assertEqual(run_once.json()["status"], "completed")

        runtime_session = self.client.get("/api/recruit-agent/runtime/session")
        self.assertEqual(runtime_session.status_code, 200)

        runtime_runs = self.client.get(f"/api/recruit-agent/runtime/runs?candidate_id={candidate_id}")
        self.assertEqual(runtime_runs.status_code, 200)
        run_payload = next(item for item in runtime_runs.json() if item["queue_task_id"] == task_id)
        self.assertEqual(run_payload["lane"], "candidate")
        self.assertEqual(run_payload["status"], "completed")
        self.assertGreater(run_payload["context_manifest"]["fragment_count"], 0)
        self.assertGreater(run_payload["context_manifest"]["selected_token_estimate"], 0)

        runtime_events = self.client.get(f"/api/recruit-agent/runtime/events?run_id={run_payload['id']}")
        self.assertEqual(runtime_events.status_code, 200)
        event_types = {item["event_type"] for item in runtime_events.json()}
        self.assertIn("task_enqueued", event_types)
        self.assertIn("run_started", event_types)
        self.assertIn("run_finalized", event_types)

    def test_context_policy_affects_context_manifest_scores(self) -> None:
        from scene_pilot.runtime.models import LLMResponse
        from scene_pilot.runtime.providers import ScriptedProvider

        container = self.client.app.state.container
        container.agent_control.agent_loop.provider = ScriptedProvider(
            provider_name="scripted-context-policy",
            responses=[
                LLMResponse(
                    content="Completed outreach context selection.",
                    result_data={"status": "pass", "summary": "Context policy applied."},
                )
            ],
        )

        update_profile = self.client.patch(
            "/api/recruit-agent/profile",
            json={
                "prompt_config": {
                    "context_policy": {
                        "global": {
                            "token_budget_default": 2048,
                            "drop_order": ["global_memory", "job_memory", "platform_context"],
                        },
                        "lanes": {
                            "candidate": {
                                "must_include": ["task_brief", "candidate_progress", "recent_messages"],
                                "default_weights": {
                                    "recent_messages": 1.5,
                                    "candidate_memory": 1.25,
                                    "global_memory": 0.2,
                                },
                            }
                        },
                        "run_type_overrides": {
                            "candidate_outreach": {
                                "prefer": ["recent_messages", "candidate_memory"],
                                "suppress": ["global_memory"],
                            }
                        },
                    }
                }
            },
        )
        self.assertEqual(update_profile.status_code, 200)

        dashboard = self.client.get("/api/dashboard")
        candidate_id = dashboard.json()["candidates"][0]["id"]
        self.assertEqual(self.client.get(f"/api/recruit-agent/candidate-memories/{candidate_id}").status_code, 200)
        self.assertEqual(self.client.get("/api/recruit-agent/global-memory").status_code, 200)
        entry = self.client.post(
            f"/api/recruit-agent/candidate-threads/{candidate_id}/entries",
            json={
                "direction": "inbound",
                "content": "可以先发我岗位详细信息和简历要求吗？",
                "message_type": "text",
                "platform": "boss",
            },
        )
        self.assertEqual(entry.status_code, 201)

        queued = self.client.post(
            "/api/agent/tasks",
            json={
                "task_type": "candidate_outreach",
                "priority": 210,
                "candidate_id": candidate_id,
                "payload": {"message": "你好，想继续和你沟通岗位细节。"},
            },
        )
        self.assertEqual(queued.status_code, 200)
        task_id = queued.json()["task_id"]

        run_once = self.client.post("/api/agent/run-once")
        self.assertEqual(run_once.status_code, 200)
        self.assertEqual(run_once.json()["status"], "completed")

        runtime_runs = self.client.get(f"/api/recruit-agent/runtime/runs?candidate_id={candidate_id}")
        self.assertEqual(runtime_runs.status_code, 200)
        run_payload = next(item for item in runtime_runs.json() if item["queue_task_id"] == task_id)
        fragments = run_payload["context_manifest"]["fragments"]
        recent_messages = next(item for item in fragments if item["policy_key"] == "recent_messages")
        candidate_memory = next(item for item in fragments if item["policy_key"] == "candidate_memory")
        global_memory = next(item for item in fragments if item["policy_key"] == "global_memory")
        self.assertGreater(recent_messages["final_score"], recent_messages["base_score"])
        self.assertGreater(candidate_memory["final_score"], candidate_memory["base_score"])
        self.assertLess(global_memory["final_score"], global_memory["base_score"])

    def test_runtime_normalizes_provider_business_status_across_persistence(self) -> None:
        from scene_pilot.models import CandidateSession, DecisionLog, ExecutionTrace
        from scene_pilot.runtime.models import LLMResponse
        from scene_pilot.runtime.providers import ScriptedProvider

        container = self.client.app.state.container
        container.agent_control.agent_loop.provider = ScriptedProvider(
            provider_name="scripted-provider-shape",
            responses=[
                LLMResponse(
                    content="Applied the active screening playbook.",
                    result_data={
                        "status": "completed",
                        "screening_result": {
                            "decision": "pass",
                            "summary": "Strong backend depth.",
                        },
                    },
                )
            ],
        )

        dashboard = self.client.get("/api/dashboard")
        candidate_id = dashboard.json()["candidates"][0]["id"]

        queued = self.client.post(
            "/api/agent/tasks",
            json={
                "task_type": "candidate_probe",
                "priority": 240,
                "candidate_id": candidate_id,
                "payload": {"jd_criteria": "Distributed systems"},
            },
        )
        task_id = queued.json()["task_id"]

        run_once = self.client.post("/api/agent/run-once")
        self.assertEqual(run_once.status_code, 200)
        self.assertEqual(run_once.json()["status"], "completed")

        with container.session_factory() as session:
            traces = session.query(ExecutionTrace).filter(ExecutionTrace.candidate_id == candidate_id).all()
            trace = next((item for item in traces if (item.raw_trace or {}).get("task_snapshot", {}).get("task_id") == task_id), None)
            self.assertIsNotNone(trace)
            outcome = dict(trace.outcome or {})
            self.assertEqual(outcome["status"], "completed")

            candidate_session = session.query(CandidateSession).filter(CandidateSession.candidate_id == candidate_id).first()
            self.assertIsNotNone(candidate_session)
            self.assertEqual(candidate_session.facts["last_result_status"], "pass")
            self.assertEqual(candidate_session.facts["last_execution_status"], "completed")

            decision_log = session.query(DecisionLog).filter(DecisionLog.task_id == task_id).first()
            self.assertIsNotNone(decision_log)
            self.assertEqual(decision_log.decision, "pass")

    def test_runtime_updates_active_skill_health_after_execution(self) -> None:
        from scene_pilot.models import Skill
        from scene_pilot.runtime.models import LLMResponse
        from scene_pilot.runtime.providers import ScriptedProvider

        container = self.client.app.state.container
        container.agent_control.agent_loop.provider = ScriptedProvider(
            provider_name="scripted-skill-health",
            responses=[
                LLMResponse(
                    content="Screening completed below quality threshold.",
                    result_data={"status": "pass", "overall": 72, "summary": "Candidate is borderline."},
                )
            ],
        )

        created_skill = self.client.post(
            "/api/skills",
            json={
                "skill_id": "health_sensitive_screening",
                "name": "Health Sensitive Screening",
                "status": "active",
                "platform": "boss",
                "bound_to_stage": "candidate_probe",
                "strategy": {"summary": "Require stronger quality bar."},
                "health_check_config": {"minimum_overall_score": 85},
            },
        )
        self.assertEqual(created_skill.status_code, 201)
        skill_id = created_skill.json()["id"]

        dashboard = self.client.get("/api/dashboard")
        candidate_id = dashboard.json()["candidates"][0]["id"]

        queued = self.client.post(
            "/api/agent/tasks",
            json={
                "task_type": "candidate_probe",
                "priority": 240,
                "candidate_id": candidate_id,
                "adaptive_stage": "candidate_probe",
                "payload": {"jd_criteria": "Distributed systems"},
            },
        )
        self.assertEqual(queued.status_code, 200)

        run_once = self.client.post("/api/agent/run-once")
        self.assertEqual(run_once.status_code, 200)
        self.assertEqual(run_once.json()["status"], "completed")

        with container.session_factory() as session:
            skill = session.query(Skill).filter(Skill.id == skill_id).first()
            self.assertIsNotNone(skill)
            self.assertEqual(skill.status, "degraded")
            self.assertEqual(skill.last_health_status, "warning")
            self.assertIsNotNone(skill.last_health_check)

    def test_blocked_task_approval_resumes_execution(self) -> None:
        from scene_pilot.runtime.models import LLMResponse
        from scene_pilot.runtime.providers import ScriptedProvider

        container = self.client.app.state.container
        container.agent_control.agent_loop.provider = ScriptedProvider(
            provider_name="scripted-blocked-task",
            responses=[
                LLMResponse(
                    content="Need human review before continuing.",
                    requires_human_input=True,
                ),
                LLMResponse(
                    content="Human review applied.",
                    result_data={"status": "pass", "summary": "Resume completed."},
                ),
            ],
        )

        dashboard = self.client.get("/api/dashboard")
        candidate_id = dashboard.json()["candidates"][0]["id"]
        queued = self.client.post(
            "/api/agent/tasks",
            json={
                "task_type": "candidate_probe",
                "priority": 210,
                "candidate_id": candidate_id,
                "payload": {"jd_criteria": "Resume review"},
            },
        )
        task_id = queued.json()["task_id"]

        first_run = self.client.post("/api/agent/run-once")
        self.assertEqual(first_run.status_code, 200)
        self.assertEqual(first_run.json()["status"], "waiting_human")

        approvals = self.client.get("/api/approvals?pending_only=true")
        self.assertEqual(approvals.status_code, 200)
        blocked_approval = next(
            item
            for item in approvals.json()
            if item["target_type"] == "blocked_task" and item["target_id"] == task_id
        )
        self.assertEqual(blocked_approval["payload"]["blocked_task"]["task_id"], task_id)
        self.assertIn("resume_task", blocked_approval["payload"])

        checkpoints = self.client.get("/api/recruit-agent/runtime/checkpoints?open_only=true")
        self.assertEqual(checkpoints.status_code, 200)
        checkpoint = next(item for item in checkpoints.json() if item["approval_id"] == blocked_approval["id"])
        self.assertEqual(checkpoint["status"], "open")
        self.assertEqual(checkpoint["checkpoint_kind"], "approval")

        approved = self.client.post(
            f"/api/approvals/{blocked_approval['id']}/approve",
            json={"reviewer": "desktop-user", "reason": "Continue after human review"},
        )
        self.assertEqual(approved.status_code, 200)
        self.assertEqual(approved.json()["status"], "approved")
        self.assertEqual(approved.json()["payload"]["resolution"]["status"], "approved")
        self.assertTrue(approved.json()["payload"]["resolution"]["resumed"])

        resolved_checkpoints = self.client.get("/api/recruit-agent/runtime/checkpoints")
        self.assertEqual(resolved_checkpoints.status_code, 200)
        resolved_checkpoint = next(item for item in resolved_checkpoints.json() if item["approval_id"] == blocked_approval["id"])
        self.assertEqual(resolved_checkpoint["status"], "resolved")

        second_run = self.client.post("/api/agent/run-once")
        self.assertEqual(second_run.status_code, 200)
        self.assertEqual(second_run.json()["status"], "completed")

    def test_runtime_concurrency_limit_defers_candidate_runs(self) -> None:
        from scene_pilot.repositories import AgentRunRepository, AgentSessionRepository
        from scene_pilot.services.recruit_agent import ensure_primary_recruit_agent_profile

        settings_response = self.client.patch(
            "/api/settings",
            json={"platform": {"maxConcurrentRuns": 1}},
        )
        self.assertEqual(settings_response.status_code, 200)

        blocker_candidate = self.client.post(
            "/api/candidates",
            json={
                "name": "Blocking Candidate",
                "platform": "site",
                "status": "screening",
                "jd_id": "jd-runtime",
            },
        ).json()
        target_candidate = self.client.post(
            "/api/candidates",
            json={
                "name": "Queued Candidate",
                "platform": "site",
                "status": "discovered",
                "jd_id": "jd-runtime",
            },
        ).json()

        container = self.client.app.state.container
        with container.session_factory() as session:
            profile = ensure_primary_recruit_agent_profile(session)
            session_repo = AgentSessionRepository(session)
            runtime_session = session_repo.by_agent_and_key(agent_profile_id=profile.id, session_key="primary")
            if runtime_session is None:
                runtime_session = session_repo.create(
                    {
                        "agent_profile_id": profile.id,
                        "session_key": "primary",
                        "status": "active",
                        "runtime_metadata": {"agent_key": profile.agent_key},
                    }
                )
            AgentRunRepository(session).create(
                {
                    "session_id": runtime_session.id,
                    "candidate_id": blocker_candidate["id"],
                    "jd_id": blocker_candidate["jd_id"],
                    "platform": "site",
                    "lane": "candidate",
                    "run_type": "candidate_probe",
                    "status": "running",
                    "priority": 300,
                    "queue_task_id": "existing-runtime-run",
                    "runtime_metadata": {"seeded": True},
                }
            )

        queued = self.client.post(
            "/api/agent/tasks",
            json={
                "task_type": "candidate_probe",
                "priority": 180,
                "candidate_id": target_candidate["id"],
                "payload": {"jd_criteria": "Global limit"},
            },
        )
        self.assertEqual(queued.status_code, 200)
        task_id = queued.json()["task_id"]

        run_once = self.client.post("/api/agent/run-once")
        self.assertEqual(run_once.status_code, 200)
        self.assertEqual(run_once.json()["status"], "deferred")

        queue_snapshot = self.client.get("/api/agent/queue?status=pending")
        self.assertEqual(queue_snapshot.status_code, 200)
        self.assertTrue(any(item["task_id"] == task_id for item in queue_snapshot.json()))

        runtime_runs = self.client.get(f"/api/recruit-agent/runtime/runs?candidate_id={target_candidate['id']}")
        self.assertEqual(runtime_runs.status_code, 200)
        deferred_run = next(item for item in runtime_runs.json() if item["queue_task_id"] == task_id)
        self.assertEqual(deferred_run["status"], "queued")

    def test_blocked_task_reject_marks_closure_metadata(self) -> None:
        from scene_pilot.runtime.models import LLMResponse
        from scene_pilot.runtime.providers import ScriptedProvider

        container = self.client.app.state.container
        container.agent_control.agent_loop.provider = ScriptedProvider(
            provider_name="scripted-blocked-task-reject",
            responses=[LLMResponse(content="Need human review before continuing.", requires_human_input=True)],
        )

        dashboard = self.client.get("/api/dashboard")
        candidate_id = dashboard.json()["candidates"][0]["id"]
        queued = self.client.post(
            "/api/agent/tasks",
            json={
                "task_type": "candidate_probe",
                "priority": 205,
                "candidate_id": candidate_id,
                "payload": {"jd_criteria": "Resume review"},
            },
        )
        task_id = queued.json()["task_id"]

        first_run = self.client.post("/api/agent/run-once")
        self.assertEqual(first_run.status_code, 200)
        self.assertEqual(first_run.json()["status"], "waiting_human")

        approvals = self.client.get("/api/approvals?pending_only=true")
        self.assertEqual(approvals.status_code, 200)
        blocked_approval = next(
            item
            for item in approvals.json()
            if item["target_type"] == "blocked_task" and item["target_id"] == task_id
        )

        rejected = self.client.post(
            f"/api/approvals/{blocked_approval['id']}/reject",
            json={"reviewer": "desktop-user", "reason": "Do not resume"},
        )
        self.assertEqual(rejected.status_code, 200)
        self.assertEqual(rejected.json()["status"], "rejected")
        self.assertEqual(rejected.json()["payload"]["resolution"]["status"], "rejected")
        self.assertIn("closed_at", rejected.json()["payload"])
        self.assertFalse(rejected.json()["payload"]["resolution"]["resumed"])

    def test_system_command_request_enforces_flag_and_whitelist(self) -> None:
        container = self.client.app.state.container

        policy = self.client.get("/api/agent/system-commands/policy")
        self.assertEqual(policy.status_code, 200)
        self.assertFalse(policy.json()["enabled"])

        blocked = self.client.post(
            "/api/agent/system-commands/request",
            json={"command": ["python3", "-m", "pytest"], "requested_by": "desktop-user"},
        )
        self.assertEqual(blocked.status_code, 403)

        container.flags.set_flag("skills.system_command", True)

        rejected = self.client.post(
            "/api/agent/system-commands/request",
            json={"command": ["rm", "-rf", "/tmp/not-allowed"], "requested_by": "desktop-user"},
        )
        self.assertEqual(rejected.status_code, 400)

        requested = self.client.post(
            "/api/agent/system-commands/request",
            json={
                "command": ["python3", "-m", "pytest", "services/backend/tests/test_runtime_tools.py"],
                "requested_by": "desktop-user",
                "rationale": "Validate the runtime tool contract.",
            },
        )
        self.assertEqual(requested.status_code, 201)
        self.assertEqual(requested.json()["target_type"], "system_command")
        self.assertEqual(requested.json()["status"], "pending")
        self.assertEqual(requested.json()["payload"]["command"][0:3], ["python3", "-m", "pytest"])

        approved = self.client.post(
            f"/api/approvals/{requested.json()['id']}/approve",
            json={"reviewer": "desktop-user", "reason": "Allowed for validation"},
        )
        self.assertEqual(approved.status_code, 200)
        self.assertEqual(approved.json()["status"], "approved")
        self.assertEqual(approved.json()["payload"]["execution_status"], "approved_but_disabled")
        self.assertFalse(approved.json()["payload"]["resolution"]["execution_enabled"])

    def test_system_command_execute_after_approval_when_enabled(self) -> None:
        container = self.client.app.state.container
        container.flags.set_flag("skills.system_command", True)
        container.system_commands.execution_enabled = True
        container.system_commands.whitelist = (
            *container.system_commands.whitelist,
            ("python3", "-c"),
        )

        requested = self.client.post(
            "/api/agent/system-commands/request",
            json={
                "command": ["python3", "-c", "print('system-command-ok')"],
                "requested_by": "desktop-user",
            },
        )
        self.assertEqual(requested.status_code, 201)

        not_ready = self.client.post(
            f"/api/agent/system-commands/{requested.json()['id']}/execute",
            json={"requested_by": "desktop-user"},
        )
        self.assertEqual(not_ready.status_code, 409)

        approved = self.client.post(
            f"/api/approvals/{requested.json()['id']}/approve",
            json={"reviewer": "desktop-user", "reason": "Safe local command"},
        )
        self.assertEqual(approved.status_code, 200)
        self.assertEqual(approved.json()["payload"]["command_resolution"]["execution_status"], "approved_ready")

        executed = self.client.post(
            f"/api/agent/system-commands/{requested.json()['id']}/execute",
            json={"requested_by": "desktop-user"},
        )
        self.assertEqual(executed.status_code, 200)
        self.assertEqual(executed.json()["payload"]["execution"]["status"], "completed")
        self.assertEqual(executed.json()["payload"]["command_resolution"]["execution_status"], "completed")
        self.assertIn("system-command-ok", executed.json()["payload"]["execution"]["stdout"])


if __name__ == "__main__":
    unittest.main()
