from __future__ import annotations

import os
import sys
import tempfile
from datetime import timedelta
from pathlib import Path
import unittest


SRC = Path(__file__).resolve().parents[1] / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

try:
    from fastapi.testclient import TestClient
except ModuleNotFoundError:
    TestClient = None  # type: ignore[assignment]

PLAYBOOKS_API_BASE = "/api/recruit-agent/playbooks"


@unittest.skipIf(TestClient is None, "FastAPI test dependencies are not installed")
class ApiPlaybookRuntimeTests(unittest.TestCase):
    def setUp(self) -> None:
        from scene_pilot.models import ApprovalItem
        from scene_pilot.core.settings import load_settings
        from scene_pilot.runtime.models import LLMResponse
        from scene_pilot.runtime.providers import ScriptedProvider
        from scene_pilot.server import create_app

        self.tempdir = tempfile.TemporaryDirectory()
        os.environ["RECRUIT_AGENT_DATA_DIR"] = self.tempdir.name
        load_settings.cache_clear()
        self.client = TestClient(create_app())
        self.client.__enter__()
        container = self.client.app.state.container
        container.agent_control.agent_loop.provider = ScriptedProvider(
            provider_name="scripted-playbook-test",
            responses=[
                LLMResponse(
                    content="Structured screening result generated by playbook runtime.",
                    result_data={"status": "pass", "summary": "Playbook test result", "overall": 1.0},
                )
            ]
            * 64,
        )
        created_candidate = self.client.post(
            "/api/candidates",
            json={
                "name": "Baseline Candidate",
                "platform": "site",
                "current_status": "discovered",
                "jd_id": "jd-baseline",
            },
        )
        if created_candidate.status_code != 201:
            raise RuntimeError(f"failed to bootstrap baseline candidate: {created_candidate.text}")
        self.default_candidate_id = created_candidate.json()["id"]
        with container.session_factory() as session:
            session.add(
                ApprovalItem(
                    target_type="runtime_checkpoint",
                    target_id="baseline-approval",
                    title="Baseline approval for playbook runtime tests",
                    status="pending",
                    requested_by="test-suite",
                    payload={"source": "test"},
                )
            )
            session.commit()
        self._load_settings = load_settings

    def tearDown(self) -> None:
        self.client.__exit__(None, None, None)
        self.tempdir.cleanup()
        os.environ.pop("RECRUIT_AGENT_DATA_DIR", None)
        self._load_settings.cache_clear()

    def test_candidate_crud_and_approval(self) -> None:
        created = self.client.post(
            "/api/candidates",
            json={
                "name": "Test Candidate",
                "platform": "boss",
                "current_status": "discovered",
                "jd_id": "jd-test",
            },
        )
        self.assertEqual(created.status_code, 201)
        candidate_id = created.json()["id"]

        updated = self.client.patch(
            f"/api/candidates/{candidate_id}",
            json={"current_status": "screening", "current_stage_key": "candidate_probe"},
        )
        self.assertEqual(updated.status_code, 200)
        self.assertEqual(updated.json()["current_status"], "screening")

        approvals = self.client.get("/api/approvals")
        self.assertEqual(approvals.status_code, 200)
        approval_id = approvals.json()[0]["id"]
        approved = self.client.post(
            f"/api/approvals/{approval_id}/approve",
            json={"reviewer": "desktop-user", "reason": "Looks safe"},
        )
        self.assertEqual(approved.status_code, 200)
        self.assertEqual(approved.json()["status"], "approved")

    def test_agent_queue_and_run(self) -> None:
        dashboard = self.client.get("/api/dashboard")
        self.assertEqual(dashboard.status_code, 200)
        candidate_id = dashboard.json()["candidates"][0]["id"]

        queued = self.client.post(
            "/api/agent/tasks",
            json={
                "task_type": "candidate_probe",
                "priority": 150,
                "candidate_id": candidate_id,
                "payload": {"jd_criteria": "Python"},
            },
        )
        self.assertEqual(queued.status_code, 200)
        self.assertEqual(queued.json()["queue_depth"], 1)
        task_id = queued.json()["task_id"]

        run_once = self.client.post("/api/agent/run-once")
        self.assertEqual(run_once.status_code, 200)
        payload = run_once.json()
        self.assertTrue(payload["processed"])
        self.assertIn(payload["status"], {"completed", "idle"})

        agent_status = self.client.get("/api/agent")
        self.assertEqual(agent_status.status_code, 200)
        self.assertGreaterEqual(agent_status.json()["queueDepth"], 1)

        request_resume = self.client.post(
            "/api/agent/tasks",
            json={"task_type": "resume_collection", "priority": 300, "candidate_id": candidate_id},
        )
        self.assertEqual(request_resume.status_code, 200)
        self.assertGreaterEqual(request_resume.json()["queue_depth"], 2)

        direct_run = self.client.post("/api/agent/run-once")
        self.assertEqual(direct_run.status_code, 200)
        direct_payload = direct_run.json()
        self.assertTrue(direct_payload["processed"])
        self.assertEqual(direct_payload["status"], "completed")

        queue_snapshot = self.client.get("/api/agent/queue")
        self.assertEqual(queue_snapshot.status_code, 200)
        queue_item = next(item for item in queue_snapshot.json() if item["task_id"] == task_id)
        self.assertIn(queue_item["status"], {"completed", "failed", "pending", "running"})
        self.assertGreaterEqual(len(queue_item["queue_audit"]), 2)

        recover = self.client.post("/api/agent/queue/recover")
        self.assertEqual(recover.status_code, 200)
        self.assertIsInstance(recover.json()["by_status"], dict)

    def test_runtime_skill_draft_persists_learning_and_approval(self) -> None:
        from scene_pilot.runtime.models import LLMResponse
        from scene_pilot.runtime.providers import ScriptedProvider

        container = self.client.app.state.container
        container.agent_control.agent_loop.provider = ScriptedProvider(
            provider_name="scripted-learning",
            responses=[
                LLMResponse(
                    content="Drafted a sharper screening heuristic.",
                    result_data={
                        "status": "pass",
                        "learning": {
                            "content": "Track architecture ownership signals during screening.",
                            "tags": ["screening", "architecture"],
                        },
                    },
                    skill_draft={
                        "content": "Promote architecture ownership as a primary screening factor.",
                        "tags": ["screening", "skill"],
                        "skill_name": "architecture_screening_v2",
                        "summary": "Increase emphasis on architecture ownership evidence.",
                    },
                )
            ],
        )

        dashboard = self.client.get("/api/dashboard")
        candidate_id = dashboard.json()["candidates"][0]["id"]
        queued = self.client.post(
            "/api/agent/tasks",
            json={
                "task_type": "candidate_probe",
                "priority": 200,
                "candidate_id": candidate_id,
                "payload": {"jd_criteria": "Architecture"},
            },
        )
        task_id = queued.json()["task_id"]

        run_once = self.client.post("/api/agent/run-once")
        self.assertEqual(run_once.status_code, 200)
        self.assertEqual(run_once.json()["status"], "completed")

        learnings = self.client.get("/api/skills/learnings")
        self.assertEqual(learnings.status_code, 200)
        runtime_learning = next(
            item
            for item in learnings.json()
            if item["source_task_id"] == task_id and "skill_draft" in item["tags"]
        )
        self.assertIn("runtime", runtime_learning["tags"])

        approvals = self.client.get("/api/approvals?pending_only=true")
        self.assertEqual(approvals.status_code, 200)
        skill_draft_approval = next(
            item for item in approvals.json() if item["target_type"] == "skill_draft" and item["target_id"] == runtime_learning["id"]
        )
        self.assertEqual(skill_draft_approval["payload"]["task_id"], task_id)

        approved = self.client.post(
            f"/api/approvals/{skill_draft_approval['id']}/approve",
            json={"reviewer": "desktop-user", "reason": "Promote this runtime draft"},
        )
        self.assertEqual(approved.status_code, 200)
        self.assertEqual(approved.json()["status"], "approved")
        self.assertEqual(approved.json()["payload"]["promoted_skill"]["status"], "approved")
        promoted_skill_id = approved.json()["payload"]["promoted_skill"]["id"]

        skills = self.client.get("/api/skills")
        self.assertEqual(skills.status_code, 200)
        promoted_skill = next(item for item in skills.json() if item["id"] == promoted_skill_id)
        first_skill_key = promoted_skill["skill_id"]
        self.assertEqual(promoted_skill["bound_to_stage"], "candidate_probe")
        self.assertEqual(promoted_skill["status"], "approved")
        self.assertEqual(promoted_skill["platform"], "runtime-scene")
        self.assertEqual(promoted_skill["skill_metadata"]["promotion_source"], "approval")
        self.assertEqual(promoted_skill["skill_metadata"]["promotion_source_kind"], "approval")
        self.assertEqual(promoted_skill["skill_metadata"]["promotion_source_id"], skill_draft_approval["id"])

        event_sources = [event.source for event in container.events.snapshot()]
        self.assertIn("learning", event_sources)
        self.assertIn("approval", event_sources)

        approved = self.client.post(
            f"/api/approvals/{skill_draft_approval['id']}/approve",
            json={"reviewer": "desktop-user", "reason": "Looks production-ready"},
        )
        self.assertEqual(approved.status_code, 200)
        self.assertEqual(approved.json()["status"], "approved")
        self.assertEqual(approved.json()["payload"]["promoted_skill"]["status"], "approved")
        self.assertEqual(approved.json()["payload"]["promoted_skill"]["version"], 1)

        skills = self.client.get("/api/skills")
        self.assertEqual(skills.status_code, 200)
        matching_skills = [item for item in skills.json() if item["skill_id"] == first_skill_key]
        self.assertEqual(len(matching_skills), 1)
        promoted_skill = matching_skills[0]
        self.assertEqual(promoted_skill["status"], "approved")
        self.assertEqual(promoted_skill["version"], 1)
        self.assertEqual(promoted_skill["id"], promoted_skill_id)
        self.assertEqual(promoted_skill["skill_id"], first_skill_key)

    def test_candidate_progression_run_persists_single_promotable_evolution_artifact(self) -> None:
        from scene_pilot.runtime.models import LLMResponse
        from scene_pilot.runtime.providers import ScriptedProvider

        container = self.client.app.state.container
        container.agent_control.agent_loop.provider = ScriptedProvider(
            provider_name="scripted-progression-artifact",
            responses=[
                LLMResponse(
                    content="Sent a concise outreach to validate backend ownership signals.",
                    result_data={
                        "status": "pass",
                        "summary": "Candidate received the first outreach.",
                    },
                    skill_draft={
                        "content": "Lead with ownership proof points before asking for resume.",
                        "summary": "Outreach should emphasize ownership evidence.",
                        "skill_name": "candidate_outreach_runtime",
                    },
                )
            ],
        )

        queued = self.client.post(
            "/api/agent/tasks",
            json={
                "task_type": "candidate_outreach",
                "priority": 220,
                "candidate_id": self.default_candidate_id,
                "payload": {"message": "你好，我们想进一步聊聊后端 owner 经验。"},
            },
        )
        self.assertEqual(queued.status_code, 200)
        task_id = queued.json()["task_id"]

        run_once = self.client.post("/api/agent/run-once")
        self.assertEqual(run_once.status_code, 200)
        self.assertEqual(run_once.json()["status"], "completed")

        artifacts = self.client.get("/api/recruit-agent/evolution-artifacts?artifact_kind=skill_draft")
        self.assertEqual(artifacts.status_code, 200)
        matched = [
            item
            for item in artifacts.json()
            if item["artifact_metadata"].get("source_task_id") == task_id
        ]
        self.assertEqual(len(matched), 1)
        artifact = matched[0]
        self.assertEqual(artifact["artifact_kind"], "skill_draft")
        self.assertEqual(artifact["status"], "pending_review")
        self.assertEqual(artifact["related_candidate_id"], self.default_candidate_id)
        self.assertIn("skill_contract", artifact["artifact_body"])
        self.assertIn("decision_trace", artifact["artifact_body"])
        self.assertIn("model_skill_draft", artifact["artifact_body"])
        self.assertNotIn("content", artifact["artifact_body"])
        self.assertEqual(artifact["artifact_body"]["skill_contract"]["skill_id"], "candidate_outreach_progression")
        self.assertEqual(artifact["artifact_body"]["skill_contract"]["bound_to_stage"], "candidate_outreach")

        approvals = self.client.get("/api/approvals?pending_only=true")
        self.assertEqual(approvals.status_code, 200)
        progression_approvals = [
            item
            for item in approvals.json()
            if item["target_type"] == "skill_draft" and item["payload"].get("task_id") == task_id
        ]
        self.assertEqual(progression_approvals, [])

    def test_runtime_persists_session_skill_and_playbook_run(self) -> None:
        from scene_pilot.models import CandidateSession, DecisionLog, ExecutionTrace
        from scene_pilot.runtime.models import LLMResponse
        from scene_pilot.runtime.providers import ScriptedProvider

        container = self.client.app.state.container
        container.agent_control.agent_loop.provider = ScriptedProvider(
            provider_name="scripted-runtime-persistence",
            responses=[
                LLMResponse(
                    content="Applied the active screening playbook.",
                    result_data={"status": "pass", "overall": 88, "summary": "Strong backend depth."},
                )
            ],
        )

        created_skill = self.client.post(
            "/api/skills",
            json={
                "skill_id": "screening_active_v1",
                "name": "Screening Active V1",
                "status": "active",
                "platform": "boss",
                "bound_to_stage": "candidate_probe",
                "strategy": {"summary": "Prioritize architecture ownership."},
                "execution_hints": {"style": "structured"},
            },
        )
        self.assertEqual(created_skill.status_code, 201)

        dashboard = self.client.get("/api/dashboard")
        candidate_id = dashboard.json()["candidates"][0]["id"]

        queued = self.client.post(
            "/api/agent/tasks",
            json={
                "task_type": "candidate_probe",
                "priority": 240,
                "candidate_id": candidate_id,
                "payload": {"jd_criteria": "Distributed systems"},
            },
        )
        self.assertEqual(queued.status_code, 200)
        task_id = queued.json()["task_id"]

        first_run = self.client.post("/api/agent/run-once")
        self.assertEqual(first_run.status_code, 200)
        self.assertEqual(first_run.json()["status"], "completed")

        agent_status = self.client.get("/api/agent")
        self.assertEqual(agent_status.status_code, 200)
        self.assertGreaterEqual(agent_status.json()["queueDepth"], 1)

        second_run = self.client.post("/api/agent/run-once")
        self.assertEqual(second_run.status_code, 200)
        self.assertEqual(second_run.json()["status"], "failed")

        with container.session_factory() as session:
            traces = session.query(ExecutionTrace).filter(ExecutionTrace.candidate_id == candidate_id).all()
            trace = next((item for item in traces if (item.raw_trace or {}).get("task_snapshot", {}).get("task_id") == task_id), None)
            self.assertIsNotNone(trace)
            self.assertEqual(trace.status, "completed")
            self.assertEqual(trace.raw_trace["task_snapshot"]["task_id"], task_id)
            self.assertEqual(trace.distilled_trace["attempt"]["task_type"], "candidate_probe")
            self.assertEqual(trace.raw_trace["session_context"]["candidate"]["id"], candidate_id)

            candidate_session = session.query(CandidateSession).filter(CandidateSession.candidate_id == candidate_id).first()
            self.assertIsNotNone(candidate_session)
            self.assertEqual(candidate_session.status, "active")
            self.assertEqual(candidate_session.facts["active_skill"]["skill_id"], "screening_active_v1")
            self.assertEqual(candidate_session.facts["last_result_status"], "pass")
            self.assertEqual(candidate_session.facts["last_execution_status"], "completed")
            self.assertEqual(candidate_session.facts["adaptive_stage"], "candidate_probe")
            self.assertIsNotNone(candidate_session.facts["goal_spec_id"])

            decision_log = session.query(DecisionLog).filter(DecisionLog.task_id == task_id).first()
            self.assertIsNotNone(decision_log)
            self.assertEqual(decision_log.decision_type, "candidate_probe")
            self.assertEqual(decision_log.decision, "pass")

    def test_runtime_endpoints_expose_session_runs_and_events(self) -> None:
        from scene_pilot.runtime.models import LLMResponse
        from scene_pilot.runtime.providers import ScriptedProvider

        container = self.client.app.state.container
        container.agent_control.agent_loop.provider = ScriptedProvider(
            provider_name="scripted-runtime-control",
            responses=[
                LLMResponse(
                    content="Completed screening with structured context.",
                    result_data={"status": "pass", "summary": "Context manifest attached."},
                )
            ],
        )

        dashboard = self.client.get("/api/dashboard")
        candidate_id = dashboard.json()["candidates"][0]["id"]

        queued = self.client.post(
            "/api/agent/tasks",
            json={
                "task_type": "candidate_probe",
                "priority": 220,
                "candidate_id": candidate_id,
                "payload": {"jd_criteria": "Runtime context"},
            },
        )
        self.assertEqual(queued.status_code, 200)
        task_id = queued.json()["task_id"]

        run_once = self.client.post("/api/agent/run-once")
        self.assertEqual(run_once.status_code, 200)
        self.assertEqual(run_once.json()["status"], "completed")

        runtime_session = self.client.get("/api/recruit-agent/runtime/session")
        self.assertEqual(runtime_session.status_code, 200)

        runtime_runs = self.client.get(f"/api/recruit-agent/runtime/runs?candidate_id={candidate_id}")
        self.assertEqual(runtime_runs.status_code, 200)
        run_payload = next(item for item in runtime_runs.json() if item["queue_task_id"] == task_id)
        self.assertEqual(run_payload["lane"], "candidate")
        self.assertEqual(run_payload["status"], "completed")
        self.assertGreater(run_payload["context_manifest"]["fragment_count"], 0)
        self.assertGreater(run_payload["context_manifest"]["selected_token_estimate"], 0)

        runtime_events = self.client.get(f"/api/recruit-agent/runtime/events?run_id={run_payload['id']}")
        self.assertEqual(runtime_events.status_code, 200)
        event_types = {item["event_type"] for item in runtime_events.json()}
        self.assertIn("task_enqueued", event_types)
        self.assertIn("run_started", event_types)
        self.assertIn("run_finalized", event_types)

    def test_context_policy_affects_context_manifest_scores(self) -> None:
        from scene_pilot.runtime.models import LLMResponse
        from scene_pilot.runtime.providers import ScriptedProvider

        container = self.client.app.state.container
        container.agent_control.agent_loop.provider = ScriptedProvider(
            provider_name="scripted-context-policy",
            responses=[
                LLMResponse(
                    content="Completed outreach context selection.",
                    result_data={"status": "pass", "summary": "Context policy applied."},
                )
            ],
        )

        update_profile = self.client.patch(
            "/api/recruit-agent/profile",
            json={
                "prompt_config": {
                    "context_policy": {
                        "global": {
                            "token_budget_default": 2048,
                            "drop_order": ["global_memory", "job_memory", "platform_context"],
                        },
                        "lanes": {
                            "candidate": {
                                "must_include": ["task_brief", "candidate_progress", "recent_messages"],
                                "default_weights": {
                                    "recent_messages": 1.5,
                                    "candidate_memory": 1.25,
                                    "global_memory": 0.2,
                                },
                            }
                        },
                        "run_type_overrides": {
                            "candidate_outreach": {
                                "prefer": ["recent_messages", "candidate_memory"],
                                "suppress": ["global_memory"],
                            }
                        },
                    }
                }
            },
        )
        self.assertEqual(update_profile.status_code, 200)

        dashboard = self.client.get("/api/dashboard")
        candidate_id = dashboard.json()["candidates"][0]["id"]
        self.assertEqual(self.client.get(f"/api/recruit-agent/candidate-memories/{candidate_id}").status_code, 200)
        self.assertEqual(self.client.get("/api/recruit-agent/global-memory").status_code, 200)
        entry = self.client.post(
            f"/api/recruit-agent/candidate-threads/{candidate_id}/entries",
            json={
                "direction": "inbound",
                "content": "可以先发我岗位详细信息和简历要求吗？",
                "message_type": "text",
                "platform": "boss",
            },
        )
        self.assertEqual(entry.status_code, 201)

        queued = self.client.post(
            "/api/agent/tasks",
            json={
                "task_type": "candidate_outreach",
                "priority": 210,
                "candidate_id": candidate_id,
                "payload": {"message": "你好，想继续和你沟通岗位细节。"},
            },
        )
        self.assertEqual(queued.status_code, 200)
        task_id = queued.json()["task_id"]

        run_once = self.client.post("/api/agent/run-once")
        self.assertEqual(run_once.status_code, 200)
        self.assertEqual(run_once.json()["status"], "completed")

        runtime_runs = self.client.get(f"/api/recruit-agent/runtime/runs?candidate_id={candidate_id}")
        self.assertEqual(runtime_runs.status_code, 200)
        run_payload = next(item for item in runtime_runs.json() if item["queue_task_id"] == task_id)
        fragments = run_payload["context_manifest"]["fragments"]
        recent_messages = next(item for item in fragments if item["policy_key"] == "recent_messages")
        candidate_memory = next(item for item in fragments if item["policy_key"] == "candidate_memory")
        global_memory = next(item for item in fragments if item["policy_key"] == "global_memory")
        self.assertGreater(recent_messages["final_score"], recent_messages["base_score"])
        self.assertGreater(candidate_memory["final_score"], candidate_memory["base_score"])
        self.assertLess(global_memory["final_score"], global_memory["base_score"])

    def test_runtime_normalizes_provider_business_status_across_persistence(self) -> None:
        from scene_pilot.models import CandidateSession, DecisionLog, ExecutionTrace
        from scene_pilot.runtime.models import LLMResponse
        from scene_pilot.runtime.providers import ScriptedProvider

        container = self.client.app.state.container
        container.agent_control.agent_loop.provider = ScriptedProvider(
            provider_name="scripted-provider-shape",
            responses=[
                LLMResponse(
                    content="Applied the active screening playbook.",
                    result_data={
                        "status": "completed",
                        "screening_result": {
                            "decision": "pass",
                            "summary": "Strong backend depth.",
                        },
                    },
                )
            ],
        )

        dashboard = self.client.get("/api/dashboard")
        candidate_id = dashboard.json()["candidates"][0]["id"]

        queued = self.client.post(
            "/api/agent/tasks",
            json={
                "task_type": "candidate_probe",
                "priority": 240,
                "candidate_id": candidate_id,
                "payload": {"jd_criteria": "Distributed systems"},
            },
        )
        task_id = queued.json()["task_id"]

        run_once = self.client.post("/api/agent/run-once")
        self.assertEqual(run_once.status_code, 200)
        self.assertEqual(run_once.json()["status"], "completed")

        with container.session_factory() as session:
            traces = session.query(ExecutionTrace).filter(ExecutionTrace.candidate_id == candidate_id).all()
            trace = next((item for item in traces if (item.raw_trace or {}).get("task_snapshot", {}).get("task_id") == task_id), None)
            self.assertIsNotNone(trace)
            outcome = dict(trace.outcome or {})
            self.assertEqual(outcome["status"], "completed")

            candidate_session = session.query(CandidateSession).filter(CandidateSession.candidate_id == candidate_id).first()
            self.assertIsNotNone(candidate_session)
            self.assertEqual(candidate_session.facts["last_result_status"], "pass")
            self.assertEqual(candidate_session.facts["last_execution_status"], "completed")

            decision_log = session.query(DecisionLog).filter(DecisionLog.task_id == task_id).first()
            self.assertIsNotNone(decision_log)
            self.assertEqual(decision_log.decision, "pass")

    def test_runtime_updates_active_skill_health_after_execution(self) -> None:
        from scene_pilot.models import Skill
        from scene_pilot.runtime.models import LLMResponse
        from scene_pilot.runtime.providers import ScriptedProvider

        container = self.client.app.state.container
        container.agent_control.agent_loop.provider = ScriptedProvider(
            provider_name="scripted-skill-health",
            responses=[
                LLMResponse(
                    content="Screening completed below quality threshold.",
                    result_data={"status": "pass", "overall": 72, "summary": "Candidate is borderline."},
                )
            ],
        )

        created_skill = self.client.post(
            "/api/skills",
            json={
                "skill_id": "health_sensitive_screening",
                "name": "Health Sensitive Screening",
                "status": "active",
                "platform": "boss",
                "bound_to_stage": "candidate_probe",
                "strategy": {"summary": "Require stronger quality bar."},
                "health_check_config": {"minimum_overall_score": 85},
            },
        )
        self.assertEqual(created_skill.status_code, 201)
        skill_id = created_skill.json()["id"]

        dashboard = self.client.get("/api/dashboard")
        candidate_id = dashboard.json()["candidates"][0]["id"]

        queued = self.client.post(
            "/api/agent/tasks",
            json={
                "task_type": "candidate_probe",
                "priority": 240,
                "candidate_id": candidate_id,
                "adaptive_stage": "candidate_probe",
                "payload": {"jd_criteria": "Distributed systems"},
            },
        )
        self.assertEqual(queued.status_code, 200)

        run_once = self.client.post("/api/agent/run-once")
        self.assertEqual(run_once.status_code, 200)
        self.assertEqual(run_once.json()["status"], "completed")

        with container.session_factory() as session:
            skill = session.query(Skill).filter(Skill.id == skill_id).first()
            self.assertIsNotNone(skill)
            self.assertEqual(skill.status, "degraded")
            self.assertEqual(skill.last_health_status, "warning")
            self.assertIsNotNone(skill.last_health_check)

    def test_blocked_task_approval_resumes_execution(self) -> None:
        from scene_pilot.runtime.models import LLMResponse
        from scene_pilot.runtime.providers import ScriptedProvider

        container = self.client.app.state.container
        container.agent_control.agent_loop.provider = ScriptedProvider(
            provider_name="scripted-blocked-task",
            responses=[
                LLMResponse(
                    content="Need human review before continuing.",
                    requires_human_input=True,
                ),
                LLMResponse(
                    content="Human review applied.",
                    result_data={"status": "pass", "summary": "Resume completed."},
                ),
            ],
        )

        dashboard = self.client.get("/api/dashboard")
        candidate_id = dashboard.json()["candidates"][0]["id"]
        queued = self.client.post(
            "/api/agent/tasks",
            json={
                "task_type": "candidate_probe",
                "priority": 210,
                "candidate_id": candidate_id,
                "payload": {"jd_criteria": "Resume review"},
            },
        )
        task_id = queued.json()["task_id"]

        first_run = self.client.post("/api/agent/run-once")
        self.assertEqual(first_run.status_code, 200)
        self.assertEqual(first_run.json()["status"], "waiting_human")

        approvals = self.client.get("/api/approvals?pending_only=true")
        self.assertEqual(approvals.status_code, 200)
        blocked_approval = next(
            item
            for item in approvals.json()
            if item["target_type"] == "blocked_task" and item["target_id"] == task_id
        )
        self.assertEqual(blocked_approval["payload"]["blocked_task"]["task_id"], task_id)
        self.assertIn("resume_task", blocked_approval["payload"])

        checkpoints = self.client.get("/api/recruit-agent/runtime/checkpoints?open_only=true")
        self.assertEqual(checkpoints.status_code, 200)
        checkpoint = next(item for item in checkpoints.json() if item["approval_id"] == blocked_approval["id"])
        self.assertEqual(checkpoint["status"], "open")
        self.assertEqual(checkpoint["checkpoint_kind"], "approval")

        approved = self.client.post(
            f"/api/approvals/{blocked_approval['id']}/approve",
            json={"reviewer": "desktop-user", "reason": "Continue after human review"},
        )
        self.assertEqual(approved.status_code, 200)
        self.assertEqual(approved.json()["status"], "approved")
        self.assertEqual(approved.json()["payload"]["resolution"]["status"], "approved")
        self.assertTrue(approved.json()["payload"]["resolution"]["resumed"])

        resolved_checkpoints = self.client.get("/api/recruit-agent/runtime/checkpoints")
        self.assertEqual(resolved_checkpoints.status_code, 200)
        resolved_checkpoint = next(item for item in resolved_checkpoints.json() if item["approval_id"] == blocked_approval["id"])
        self.assertEqual(resolved_checkpoint["status"], "resolved")

        second_run = self.client.post("/api/agent/run-once")
        self.assertEqual(second_run.status_code, 200)
        self.assertEqual(second_run.json()["status"], "completed")

    def test_runtime_concurrency_limit_defers_candidate_runs(self) -> None:
        from scene_pilot.repositories import AgentRunRepository, AgentSessionRepository
        from scene_pilot.services.recruit_agent import ensure_primary_recruit_agent_profile

        settings_response = self.client.patch(
            "/api/settings",
            json={"platform": {"maxConcurrentRuns": 1}},
        )
        self.assertEqual(settings_response.status_code, 200)

        blocker_candidate = self.client.post(
            "/api/candidates",
            json={
                "name": "Blocking Candidate",
                "platform": "site",
                "current_status": "screening",
                "jd_id": "jd-runtime",
            },
        ).json()
        target_candidate = self.client.post(
            "/api/candidates",
            json={
                "name": "Queued Candidate",
                "platform": "site",
                "current_status": "discovered",
                "jd_id": "jd-runtime",
            },
        ).json()

        container = self.client.app.state.container
        with container.session_factory() as session:
            profile = ensure_primary_recruit_agent_profile(session)
            session_repo = AgentSessionRepository(session)
            runtime_session = session_repo.by_agent_and_key(agent_profile_id=profile.id, session_key="primary")
            if runtime_session is None:
                runtime_session = session_repo.create(
                    {
                        "agent_profile_id": profile.id,
                        "session_key": "primary",
                        "status": "active",
                        "runtime_metadata": {"agent_key": profile.agent_key},
                    }
                )
            AgentRunRepository(session).create(
                {
                    "session_id": runtime_session.id,
                    "candidate_id": blocker_candidate["id"],
                    "jd_id": blocker_candidate["jd_id"],
                    "platform": "site",
                    "lane": "candidate",
                    "run_type": "candidate_probe",
                    "status": "running",
                    "priority": 300,
                    "queue_task_id": "existing-runtime-run",
                    "runtime_metadata": {"seeded": True},
                }
            )

        queued = self.client.post(
            "/api/agent/tasks",
            json={
                "task_type": "candidate_probe",
                "priority": 180,
                "candidate_id": target_candidate["id"],
                "payload": {"jd_criteria": "Global limit"},
            },
        )
        self.assertEqual(queued.status_code, 200)
        task_id = queued.json()["task_id"]

        run_once = self.client.post("/api/agent/run-once")
        self.assertEqual(run_once.status_code, 200)
        self.assertEqual(run_once.json()["status"], "deferred")

        queue_snapshot = self.client.get("/api/agent/queue?status=pending")
        self.assertEqual(queue_snapshot.status_code, 200)
        self.assertTrue(any(item["task_id"] == task_id for item in queue_snapshot.json()))

        runtime_runs = self.client.get(f"/api/recruit-agent/runtime/runs?candidate_id={target_candidate['id']}")
        self.assertEqual(runtime_runs.status_code, 200)
        deferred_run = next(item for item in runtime_runs.json() if item["queue_task_id"] == task_id)
        self.assertEqual(deferred_run["status"], "queued")

    def test_blocked_task_reject_marks_closure_metadata(self) -> None:
        from scene_pilot.runtime.models import LLMResponse
        from scene_pilot.runtime.providers import ScriptedProvider

        container = self.client.app.state.container
        container.agent_control.agent_loop.provider = ScriptedProvider(
            provider_name="scripted-blocked-task-reject",
            responses=[LLMResponse(content="Need human review before continuing.", requires_human_input=True)],
        )

        dashboard = self.client.get("/api/dashboard")
        candidate_id = dashboard.json()["candidates"][0]["id"]
        queued = self.client.post(
            "/api/agent/tasks",
            json={
                "task_type": "candidate_probe",
                "priority": 205,
                "candidate_id": candidate_id,
                "payload": {"jd_criteria": "Resume review"},
            },
        )
        task_id = queued.json()["task_id"]

        first_run = self.client.post("/api/agent/run-once")
        self.assertEqual(first_run.status_code, 200)
        self.assertEqual(first_run.json()["status"], "waiting_human")

        approvals = self.client.get("/api/approvals?pending_only=true")
        self.assertEqual(approvals.status_code, 200)
        blocked_approval = next(
            item
            for item in approvals.json()
            if item["target_type"] == "blocked_task" and item["target_id"] == task_id
        )

        rejected = self.client.post(
            f"/api/approvals/{blocked_approval['id']}/reject",
            json={"reviewer": "desktop-user", "reason": "Do not resume"},
        )
        self.assertEqual(rejected.status_code, 200)
        self.assertEqual(rejected.json()["status"], "rejected")
        self.assertEqual(rejected.json()["payload"]["resolution"]["status"], "rejected")
        self.assertIn("closed_at", rejected.json()["payload"])
        self.assertFalse(rejected.json()["payload"]["resolution"]["resumed"])

    def test_ai_auto_waiting_human_does_not_create_operator_interaction(self) -> None:
        from scene_pilot.runtime.models import LLMResponse
        from scene_pilot.runtime.providers import ScriptedProvider

        container = self.client.app.state.container
        container.agent_control.agent_loop.provider = ScriptedProvider(
            provider_name="scripted-ai-auto-waiting",
            responses=[
                LLMResponse(
                    content="Unexpected human escalation on ai_auto node.",
                    requires_human_input=True,
                )
            ],
        )

        candidate = self.client.post(
            "/api/candidates",
            json={
                "name": "AI Auto Candidate",
                "platform": "site",
                "current_status": "outreach_pending",
                "jd_id": "jd-ai-auto",
            },
        ).json()

        queued = self.client.post(
            "/api/agent/tasks",
            json={
                "task_type": "candidate_probe",
                "priority": 230,
                "candidate_id": candidate["id"],
                "payload": {"jd_criteria": "AI auto node"},
            },
        )
        self.assertEqual(queued.status_code, 200)

        run_once = self.client.post("/api/agent/run-once")
        self.assertEqual(run_once.status_code, 200)
        self.assertEqual(run_once.json()["status"], "waiting_human")

        interactions = self.client.get(f"/api/recruit-agent/runtime/operator-interactions?candidate_id={candidate['id']}")
        self.assertEqual(interactions.status_code, 200)
        self.assertEqual(interactions.json(), [])

    def test_human_required_locked_node_creates_operator_interaction_from_human_actions(self) -> None:
        class _ShouldNotRunProvider:
            provider_name = "should-not-run"

            def generate(self, messages, *, tools=None, task=None, max_tokens=None, temperature=None):
                raise AssertionError("human_required 节点应在进入 LLM 前直接挂起")

        container = self.client.app.state.container
        container.agent_control.agent_loop.provider = _ShouldNotRunProvider()

        candidate = self.client.post(
            "/api/candidates",
            json={
                "name": "Locked Review Candidate",
                "platform": "site",
                "current_status": "offer_pending",
                "jd_id": "jd-offer",
            },
        ).json()

        queued = self.client.post(
            "/api/agent/tasks",
            json={
                "task_type": "candidate_outreach",
                "priority": 240,
                "candidate_id": candidate["id"],
                "payload": {"jd_criteria": "locked human review"},
            },
        )
        self.assertEqual(queued.status_code, 200)

        run_once = self.client.post("/api/agent/run-once")
        self.assertEqual(run_once.status_code, 200)
        self.assertEqual(run_once.json()["status"], "waiting_human")

        interactions = self.client.get(f"/api/recruit-agent/runtime/operator-interactions?candidate_id={candidate['id']}")
        self.assertEqual(interactions.status_code, 200)
        payload = interactions.json()
        self.assertEqual(len(payload), 1)
        interaction = payload[0]
        self.assertIn("已锁定", interaction["agent_prompt"])
        self.assertEqual(
            [item["label"] for item in interaction["suggested_options"]],
            ["确认发出 Offer"],
        )
        self.assertEqual(interaction["suggested_options"][0]["to_status"], "offer_sent")

    def test_agent_transition_candidate_records_history_and_advances_milestone(self) -> None:
        from scene_pilot.runtime.models import LLMResponse
        from scene_pilot.runtime.providers import ScriptedProvider

        container = self.client.app.state.container
        container.agent_control.agent_loop.provider = ScriptedProvider(
            provider_name="scripted-transition-history",
            responses=[
                LLMResponse(
                    content="Offline scoring completed.",
                    result_data={
                        "status": "completed",
                        "summary": "Scoring completed",
                        "candidates": [
                            {
                                "candidate_id": "__CANDIDATE_ID__",
                                "name": "Offline Score Candidate",
                                "platform": "site",
                                "status": "offline_score_passed",
                                "summary": "离线简历评分通过。",
                            }
                        ],
                    },
                )
            ],
        )

        candidate = self.client.post(
            "/api/candidates",
            json={
                "name": "Offline Score Candidate",
                "platform": "site",
                "current_status": "offline_scoring",
                "deepest_milestone": "M06",
                "jd_id": "jd-offline",
            },
        ).json()
        container.agent_control.agent_loop.provider.responses[0].result_data["candidates"][0]["candidate_id"] = candidate["id"]

        queued = self.client.post(
            "/api/agent/tasks",
            json={
                "task_type": "candidate_scoring",
                "priority": 250,
                "candidate_id": candidate["id"],
                "payload": {"jd_criteria": "offline scoring"},
            },
        )
        self.assertEqual(queued.status_code, 200)

        run_once = self.client.post("/api/agent/run-once")
        self.assertEqual(run_once.status_code, 200)
        self.assertEqual(run_once.json()["status"], "completed")

        refreshed = self.client.get(f"/api/candidates/{candidate['id']}")
        self.assertEqual(refreshed.status_code, 200)
        self.assertEqual(refreshed.json()["current_status"], "offline_score_passed")
        self.assertEqual(refreshed.json()["deepest_milestone"], "M08")

        transitions = self.client.get(f"/api/recruit-agent/candidates/{candidate['id']}/transitions")
        self.assertEqual(transitions.status_code, 200)
        latest = transitions.json()[-1]
        self.assertEqual(latest["actor"], "agent")
        self.assertEqual(latest["to_status"], "offline_score_passed")
        self.assertEqual(latest["milestone_updated"], "M08")
        self.assertEqual(latest["trigger"], "标记线下评分通过")
        self.assertEqual(latest["metadata"]["criteria_ref"]["skillId"], "resume_scoring_v1")

    def test_retry_outbound_updates_waiting_retry_state_and_last_contacted_at(self) -> None:
        from scene_pilot.db.base import utcnow
        from scene_pilot.runtime.models import LLMResponse
        from scene_pilot.runtime.providers import ScriptedProvider

        container = self.client.app.state.container
        container.agent_control.agent_loop.provider = ScriptedProvider(
            provider_name="scripted-waiting-retry-outbound",
            responses=[
                LLMResponse(
                    content="Follow-up reminder sent.",
                    result_data={
                        "status": "completed",
                        "summary": "Sent a follow-up reminder because the candidate has not replied yet.",
                        "message": "跟进一下，方便的话麻烦回复我。",
                        "message_sent": True,
                    },
                )
            ],
        )

        previous_contacted_at = utcnow() - timedelta(hours=96)
        candidate = self.client.post(
            "/api/candidates",
            json={
                "name": "Retry Follow Up Candidate",
                "platform": "boss",
                "current_status": "outreach_sent",
                "jd_id": "jd-retry-follow-up",
                "last_contacted_at": previous_contacted_at.isoformat(),
                "state_snapshot": {
                    "snapshot_metadata": {
                        "waiting_retry": {
                            "status": "outreach_sent",
                            "retry_count": 1,
                            "last_outbound_at": previous_contacted_at.isoformat(),
                            "max_retries": 2,
                            "retry_after_hours": 72,
                            "close_after_hours": 168,
                        }
                    }
                },
            },
        ).json()

        queued = self.client.post(
            "/api/agent/tasks",
            json={
                "task_type": "candidate_outreach",
                "priority": 235,
                "candidate_id": candidate["id"],
                "payload": {
                    "retryContext": {
                        "sourceStatus": "outreach_sent",
                        "retryCount": 2,
                        "maxRetries": 2,
                        "retryAfterHours": 72,
                        "closeAfterHours": 168,
                        "reason": "retry_window_elapsed",
                    }
                },
            },
        )
        self.assertEqual(queued.status_code, 200)

        run_once = self.client.post("/api/agent/run-once")
        self.assertEqual(run_once.status_code, 200)
        self.assertEqual(run_once.json()["status"], "completed")

        refreshed = self.client.get(f"/api/candidates/{candidate['id']}")
        self.assertEqual(refreshed.status_code, 200)
        payload = refreshed.json()
        self.assertEqual(payload["current_status"], "outreach_sent")
        self.assertIsNotNone(payload["last_contacted_at"])
        self.assertGreater(payload["last_contacted_at"], previous_contacted_at.isoformat())
        waiting_retry = payload["state_snapshot"]["snapshot_metadata"]["waiting_retry"]
        self.assertEqual(waiting_retry["status"], "outreach_sent")
        self.assertEqual(waiting_retry["retry_count"], 2)
        self.assertEqual(waiting_retry["max_retries"], 2)
        self.assertEqual(waiting_retry["retry_after_hours"], 72)
        self.assertEqual(waiting_retry["close_after_hours"], 168)

    def test_agent_applies_conversation_rollback_signal_without_fake_outbound_message(self) -> None:
        from scene_pilot.models import CommunicationLog
        from scene_pilot.runtime.models import LLMResponse
        from scene_pilot.runtime.providers import ScriptedProvider

        container = self.client.app.state.container
        container.agent_control.agent_loop.provider = ScriptedProvider(
            provider_name="scripted-conversation-rollback-withdrew",
            responses=[
                LLMResponse(
                    content="Candidate already accepted another offer.",
                    result_data={
                        "status": "completed",
                        "summary": "Candidate explicitly withdrew from the process.",
                        "rollback_signal": {
                            "toStatus": "candidate_withdrew",
                            "reason": "候选人明确表示已接受其他 Offer。",
                            "evidenceExcerpt": "我已经接了别的 offer，先不继续了。",
                            "signalKind": "conversation_signal",
                        },
                    },
                )
            ],
        )

        candidate = self.client.post(
            "/api/candidates",
            json={
                "name": "Rollback Candidate",
                "platform": "boss",
                "current_status": "in_conversation",
                "deepest_milestone": "M04",
                "jd_id": "jd-rollback",
            },
        ).json()
        entry = self.client.post(
            f"/api/recruit-agent/candidate-threads/{candidate['id']}/entries",
            json={
                "direction": "inbound",
                "content": "我已经接了别的 offer，先不继续了。",
                "message_type": "text",
                "platform": "boss",
            },
        )
        self.assertEqual(entry.status_code, 201)

        queued = self.client.post(
            "/api/agent/tasks",
            json={
                "task_type": "candidate_outreach",
                "priority": 230,
                "candidate_id": candidate["id"],
                "payload": {},
            },
        )
        self.assertEqual(queued.status_code, 200)

        run_once = self.client.post("/api/agent/run-once")
        self.assertEqual(run_once.status_code, 200)
        self.assertEqual(run_once.json()["status"], "completed")

        refreshed = self.client.get(f"/api/candidates/{candidate['id']}")
        self.assertEqual(refreshed.status_code, 200)
        self.assertEqual(refreshed.json()["current_status"], "candidate_withdrew")

        transitions = self.client.get(f"/api/recruit-agent/candidates/{candidate['id']}/transitions")
        self.assertEqual(transitions.status_code, 200)
        latest = transitions.json()[-1]
        self.assertEqual(latest["actor"], "agent_override")
        self.assertEqual(latest["trigger"], "conversation_signal")
        self.assertEqual(latest["to_status"], "candidate_withdrew")
        self.assertEqual(latest["override_reason"], "候选人明确表示已接受其他 Offer。")
        self.assertEqual(latest["metadata"]["signal_kind"], "conversation_signal")

        with container.session_factory() as session:
            logs = (
                session.query(CommunicationLog)
                .filter(CommunicationLog.candidate_id == candidate["id"])
                .order_by(CommunicationLog.timestamp.asc())
                .all()
            )
            self.assertEqual(len(logs), 1)
            self.assertEqual(logs[0].direction, "inbound")

    def test_agent_applies_cooldown_rollback_signal_and_sets_cooldown_until(self) -> None:
        from scene_pilot.db.base import utcnow
        from scene_pilot.models import Candidate
        from scene_pilot.runtime.models import LLMResponse
        from scene_pilot.runtime.providers import ScriptedProvider

        container = self.client.app.state.container
        container.agent_control.agent_loop.provider = ScriptedProvider(
            provider_name="scripted-conversation-rollback-cooldown",
            responses=[
                LLMResponse(
                    content="Candidate asked to revisit later.",
                    result_data={
                        "status": "completed",
                        "summary": "Candidate prefers to pause and revisit later.",
                        "rollback_signal": {
                            "toStatus": "cooldown",
                            "reason": "候选人明确表示暂时不考虑换工作。",
                            "evidenceExcerpt": "最近不考虑换工作，一个月后再聊。",
                            "signalKind": "conversation_signal",
                            "cooldownDays": 14,
                        },
                    },
                )
            ],
        )

        candidate = self.client.post(
            "/api/candidates",
            json={
                "name": "Cooldown Candidate",
                "platform": "boss",
                "current_status": "in_conversation",
                "deepest_milestone": "M04",
                "jd_id": "jd-cooldown",
            },
        ).json()

        queued = self.client.post(
            "/api/agent/tasks",
            json={
                "task_type": "candidate_outreach",
                "priority": 225,
                "candidate_id": candidate["id"],
                "payload": {},
            },
        )
        self.assertEqual(queued.status_code, 200)

        run_once = self.client.post("/api/agent/run-once")
        self.assertEqual(run_once.status_code, 200)
        self.assertEqual(run_once.json()["status"], "completed")

        with container.session_factory() as session:
            refreshed = session.get(Candidate, candidate["id"])
            self.assertIsNotNone(refreshed)
            assert refreshed is not None
            self.assertEqual(refreshed.current_status, "cooldown")
            self.assertIsNotNone(refreshed.cooldown_until)
            remaining_days = (refreshed.cooldown_until.date() - utcnow().date()).days
            self.assertGreaterEqual(remaining_days, 13)
            self.assertLessEqual(remaining_days, 14)

        transitions = self.client.get(f"/api/recruit-agent/candidates/{candidate['id']}/transitions")
        self.assertEqual(transitions.status_code, 200)
        latest = transitions.json()[-1]
        self.assertEqual(latest["actor"], "agent_override")
        self.assertEqual(latest["trigger"], "conversation_signal")
        self.assertEqual(latest["to_status"], "cooldown")
        self.assertEqual(latest["metadata"]["conversation_signal"]["cooldown_days"], 14)

    def test_system_command_request_enforces_flag_and_whitelist(self) -> None:
        container = self.client.app.state.container

        policy = self.client.get("/api/agent/system-commands/policy")
        self.assertEqual(policy.status_code, 200)
        self.assertFalse(policy.json()["enabled"])

        blocked = self.client.post(
            "/api/agent/system-commands/request",
            json={"command": ["python3", "-m", "pytest"], "requested_by": "desktop-user"},
        )
        self.assertEqual(blocked.status_code, 403)

        container.flags.set_flag("skills.system_command", True)

        rejected = self.client.post(
            "/api/agent/system-commands/request",
            json={"command": ["rm", "-rf", "/tmp/not-allowed"], "requested_by": "desktop-user"},
        )
        self.assertEqual(rejected.status_code, 400)

        requested = self.client.post(
            "/api/agent/system-commands/request",
            json={
                "command": ["python3", "-m", "pytest", "services/backend/tests/test_runtime_tools.py"],
                "requested_by": "desktop-user",
                "rationale": "Validate the runtime tool contract.",
            },
        )
        self.assertEqual(requested.status_code, 201)
        self.assertEqual(requested.json()["target_type"], "system_command")
        self.assertEqual(requested.json()["status"], "pending")
        self.assertEqual(requested.json()["payload"]["command"][0:3], ["python3", "-m", "pytest"])

        approved = self.client.post(
            f"/api/approvals/{requested.json()['id']}/approve",
            json={"reviewer": "desktop-user", "reason": "Allowed for validation"},
        )
        self.assertEqual(approved.status_code, 200)
        self.assertEqual(approved.json()["status"], "approved")
        self.assertEqual(approved.json()["payload"]["execution_status"], "approved_but_disabled")
        self.assertFalse(approved.json()["payload"]["resolution"]["execution_enabled"])

    def test_system_command_execute_after_approval_when_enabled(self) -> None:
        container = self.client.app.state.container
        container.flags.set_flag("skills.system_command", True)
        container.system_commands.execution_enabled = True
        container.system_commands.whitelist = (
            *container.system_commands.whitelist,
            ("python3", "-c"),
        )

        requested = self.client.post(
            "/api/agent/system-commands/request",
            json={
                "command": ["python3", "-c", "print('system-command-ok')"],
                "requested_by": "desktop-user",
            },
        )
        self.assertEqual(requested.status_code, 201)

        not_ready = self.client.post(
            f"/api/agent/system-commands/{requested.json()['id']}/execute",
            json={"requested_by": "desktop-user"},
        )
        self.assertEqual(not_ready.status_code, 409)

        approved = self.client.post(
            f"/api/approvals/{requested.json()['id']}/approve",
            json={"reviewer": "desktop-user", "reason": "Safe local command"},
        )
        self.assertEqual(approved.status_code, 200)
        self.assertEqual(approved.json()["payload"]["command_resolution"]["execution_status"], "approved_ready")

        executed = self.client.post(
            f"/api/agent/system-commands/{requested.json()['id']}/execute",
            json={"requested_by": "desktop-user"},
        )
        self.assertEqual(executed.status_code, 200)
        self.assertEqual(executed.json()["payload"]["execution"]["status"], "completed")
        self.assertEqual(executed.json()["payload"]["command_resolution"]["execution_status"], "completed")
        self.assertIn("system-command-ok", executed.json()["payload"]["execution"]["stdout"])


if __name__ == "__main__":
    unittest.main()
