from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from typing import Any

from sqlalchemy.orm import Session, sessionmaker

from recruit_agent.core.settings import AppSettings, load_settings
from recruit_agent.db.session import create_engine_from_settings, create_session_factory, initialize_database
from recruit_agent.models import ApprovalItem, Candidate, Skill, Workflow
from recruit_agent.platforms import BossPlatformAdapter, PlatformAdapter
from recruit_agent.runtime.agent_loop import AgentLoop
from recruit_agent.runtime.models import LLMResponse, Message
from recruit_agent.runtime.prompts import PromptBuilder
from recruit_agent.runtime.providers import AnthropicProvider, LLMProvider, OpenAICompatibleProvider, ProviderRegistry, ScriptedProvider
from recruit_agent.runtime.tools import ToolDefinition, ToolRegistry
from recruit_agent.scheduler.queue import SqlAlchemyQueue
from recruit_agent.scheduler.scheduler import SerialScheduler
from recruit_agent.services.agent import AgentControlService
from recruit_agent.services.dashboard import DashboardService
from recruit_agent.services.events import EventStreamService
from recruit_agent.services.feature_flags import FeatureFlagService
from recruit_agent.repositories import SkillRepository
from recruit_agent.services.skills import SkillHealthSweepService, SkillLifecycleService, SkillSafetyService
from recruit_agent.services.sync import SyncService
from recruit_agent.services.system_commands import SystemCommandService
from recruit_agent.workflows.engine import WorkflowEngine


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


def _scripted_provider() -> ScriptedProvider:
    responses = [
        LLMResponse(
            content="Structured screening result generated by scaffold runtime.",
            result_data={"status": "pass", "summary": "Scaffold result"},
        )
    ] * 64
    return ScriptedProvider(provider_name="scripted_default", responses=responses)


@dataclass(slots=True)
class RegistryBackedProvider:
    registry: ProviderRegistry
    preferred_provider: str | None = None
    provider_name: str = "registry_runtime"

    def generate(
        self,
        messages: list[Message],
        *,
        tools: list[dict[str, Any]] | None = None,
        task: dict[str, Any] | None = None,
        max_tokens: int | None = None,
        temperature: float | None = None,
    ) -> LLMResponse:
        return self.registry.generate(
            messages,
            preferred_provider=self.preferred_provider,
            tools=tools,
            task=task,
            max_tokens=max_tokens,
            temperature=temperature,
        )


def _build_provider_registry(settings: AppSettings) -> tuple[ProviderRegistry, LLMProvider]:
    registry = ProviderRegistry()
    preferred_provider: str | None = None

    openai_config = settings.build_provider_config("openai_compatible")
    if openai_config.has_http_credentials():
        registry.register(OpenAICompatibleProvider(openai_config))
        preferred_provider = preferred_provider or openai_config.provider_name

    anthropic_config = settings.build_provider_config("anthropic")
    if anthropic_config.has_http_credentials():
        registry.register(AnthropicProvider(anthropic_config))
        preferred_provider = preferred_provider or anthropic_config.provider_name

    registry.register(_scripted_provider())
    return registry, RegistryBackedProvider(registry=registry, preferred_provider=preferred_provider)


def _build_sync_target(settings: AppSettings) -> dict[str, Any]:
    sync_settings = settings.intranet_sync
    provider_config = settings.provider_config or {}
    return {
        "kind": "intranet",
        "base_url": str(sync_settings.base_url or provider_config.get("intranet_base_url") or ""),
        "api_path": str(sync_settings.api_path),
        "timeout_seconds": int(sync_settings.timeout_seconds or provider_config.get("intranet_timeout_seconds", 10) or 10),
    }


def _candidate_payload(candidate: Candidate) -> dict[str, Any]:
    candidate_key = candidate.platform_candidate_id or candidate.id
    return {
        "candidate_id": candidate_key,
        "platform_candidate_id": candidate.platform_candidate_id or candidate_key,
        "name": candidate.name,
        "platform": candidate.platform or "site",
        "status": candidate.status,
        "contact_info": dict(candidate.contact_info or {}),
        "ai_scores": dict(candidate.ai_scores or {}),
        "ai_reasoning": candidate.ai_reasoning,
        "resume_path": candidate.resume_path,
        "online_resume_text": candidate.online_resume_text,
        "cooldown_until": candidate.cooldown_until.isoformat() if candidate.cooldown_until else None,
        "last_contacted_at": candidate.last_contacted_at.isoformat() if candidate.last_contacted_at else None,
    }


def _resolve_candidate(session: Session, candidate_id: str) -> Candidate:
    candidate = session.query(Candidate).filter(Candidate.id == candidate_id).first()
    if candidate is not None:
        return candidate
    candidate = session.query(Candidate).filter(Candidate.platform_candidate_id == candidate_id).first()
    if candidate is not None:
        return candidate
    raise KeyError(f"Unknown runtime-scene candidate: {candidate_id}")


def _build_recruiting_site_adapter(session_factory: sessionmaker[Session], settings: AppSettings) -> PlatformAdapter:
    cooldown_days = settings.provider_runtime_settings().cooldown_days

    def _discover(query: dict[str, Any]) -> list[dict[str, Any]]:
        with session_factory() as session:
            store = {
                candidate.platform_candidate_id or candidate.id: _candidate_payload(candidate)
                for candidate in session.query(Candidate).all()
            }
        adapter = BossPlatformAdapter(browser_context={"cooldown_days": cooldown_days}, candidate_store=store)
        return [snapshot.raw for snapshot in adapter.discover_candidates(query)]

    def _inspect(candidate_id: str) -> dict[str, Any]:
        with session_factory() as session:
            return _candidate_payload(_resolve_candidate(session, candidate_id))

    def _send_message(candidate_id: str, message: str) -> dict[str, Any]:
        with session_factory() as session:
            candidate = _resolve_candidate(session, candidate_id)
            candidate.status = "pending_reply"
            candidate.last_contacted_at = _utcnow()
            contact_info = dict(candidate.contact_info or {})
            contact_info["last_outbound_message"] = message
            candidate.contact_info = contact_info
            session.commit()
            return {
                "candidate_id": candidate.platform_candidate_id or candidate.id,
                "message": message,
                "status": "sent",
                "sent_at": candidate.last_contacted_at.isoformat(),
            }

    def _request_resume(candidate_id: str) -> dict[str, Any]:
        with session_factory() as session:
            candidate = _resolve_candidate(session, candidate_id)
            candidate.status = "awaiting_resume"
            contact_info = dict(candidate.contact_info or {})
            contact_info["resume_requested_at"] = _utcnow().isoformat()
            candidate.contact_info = contact_info
            session.commit()
            return {
                "candidate_id": candidate.platform_candidate_id or candidate.id,
                "status": "requested",
                "requested_at": contact_info["resume_requested_at"],
            }

    def _score(candidate_id: str, scores: dict[str, Any]) -> dict[str, Any]:
        with session_factory() as session:
            candidate = _resolve_candidate(session, candidate_id)
            merged_scores = dict(candidate.ai_scores or {})
            merged_scores.update(scores)
            candidate.ai_scores = merged_scores
            overall = merged_scores.get("overall")
            if isinstance(overall, (int, float)) and overall >= 70:
                candidate.status = "screening"
            else:
                candidate.status = "candidate_scoring"
            session.commit()
            return {
                "candidate_id": candidate.platform_candidate_id or candidate.id,
                "status": candidate.status,
                "overall_score": overall,
                "scores": merged_scores,
            }

    def _archive(candidate_id: str, reason: str) -> dict[str, Any]:
        with session_factory() as session:
            candidate = _resolve_candidate(session, candidate_id)
            candidate.status = "archived"
            candidate.ai_reasoning = reason
            session.commit()
            return {
                "candidate_id": candidate.platform_candidate_id or candidate.id,
                "status": "archived",
                "reason": reason,
            }

    def _cooldown(candidate_id: str) -> bool:
        with session_factory() as session:
            candidate = _resolve_candidate(session, candidate_id)
            adapter = BossPlatformAdapter(
                browser_context={"cooldown_days": cooldown_days},
                candidate_store={candidate.platform_candidate_id or candidate.id: _candidate_payload(candidate)},
            )
            return adapter.check_cooldown(candidate.platform_candidate_id or candidate.id)

    return BossPlatformAdapter(
        browser_context={"cooldown_days": cooldown_days},
        action_handlers={
            "healthcheck": lambda: True,
            "discover_candidates": _discover,
            "inspect_candidate": _inspect,
            "send_message": _send_message,
            "request_resume": _request_resume,
            "score_candidate": _score,
            "archive_candidate": _archive,
            "check_cooldown": _cooldown,
        },
    )


def _register_recruiting_site_tools(tools: ToolRegistry, adapter: PlatformAdapter) -> None:
    tools.register(
        ToolDefinition(
            name="boss_discover_candidates",
            description="Compatibility alias: discover candidates in the current runtime scene.",
            parameters={
                "type": "object",
                "properties": {},
                "additionalProperties": True,
            },
            handler=lambda args: [candidate.raw for candidate in adapter.discover_candidates(args)],
        )
    )
    tools.register(
        ToolDefinition(
            name="boss_inspect_candidate",
            description="Compatibility alias: inspect a candidate profile in the current runtime scene.",
            parameters={
                "type": "object",
                "properties": {"candidate_id": {"type": "string"}},
                "required": ["candidate_id"],
            },
            handler=lambda args: adapter.inspect_candidate(str(args["candidate_id"])).raw,
        )
    )
    tools.register(
        ToolDefinition(
            name="boss_send_message",
            description="Compatibility alias: send a message to a candidate in the current runtime scene.",
            parameters={
                "type": "object",
                "properties": {
                    "candidate_id": {"type": "string"},
                    "message": {"type": "string"},
                },
                "required": ["candidate_id", "message"],
            },
            handler=lambda args: adapter.send_message(str(args["candidate_id"]), str(args["message"])),
        )
    )
    tools.register(
        ToolDefinition(
            name="boss_request_resume",
            description="Compatibility alias: request a resume from a candidate in the current runtime scene.",
            parameters={
                "type": "object",
                "properties": {"candidate_id": {"type": "string"}},
                "required": ["candidate_id"],
            },
            handler=lambda args: adapter.request_resume(str(args["candidate_id"])),
        )
    )
    tools.register(
        ToolDefinition(
            name="boss_score_candidate",
            description="Compatibility alias: record structured scoring for a candidate in the current runtime scene.",
            parameters={
                "type": "object",
                "properties": {
                    "candidate_id": {"type": "string"},
                    "scores": {"type": "object"},
                },
                "required": ["candidate_id", "scores"],
            },
            handler=lambda args: adapter.score_candidate(str(args["candidate_id"]), dict(args["scores"])),
        )
    )
    tools.register(
        ToolDefinition(
            name="boss_archive_candidate",
            description="Compatibility alias: archive a candidate in the current runtime scene with a reason.",
            parameters={
                "type": "object",
                "properties": {
                    "candidate_id": {"type": "string"},
                    "reason": {"type": "string"},
                },
                "required": ["candidate_id", "reason"],
            },
            handler=lambda args: adapter.archive_candidate(str(args["candidate_id"]), str(args["reason"])),
        )
    )


@dataclass(slots=True)
class AppContainer:
    settings: AppSettings
    session_factory: sessionmaker[Session]
    flags: FeatureFlagService
    providers: ProviderRegistry
    tools: ToolRegistry
    workflow_engine: WorkflowEngine
    scheduler: SerialScheduler
    events: EventStreamService
    agent_control: AgentControlService
    dashboard: DashboardService
    sync: SyncService
    skill_lifecycle: SkillLifecycleService
    skill_safety: SkillSafetyService
    system_commands: SystemCommandService

    def _build_runtime_tools(self, settings: AppSettings) -> tuple[ToolRegistry, PlatformAdapter]:
        tools = ToolRegistry()
        tools.register(tools.build_result_submission_tool())
        tools.register(
            ToolDefinition(
                name="record_note",
                description="Store an audit note for the current candidate.",
                parameters={
                    "type": "object",
                    "properties": {"note": {"type": "string"}},
                    "required": ["note"],
                },
                handler=lambda args: {"recorded": True, "note": args.get("note", "")},
            )
        )
        tools.register(tools.build_system_command_tool(self.system_commands.request_tool_command))

        site_adapter = _build_recruiting_site_adapter(self.session_factory, settings)
        _register_recruiting_site_tools(tools, site_adapter)
        return tools, site_adapter

    def reload_settings(self, settings: AppSettings) -> None:
        self.settings = settings
        self.dashboard.settings = settings
        self.sync.intranet_enabled = settings.feature_flags.enable_intranet_sync
        self.sync.target = _build_sync_target(settings)
        self.flags.merge(
            {
                "skills.auto_activate": False,
                "skills.health_autonomy": settings.feature_flags.enable_skill_health_autonomy,
                "skills.system_command": settings.feature_flags.enable_system_commands,
                "feature.autonomy": settings.feature_flags.enable_autonomy,
                "feature.outbound_messaging": settings.feature_flags.enable_outbound_messaging,
            }
        )

        providers, runtime_provider = _build_provider_registry(settings)
        self.providers = providers

        tools, site_adapter = self._build_runtime_tools(settings)
        self.tools = tools
        self.agent_control.platform_adapter = site_adapter

        if self.agent_control.agent_loop is not None:
            self.agent_control.agent_loop.provider = runtime_provider
            self.agent_control.agent_loop.tools = tools

    @classmethod
    def build(cls, settings: AppSettings | None = None, *, seed_demo: bool | None = None) -> "AppContainer":
        resolved_settings = settings or load_settings()
        engine = create_engine_from_settings(resolved_settings)
        initialize_database(engine)
        session_factory = create_session_factory(engine)

        flags = FeatureFlagService(
            {
                "skills.auto_activate": False,
                "skills.health_autonomy": resolved_settings.feature_flags.enable_skill_health_autonomy,
                "skills.system_command": resolved_settings.feature_flags.enable_system_commands,
                "feature.autonomy": resolved_settings.feature_flags.enable_autonomy,
                "feature.outbound_messaging": resolved_settings.feature_flags.enable_outbound_messaging,
            }
        )
        providers, runtime_provider = _build_provider_registry(resolved_settings)

        events = EventStreamService()
        system_commands = SystemCommandService(
            session_factory=session_factory,
            flags=flags,
            events=events,
        )
        tools = ToolRegistry()
        tools.register(tools.build_result_submission_tool())
        tools.register(
            ToolDefinition(
                name="record_note",
                description="Store an audit note for the current candidate.",
                parameters={
                    "type": "object",
                    "properties": {"note": {"type": "string"}},
                    "required": ["note"],
                },
                handler=lambda args: {"recorded": True, "note": args.get("note", "")},
            )
        )
        tools.register(tools.build_system_command_tool(system_commands.request_tool_command))
        workflow_engine = WorkflowEngine(session_factory=session_factory)
        site_adapter = _build_recruiting_site_adapter(session_factory, resolved_settings)
        _register_recruiting_site_tools(tools, site_adapter)
        agent_loop = AgentLoop(provider=runtime_provider, tools=tools, prompt_builder=PromptBuilder())
        scheduler = SerialScheduler(queue=SqlAlchemyQueue(session_factory), follow_up_factory=workflow_engine.build_follow_up_factory())
        sync = SyncService(
            intranet_enabled=resolved_settings.feature_flags.enable_intranet_sync,
            session_factory=session_factory,
            target=_build_sync_target(resolved_settings),
        )
        agent_control = AgentControlService(
            scheduler=scheduler,
            workflow_engine=workflow_engine,
            agent_loop=agent_loop,
            events=events,
            flags=flags,
            platform_adapter=site_adapter,
            sync_service=sync,
            session_factory=session_factory,
        )
        scheduler.runner = agent_control.build_runner()
        dashboard = DashboardService(resolved_settings, events, sync)
        skill_lifecycle = SkillLifecycleService(flags=flags)
        skill_safety = SkillSafetyService(flags=flags)

        container = cls(
            settings=resolved_settings,
            session_factory=session_factory,
            flags=flags,
            providers=providers,
            tools=tools,
            workflow_engine=workflow_engine,
            scheduler=scheduler,
            events=events,
            agent_control=agent_control,
            dashboard=dashboard,
            sync=sync,
            skill_lifecycle=skill_lifecycle,
            skill_safety=skill_safety,
            system_commands=system_commands,
        )
        recovered_tasks = 0
        recover_stale = getattr(container.scheduler.queue, "recover_stale", None)
        if callable(recover_stale):
            recovered_tasks = int(recover_stale())
        should_seed = seed_demo if seed_demo is not None else settings is None
        if should_seed:
            container.seed()
        if recovered_tasks:
            events.publish(
                "warning",
                "scheduler",
                "Recovered stale queued tasks from a previous runtime.",
                recovered_tasks=recovered_tasks,
            )
        events.publish("info", "bootstrap", "Application container initialized.")
        return container

    def run_skill_health_sweep(
        self,
        *,
        statuses: list[str] | None = None,
        platform: str | None = None,
        observed_results_by_skill: dict[str, dict[str, Any]] | None = None,
    ) -> dict[str, Any]:
        with self.session_factory() as session:
            repo = SkillRepository(session)
            sweep = SkillHealthSweepService()
            selected_statuses = statuses or ["active", "approved"]
            selected_skills = sweep.filter_skills(
                repo.list(limit=5000, offset=0),
                statuses=selected_statuses,
                platform=platform,
            )
            sweep_result = sweep.run(
                selected_skills,
                observed_results_by_skill=observed_results_by_skill,
            )

            degraded_skill_ids: list[str] = []
            healthy_skill_ids: list[str] = []
            for skill, _result in sweep_result.results:
                updated = repo.update(
                    skill,
                    {
                        "status": str(skill.status),
                        "last_health_check": skill.last_health_check,
                        "last_health_status": skill.last_health_status,
                        "updated_at": skill.updated_at,
                    },
                )
                if updated.status == "degraded":
                    degraded_skill_ids.append(updated.skill_id)
                elif updated.last_health_status == "healthy":
                    healthy_skill_ids.append(updated.skill_id)

            return {
                "checked_count": sweep_result.checked_count,
                "degraded_count": sweep_result.degraded_count,
                "statuses": selected_statuses,
                "platform": platform,
                "degraded_skill_ids": degraded_skill_ids,
                "healthy_skill_ids": healthy_skill_ids,
            }

    def seed(self) -> None:
        with self.session_factory() as session:
            if session.query(Candidate).first() is not None:
                return

            screening_nodes: list[dict[str, Any]] = [
                {
                    "id": "discover_candidate",
                    "name": "Discover candidates",
                    "task_type": "discover_candidate",
                    "kind": "discover",
                    "status": "approved",
                    "owner": "Scheduler",
                    "description": "Search and ingest candidate profiles.",
                    "transitions": [{"condition": "default", "target": "initial_screening"}],
                },
                {
                    "id": "initial_screening",
                    "name": "Initial screening",
                    "task_type": "initial_screening",
                    "kind": "screen",
                    "status": "running",
                    "owner": "Agent",
                    "description": "Read resumes and evaluate against JD criteria.",
                    "requires_skill": True,
                    "skill_id": "resume_screening",
                    "transitions": [
                        {"condition": "pass", "target": "request_resume"},
                        {"condition": "fail", "target": "cooldown"},
                        {"condition": "default", "target": "request_resume"},
                    ],
                },
                {
                    "id": "request_resume",
                    "name": "Request resume",
                    "task_type": "request_resume",
                    "kind": "resume",
                    "status": "idle",
                    "owner": "Agent",
                    "description": "Collect structured resume artifacts.",
                    "transitions": [{"condition": "default", "target": "candidate_scoring"}],
                },
                {
                    "id": "candidate_scoring",
                    "name": "Candidate scoring",
                    "task_type": "candidate_scoring",
                    "kind": "score",
                    "status": "idle",
                    "owner": "Agent",
                    "description": "Produce scoring and reasoning payloads.",
                    "transitions": [
                        {"condition": "pass", "target": "hr_review"},
                        {"condition": "fail", "target": "cooldown"},
                        {"condition": "default", "target": "hr_review"},
                    ],
                },
                {
                    "id": "hr_review",
                    "name": "HR review",
                    "task_type": "hr_review",
                    "kind": "review",
                    "status": "blocked",
                    "owner": "Human",
                    "description": "Await desktop approval before talent pool sync.",
                    "transitions": [],
                },
                {
                    "id": "cooldown",
                    "name": "Cooldown",
                    "task_type": "cooldown",
                    "kind": "cooldown",
                    "status": "idle",
                    "owner": "System",
                    "description": "Hold future contact attempts until the cooldown window expires.",
                    "transitions": [],
                },
            ]

            session.add_all(
                [
                    Candidate(
                        name="Mia Chen",
                        platform="Recruiting scene",
                        platform_candidate_id="site_001",
                        status="screening",
                        current_workflow_node="initial_screening",
                        jd_id="Frontend Platform Engineer",
                        contact_info={
                            "title": "Senior Frontend Engineer",
                            "location": "Shanghai",
                            "experience_years": 8,
                            "next_action": "Verify system design depth and React performance examples.",
                            "tags": ["React", "Design Systems", "Performance"],
                        },
                        ai_scores={"overall": 92},
                        ai_reasoning="Strong product sense and strong ownership.",
                        resume_path="/tmp/mia-chen.pdf",
                        last_contacted_at=_utcnow() - timedelta(hours=2),
                    ),
                    Candidate(
                        name="Jason Li",
                        platform="Recruiting scene",
                        platform_candidate_id="site_002",
                        status="pending_communication",
                        current_workflow_node="initiate_communication",
                        jd_id="Platform Engineer",
                        contact_info={
                            "title": "Backend Engineer",
                            "location": "Hangzhou",
                            "experience_years": 6,
                            "next_action": "Send outreach message with salary range and team scope.",
                            "tags": ["Go", "PostgreSQL", "APIs"],
                        },
                        ai_scores={"overall": 84},
                        ai_reasoning="Reliable service design experience.",
                    ),
                    Candidate(
                        name="Luna Wang",
                        platform="Recruiting scene",
                        platform_candidate_id="site_003",
                        status="cooldown",
                        current_workflow_node="cooldown",
                        jd_id="Product Lead",
                        contact_info={
                            "title": "Product Manager",
                            "location": "Beijing",
                            "experience_years": 7,
                            "next_action": "Respect cooldown until the next contact window opens.",
                            "tags": ["Discovery", "Roadmap", "Analytics"],
                        },
                        ai_scores={"overall": 73},
                        ai_reasoning="Rejected after communication.",
                        cooldown_until=_utcnow() + timedelta(days=18),
                        last_contacted_at=_utcnow() - timedelta(days=1),
                    ),
                    Workflow(
                        name="Discovery to Screening",
                        jd_id="Frontend Platform Engineer",
                        status="active",
                        version=3,
                        config={"start_node_id": "discover_candidate", "nodes": screening_nodes},
                    ),
                    Workflow(
                        name="Talent Pool Handoff",
                        jd_id="Platform Engineer",
                        status="draft",
                        version=1,
                        config={
                            "start_node_id": "screen",
                            "nodes": [
                                {
                                    "id": "screen",
                                    "name": "Screen",
                                    "task_type": "initial_screening",
                                    "kind": "screen",
                                    "status": "approved",
                                    "owner": "Agent",
                                    "description": "Score against criteria.",
                                    "transitions": [{"condition": "default", "target": "talent_pool_upload"}],
                                },
                                {
                                    "id": "talent_pool_upload",
                                    "name": "Upload to talent pool",
                                    "task_type": "talent_pool_upload",
                                    "kind": "review",
                                    "status": "idle",
                                    "owner": "Human",
                                    "description": "Push qualified candidates to the internal system.",
                                },
                            ]
                        },
                    ),
                    Skill(
                        skill_id="site_scene_outreach_drafting",
                        name="Recruiting Scene Outreach Drafting",
                        version=1,
                        status="active",
                        bound_to_workflow_node="initiate_communication",
                        platform="Recruiting scene",
                        strategy={"summary": "Produces short, respectful outreach with role-specific context."},
                        last_health_status="healthy",
                        last_health_check=_utcnow(),
                    ),
                    Skill(
                        skill_id="resume_screening",
                        name="Resume Screening",
                        version=1,
                        status="pending_review",
                        bound_to_workflow_node="initial_screening",
                        platform="Recruiting scene",
                        strategy={"summary": "Drafted from recent candidate examples and pending approval."},
                        last_health_status="warning",
                        last_health_check=_utcnow(),
                    ),
                    ApprovalItem(
                        target_type="skill",
                        target_id="resume_screening",
                        title="Approve resume screening Skill",
                        status="pending",
                        requested_by="agent",
                        payload={"summary": "Review the new initial screening strategy before activation."},
                    ),
                    ApprovalItem(
                        target_type="workflow",
                        target_id="workflow_change_001",
                        title="Activate talent pool handoff",
                        status="pending",
                        requested_by="ops",
                        payload={"summary": "Enables the workflow path from scoring to human review."},
                    ),
                ]
            )
            session.commit()
