import type {
  ApprovalItem,
  AgentQueueItem,
  AgentSnapshot,
  CandidateRecord,
  DashboardSummary,
  DomainPackRecord,
  RuntimeCapabilityDriver,
  RuntimeCompilerContract,
  RuntimeEnvironmentAssessment,
  RuntimeExecutionPlan,
  RuntimeEpisode,
  RuntimeEpisodeReplay,
  RuntimePatch,
  RuntimePlanReplanResult,
  RuntimeSnapshot,
  RuntimeTaskSpec,
  RuntimeTemplate,
  RuntimeWorkspaceData,
  SettingsSnapshot,
  SkillRecord,
  SyncBacklogItem,
  SyncStatusSnapshot,
  TimelineEvent,
  WorkflowDefinition,
} from "./types";

const now = new Date();
const iso = (offsetMinutes: number): string => new Date(now.getTime() + offsetMinutes * 60_000).toISOString();

const candidates: CandidateRecord[] = [
  {
    id: "cand-001",
    name: "Mia Chen",
    title: "Senior Frontend Engineer",
    platform: "招聘工作流",
    location: "Shanghai",
    status: "screening",
    workflowNode: "initial_screening",
    jdTitle: "Frontend Platform Engineer",
    matchScore: 92,
    experienceYears: 8,
    nextAction: "确认系统设计深度和 React 性能案例是否足够扎实。",
    summary: "产品感觉好、owner 意识清晰，UI 细节和工程深度比较平衡。",
    tags: ["React", "Design Systems", "Performance"],
    resumeAvailable: true,
    lastContactedAt: iso(-120),
  },
  {
    id: "cand-002",
    name: "Jason Li",
    title: "Backend Engineer",
    platform: "招聘工作流",
    location: "Hangzhou",
    status: "pending_communication",
    workflowNode: "initiate_communication",
    jdTitle: "Platform Engineer",
    matchScore: 84,
    experienceYears: 6,
    nextAction: "发送外联消息，并说明薪资范围和团队职责范围。",
    summary: "服务设计经验可靠，对后端运行和交付有较强 owner 意识。",
    tags: ["Go", "PostgreSQL", "APIs"],
    resumeAvailable: false,
  },
  {
    id: "cand-003",
    name: "Luna Wang",
    title: "Product Manager",
    platform: "招聘工作流",
    location: "Beijing",
    status: "cooldown",
    workflowNode: "cooldown",
    jdTitle: "Product Lead",
    matchScore: 73,
    experienceYears: 7,
    nextAction: "尊重冷却期，等下一个联系窗口再评估是否继续。",
    summary: "沟通后已拒绝，先保留在暂停池中，避免重复外联。",
    tags: ["Discovery", "Roadmap", "Analytics"],
    resumeAvailable: true,
    cooldownUntil: iso(60 * 24 * 18),
    lastContactedAt: iso(-1440),
  },
];

const workflows: WorkflowDefinition[] = [
  {
    id: "wf-screening",
    name: "发现到初筛",
    jdTitle: "Frontend Platform Engineer",
    status: "active",
    version: "v1.3",
    updatedAt: iso(-180),
    nodes: [
      { id: "discover", name: "发现候选人", kind: "discover", status: "approved", owner: "Scheduler", description: "搜索并接入候选人档案。" },
      { id: "initial_screening", name: "初筛", kind: "screen", status: "running", owner: "Agent", description: "阅读简历并按 JD 要求做判断。" },
      { id: "initiate_communication", name: "发起沟通", kind: "communicate", status: "idle", owner: "Agent", description: "使用批准后的消息模板发起外联。" },
      { id: "request_resume", name: "获取简历", kind: "resume", status: "idle", owner: "Agent", description: "收集结构化简历材料。" },
      { id: "candidate_scoring", name: "候选人评分", kind: "score", status: "idle", owner: "Agent", description: "生成评分和判断依据。" },
      { id: "hr_review", name: "HR 审查", kind: "review", status: "blocked", owner: "Human", description: "在同步人才库前等待人工批准。" },
    ],
  },
  {
    id: "wf-talent-pool",
    name: "人才库交接",
    jdTitle: "Platform Engineer",
    status: "draft",
    version: "v0.8",
    updatedAt: iso(-75),
    nodes: [
      { id: "screen", name: "初筛评分", kind: "screen", status: "approved", owner: "Agent", description: "按标准完成评分。" },
      { id: "talent_pool_upload", name: "上传人才库", kind: "review", status: "idle", owner: "Human", description: "把合格候选人推送到内部系统。" },
    ],
  },
];

const skills: SkillRecord[] = [
  {
    id: "skill-001",
    name: "招聘外联撰写",
    version: "1.2.0",
    status: "active",
    boundNode: "initiate_communication",
    platform: "招聘工作流",
    health: "healthy",
    lastCheckedAt: iso(-30),
    summary: "生成简短、克制、带岗位上下文的外联内容。",
  },
  {
    id: "skill-002",
    name: "Resume Screening",
    version: "1.0.4",
    status: "pending_review",
    boundNode: "initial_screening",
    platform: "招聘工作流",
    health: "warning",
    lastCheckedAt: iso(-90),
    summary: "由近期候选人案例沉淀而来，当前等待批准。",
  },
  {
    id: "skill-003",
    name: "人才库交接打包",
    version: "0.9.1",
    status: "degraded",
    boundNode: "candidate_scoring",
    platform: "招聘工作流",
    health: "critical",
    lastCheckedAt: iso(-240),
    summary: "最近一次浏览器运行中检测到选择器漂移。",
  },
];

const approvals: ApprovalItem[] = [
  {
    id: "apr-001",
    kind: "skill",
    title: "批准 resume screening Skill",
    detail: "在启用前先审查新的初筛策略。",
    requester: "Agent",
    status: "pending",
    createdAt: iso(-45),
  },
  {
    id: "apr-002",
    kind: "workflow",
    title: "激活人才库交接",
    detail: "启用从评分到人工审查的工作流路径。",
    requester: "Ops",
    status: "pending",
    createdAt: iso(-65),
  },
  {
    id: "apr-003",
    kind: "system_command",
    title: "允许本地包检查命令",
    detail: "在白名单控制下注册一个安全命令。",
    requester: "Agent",
    status: "rejected",
    createdAt: iso(-180),
  },
];

const agent: AgentSnapshot = {
  status: "running",
  activeTask: "正在为 Mia Chen 执行初筛",
  browserLock: "held",
  uptime: "03:12:41",
  queueDepth: 4,
  tokenBudgetUsed: 38,
  health: "warning",
};

const events: TimelineEvent[] = [
  {
    id: "evt-001",
    label: "工作流节点已推进",
    detail: "已将 Mia Chen 推进到初筛步骤。",
    at: iso(-12),
    tone: "positive",
  },
  {
    id: "evt-002",
    label: "审批待处理",
    detail: "resume screening Skill 正在等待审查。",
    at: iso(-32),
    tone: "warning",
  },
  {
    id: "evt-003",
    label: "已应用冷却期",
    detail: "Luna Wang 已被标记为避免重复外联。",
    at: iso(-48),
    tone: "neutral",
  },
];

const alerts: TimelineEvent[] = [
  {
    id: "alert-001",
    label: "检测到选择器漂移",
    detail: "人才库交接打包在恢复完全自动化前需要先刷新。",
    at: iso(-22),
    tone: "critical",
  },
];

const settings: SettingsSnapshot = {
  locale: "en-US",
  timezone: "Asia/Shanghai",
  intranetEnabled: false,
  desktopApprovalsOnly: true,
  skillHealthAutonomyEnabled: false,
  skillHealthAutonomyIntervalSeconds: 300,
  providers: [
    { kind: "openai-compatible", name: "Primary OpenAI API", model: "gpt-5.4", enabled: true, temperature: 0.2, baseUrl: "https://api.openai.com/v1" },
    { kind: "anthropic", name: "Fallback Anthropic", model: "claude-sonnet-4", enabled: false, temperature: 0.2, baseUrl: "https://api.anthropic.com" },
  ],
  platform: {
    name: "Recruiting scene profile",
    account: "本机场景 01",
    cooldownDays: 18,
    allowOutboundMessaging: false,
  },
};

const metrics = [
  { label: "Candidates screened", value: "126", delta: "+14%", tone: "positive" as const, caption: "Past 7 days" },
  { label: "Reply rate", value: "41%", delta: "+6%", tone: "positive" as const, caption: "Outreach to response" },
  { label: "Budget used", value: "$182", delta: "-9%", tone: "neutral" as const, caption: "Token spend this week" },
  { label: "Manual approvals", value: "3", delta: "1 pending", tone: "warning" as const, caption: "Human gate queue" },
];

const pipeline = [
  { label: "Discovery", value: 18, target: 20 },
  { label: "Screening", value: 12, target: 16 },
  { label: "Communication", value: 7, target: 10 },
  { label: "Scoring", value: 4, target: 6 },
  { label: "Human review", value: 3, target: 4 },
];

export const desktopMockSnapshot: DashboardSummary = {
  metrics,
  pipeline,
  timeline: events,
  alerts,
  candidates,
  workflows,
  skills,
  approvals,
  agent,
  settings,
};

const runtimeTasks: RuntimeTaskSpec[] = [
  {
    id: "task-001",
    title: "调研 PDF 转换工具",
    description: "由自然语言需求生成的网页研究工作流草稿。",
    goal: "找出好用的 PDF 转换工具，完成对比并产出候选清单。",
    domain: "web_research",
    status: "trial_ready",
    sourceKind: "natural_language",
    sourceText: "去网上找好用的 PDF 转换工具，做对比并整理成候选清单。",
    inputs: {},
    constraints: { requires_human_supervision: true },
    successCriteria: { minimum_candidates: 3, include_comparison: true },
    approvalPolicy: { mode: "desktop_review", trial_required: true },
    outputContract: { kind: "research_shortlist", format: "table" },
    preferredCapabilities: ["search", "browser", "http", "llm", "document"],
    preferredDomains: ["web_research"],
    compiledPayload: {
      domain_pack: "web_research",
      compiler_source: "llm",
      compiler_quality: {
        quality_status: "accepted",
        quality_score: 0.94,
        repair_count: 0,
        missing_required_fields: [],
        warnings: [],
      },
      requires_trial: true,
      trial_expectations: { minimum_candidates: 3, requires_scene_assessment_for_browser: true },
    },
    activePlanId: "plan-001",
    createdAt: iso(-200),
    updatedAt: iso(-120),
  },
  {
    id: "task-002",
    title: "GitHub 今日热点项目",
    description: "由自然语言需求生成的 GitHub 热点工作流草稿。",
    goal: "找出今天最热的 GitHub 项目，并附带仓库链接和简介进行汇总。",
    domain: "github_trends",
    status: "compiled",
    sourceKind: "natural_language",
    sourceText: "GitHub 上今天的热点项目是哪些，找到仓库地址和项目简介发给我。",
    inputs: {},
    constraints: { requires_source_links: true },
    successCriteria: { minimum_repositories: 5, include_repo_links: true },
    approvalPolicy: { mode: "desktop_review", trial_required: true },
    outputContract: { kind: "repository_digest", format: "table" },
    preferredCapabilities: ["http", "browser", "llm", "document"],
    preferredDomains: ["github_trends"],
    compiledPayload: {
      domain_pack: "github_trends",
      compiler_source: "llm",
      compiler_quality: {
        quality_status: "accepted",
        quality_score: 0.9,
        repair_count: 0,
        missing_required_fields: [],
        warnings: [],
      },
      requires_trial: true,
      trial_expectations: { minimum_repositories: 5, requires_scene_assessment_for_browser: true },
    },
    activePlanId: "plan-002",
    createdAt: iso(-90),
    updatedAt: iso(-60),
  },
];

const runtimePlans: RuntimeExecutionPlan[] = [
  {
    id: "plan-001",
    taskSpecId: "task-001",
    name: "PDF 转换工具试跑计划",
    mode: "trial",
    status: "validated",
    version: 2,
    approvalState: "template_candidate",
    planBody: {
      steps: [
        { id: "understand_task", capability: "analyze" },
        { id: "search_1", capability: "search" },
        { id: "browser_2", capability: "browser" },
        { id: "http_3", capability: "http" },
        { id: "summarize_result", capability: "document" },
      ],
      instruction: "找出好用的 PDF 转换工具并整理候选清单。",
      domain: "web_research",
    },
    environmentRequirements: { requires_browser: true, requires_network: true },
    checkpoints: [{ kind: "approval", label: "复用前先审查候选清单" }],
    runtimeMetadata: { compiler: "llm", domain_pack: "web_research" },
    compiledFromPatchId: undefined,
    createdAt: iso(-200),
    updatedAt: iso(-30),
  },
  {
    id: "plan-002",
    taskSpecId: "task-002",
    name: "GitHub 热点项目试跑计划",
    mode: "trial",
    status: "diverged",
    version: 1,
    approvalState: "pending_review",
    planBody: {
      steps: [
        { id: "collect_trending_repos", capability: "http" },
        { id: "inspect_repository_pages", capability: "browser" },
        { id: "summarize_repositories", capability: "llm" },
      ],
      instruction: "找出 GitHub 热点仓库并完成摘要。",
      domain: "github_trends",
    },
    environmentRequirements: { requires_browser: true, requires_network: true },
    checkpoints: [{ kind: "approval", label: "审查偏差与修订建议" }],
    runtimeMetadata: { compiler: "llm", domain_pack: "github_trends" },
    compiledFromPatchId: undefined,
    createdAt: iso(-90),
    updatedAt: iso(-18),
  },
];

const runtimeEpisodes: RuntimeEpisode[] = [
  {
    id: "episode-001",
    taskSpecId: "task-001",
    executionPlanId: "plan-001",
    mode: "trial",
    status: "awaiting_review",
    requestedBy: "desktop-user",
    requiresConfirmation: true,
    startedAt: iso(-70),
    finishedAt: iso(-65),
    resultSummary: "试跑已完成网页探索，并产出面向候选清单的调研摘要。",
    observations: [{ step_id: "browser_2", kind: "observation", summary: "已检查首批工具卡片和核心信息。" }],
    actions: [{ step_id: "search_1", capability: "search", status: "completed" }],
    metrics: { step_count: 5, completion_rate: 1 },
    divergenceDetected: false,
    patchId: undefined,
    runtimeMetadata: { operator: "desktop-user" },
    createdAt: iso(-70),
    updatedAt: iso(-65),
  },
  {
    id: "episode-002",
    taskSpecId: "task-002",
    executionPlanId: "plan-002",
    mode: "trial",
    status: "diverged",
    requestedBy: "desktop-user",
    requiresConfirmation: true,
    startedAt: iso(-24),
    finishedAt: iso(-18),
    resultSummary: "试跑已采集热点仓库，但环境漂移提示需要更新检查点。",
    observations: [{ step_id: "inspect_repository_pages", kind: "observation", summary: "热点列表布局发生漂移。" }],
    actions: [{ step_id: "collect_trending_repos", capability: "http", status: "completed" }],
    metrics: { step_count: 3, completion_rate: 1 },
    divergenceDetected: true,
    patchId: "patch-001",
    runtimeMetadata: { operator: "desktop-user" },
    createdAt: iso(-24),
    updatedAt: iso(-18),
  },
];

const runtimeSnapshots: RuntimeSnapshot[] = [
  {
    id: "snapshot-001",
    taskSpecId: "task-001",
    executionPlanId: "plan-001",
    executionEpisodeId: "episode-001",
    source: "browser",
    environmentKey: "web_research:browser",
    status: "captured",
    url: "https://example.com/pdf-tools",
    title: "PDF 工具对比页",
    pageType: "tool_listing",
    capabilityHints: ["search", "browser"],
    observedEntities: [{ kind: "tool_card", label: "Converter A" }],
    affordances: [{ kind: "open_tool", label: "Open tool page" }],
    runtimeMetadata: { plan_name: "PDF 转换工具试跑计划" },
    createdAt: iso(-66),
    updatedAt: iso(-66),
  },
  {
    id: "snapshot-002",
    taskSpecId: "task-002",
    executionPlanId: "plan-002",
    executionEpisodeId: "episode-002",
    source: "browser",
    environmentKey: "github_trends:browser",
    status: "captured",
    url: "https://github.com/trending",
    title: "GitHub 热门仓库页",
    pageType: "repository_listing",
    capabilityHints: ["http", "browser"],
    observedEntities: [{ kind: "repository_card", label: "example/repo" }],
    affordances: [{ kind: "open_repository", label: "Open repository page" }],
    runtimeMetadata: { plan_name: "GitHub 热点项目试跑计划" },
    createdAt: iso(-18),
    updatedAt: iso(-18),
  },
];

const runtimeCapabilityDrivers: RuntimeCapabilityDriver[] = [
  {
    id: "driver-001",
    key: "browser.navigator",
    name: "浏览器导航器",
    category: "browser",
    status: "ready",
    scope: "在网页场景中完成导航、观察 DOM 状态，并记录受监督操作。",
    description: "当系统需要直接观察页面、点击目标或保留场景截图时，优先使用这个驱动。",
    safetyMode: "supervised_write",
    supportsWrite: true,
    sceneTypes: ["candidate_listing", "repository_listing", "tool_listing", "detail_page"],
    signalLabels: ["dom_affordances", "scene_classifier", "selector_confidence"],
    updatedAt: iso(-15),
  },
  {
    id: "driver-002",
    key: "search.discovery",
    name: "搜索发现器",
    category: "search",
    status: "ready",
    scope: "检索公开网络，并把排序后的候选结果送入试跑计划。",
    description: "适用于需要先广泛搜索、再进入浏览器或 HTTP 观察的探索型任务。",
    safetyMode: "read_only",
    supportsWrite: false,
    sceneTypes: ["search_results", "research_seed"],
    signalLabels: ["ranking_score", "source_diversity", "query_rewrite"],
    updatedAt: iso(-22),
  },
  {
    id: "driver-003",
    key: "http.harvest",
    name: "HTTP 采集器",
    category: "http",
    status: "degraded",
    scope: "优先抓取结构化页面或 API，再决定是否升级到浏览器观察。",
    description: "适合可通过轻量请求解决的场景，但当前仍有部分结构漂移需要关注。",
    safetyMode: "read_only",
    supportsWrite: false,
    sceneTypes: ["repository_listing", "news_feed", "api_resource"],
    signalLabels: ["schema_match", "response_latency", "rate_limit"],
    updatedAt: iso(-18),
  },
  {
    id: "driver-004",
    key: "document.summarizer",
    name: "文档整理器",
    category: "document",
    status: "ready",
    scope: "把采集到的证据整理成面向操作员的输出和回放材料。",
    description: "把浏览器和 HTTP 证据转成摘要、评分卡和可审批的总结。",
    safetyMode: "local_only",
    supportsWrite: true,
    sceneTypes: ["summary", "scorecard", "handoff_bundle"],
    signalLabels: ["output_contract", "coverage_score", "citation_density"],
    updatedAt: iso(-11),
  },
];

const runtimeEnvironmentAssessments: RuntimeEnvironmentAssessment[] = [
  {
    id: "assessment-001",
    taskSpecId: "task-001",
    executionPlanId: "plan-001",
    executionEpisodeId: "episode-001",
    snapshotId: "snapshot-001",
    environmentKey: "web_research:browser",
    sceneLabel: "PDF 转换工具对比列表",
    sceneType: "tool_listing",
    status: "aligned",
    confidence: 0.94,
    summary: "当前观察到的工具卡片和对比动作，仍与现有受监督调研计划保持一致。",
    observedEntities: [
      {
        kind: "tool_card",
        label: "PDF 转换工具卡片",
        entityId: "tool-card-1",
        role: "result",
        confidence: 0.94,
        state: "visible",
        interactive: true,
        signals: ["listing_surface"],
        locator: { selector: "[data-tool-card]" },
        attributes: { count: 8 },
      },
    ],
    affordances: [
      {
        kind: "link",
        label: "打开工具详情",
        action: "navigate",
        target: "detail_page",
        confidence: 0.9,
        enabled: true,
        requiresConfirmation: false,
        signals: ["navigation_target"],
        locator: { selector: "a[data-open-tool]" },
        metadata: {},
      },
    ],
    sceneProfile: {
      source: "browser",
      sceneType: "tool_listing",
      interactionMode: "navigate",
      volatility: "low",
      authState: "clear",
      entityCount: 3,
      affordanceCount: 3,
      primaryTargets: ["PDF 转换工具卡片"],
      signals: ["listing_surface", "well_observed_scene"],
      blockers: [],
      evidence: { observed_entity_kinds: ["tool_card", "pricing_badge", "feature_table"] },
    },
    plannerGuidance: {
      posture: "verify",
      requiredCapabilities: ["search.discovery", "browser.navigator", "document.summarizer"],
      insertedCapabilities: ["browser.navigator"],
      preferredNextActions: ["在记录详细工具信息前，先确认当前列表布局。"],
      requiresSceneAssessment: true,
      requiresHumanReview: false,
      shouldCheckpoint: true,
      rationale: ["当前场景整体健康，但在正式抽取前仍应确认对比布局。"],
    },
    capabilityKeys: ["search.discovery", "browser.navigator", "document.summarizer"],
    observedLabels: ["tool_card", "pricing_badge", "feature_table"],
    affordanceLabels: ["open_tool", "compare_features", "capture_notes"],
    driftSignals: [],
    recommendedActions: ["保持现有试跑模板继续可用。", "如果候选清单结果依旧可靠，可在确认后提升为正式版本。"],
    updatedAt: iso(-14),
  },
  {
    id: "assessment-002",
    taskSpecId: "task-002",
    executionPlanId: "plan-002",
    executionEpisodeId: "episode-002",
    snapshotId: "snapshot-002",
    environmentKey: "github_trends:browser",
    sceneLabel: "GitHub 热门仓库列表",
    sceneType: "repository_listing",
    status: "drift_detected",
    confidence: 0.72,
    summary: "当前列表仍可识别，但仓库卡片把关键元信息收进了额外交互层里。",
    observedEntities: [
      {
        kind: "repository_card",
        label: "仓库卡片",
        entityId: "repo-card-1",
        role: "result",
        confidence: 0.83,
        state: "partial",
        interactive: true,
        signals: ["listing_surface", "detail_surface"],
        locator: { selector: "[data-repo-card]" },
        attributes: { expanded: false },
      },
    ],
    affordances: [
      {
        kind: "button",
        label: "展开详情",
        action: "click",
        target: "repository_metadata",
        confidence: 0.76,
        enabled: true,
        requiresConfirmation: false,
        signals: ["navigation_target"],
        locator: { selector: "button[data-expand]" },
        metadata: {},
      },
    ],
    sceneProfile: {
      source: "browser",
      sceneType: "repository_listing",
      interactionMode: "navigate",
      volatility: "medium",
      authState: "clear",
      entityCount: 3,
      affordanceCount: 3,
      primaryTargets: ["仓库卡片"],
      signals: ["listing_surface", "detail_surface"],
      blockers: ["scene_needs_reassessment"],
      evidence: { observed_entity_kinds: ["repository_card", "language_badge", "star_delta"] },
    },
    plannerGuidance: {
      posture: "recover",
      requiredCapabilities: ["http.harvest", "browser.navigator", "document.summarizer"],
      insertedCapabilities: ["browser.navigator"],
      preferredNextActions: [
        "在提取详情前，重新评估仓库列表布局。",
        "下一版重规划优先采用 HTTP 与浏览器混合提取。",
      ],
      requiresSceneAssessment: true,
      requiresHumanReview: true,
      shouldCheckpoint: true,
      rationale: ["场景漂移说明规划器应先做新的浏览器评估，再继续执行。"],
    },
    capabilityKeys: ["http.harvest", "browser.navigator", "document.summarizer"],
    observedLabels: ["repository_card", "language_badge", "star_delta"],
    affordanceLabels: ["open_repository", "expand_details", "capture_digest"],
    driftSignals: ["元信息被收进动态展开层。", "Star delta 被挪到了次级行。"],
    recommendedActions: ["在抓取仓库详情前插入场景评估检查点。", "下一版重规划优先采用 HTTP 与浏览器混合提取。"],
    updatedAt: iso(-10),
  },
];

const runtimeTemplates: RuntimeTemplate[] = [
  {
    id: "template-001",
    templateKey: "web_research_research_pdf_converters",
    name: "PDF 转换工具工作流版本",
    domain: "web_research",
    status: "draft",
    version: 1,
    sourceTaskSpecId: "task-001",
    templateBody: { steps: runtimePlans[0].planBody.steps, checkpoints: runtimePlans[0].checkpoints },
    activationStrategy: {
      mode: "supervised_trial_first",
      requires_confirmation: true,
      governance: {
        episode_quality_band: "high",
        domain_pack_version: "0.4.0",
        trial_expectations: { minimum_candidates: 3, requires_scene_assessment_for_browser: true },
      },
    },
    validationSummary: "已在受监督试跑中完成验证。",
    lastValidatedAt: iso(-65),
    createdAt: iso(-64),
    updatedAt: iso(-64),
  },
  {
    id: "template-002",
    templateKey: "github_trends_digest",
    name: "GitHub 热点摘要版本",
    domain: "github_trends",
    status: "active",
    version: 1,
    sourceTaskSpecId: undefined,
    templateBody: { steps: runtimePlans[1].planBody.steps },
    activationStrategy: {
      mode: "trial_first",
      governance: {
        episode_quality_band: "medium",
        domain_pack_version: "0.4.0",
        quality_gates: { minimum_repositories: 5, require_source_links: true },
      },
    },
    validationSummary: "用于 GitHub 热点监控的初始版本。",
    lastValidatedAt: iso(-320),
    createdAt: iso(-320),
    updatedAt: iso(-320),
  },
];

const runtimePatches: RuntimePatch[] = [
  {
    id: "patch-001",
    title: "修正 GitHub 热点项目工作流",
    patchKind: "execution_divergence",
    status: "pending_review",
    templateId: "template-002",
    taskSpecId: "task-002",
    executionPlanId: "plan-002",
    executionEpisodeId: "episode-002",
    proposedBy: "runtime",
    divergenceSummary: "在处理 repository_listing 时，试跑执行出现偏差。",
    rationale: "观测到的环境与当前执行计划不一致。",
    patchBody: { operations: [{ op: "review_checkpoint", target: "repository_listing" }] },
    runtimeMetadata: {
      generatedFromEpisode: "episode-002",
      domain_pack_version: "0.4.0",
      episode_quality_band: "medium",
      plan_version: 1,
    },
    createdAt: iso(-18),
    updatedAt: iso(-18),
  },
];

const runtimeReplans: RuntimePlanReplanResult[] = [
  {
    id: "replan-001",
    taskSpecId: "task-002",
    baseExecutionPlanId: "plan-002",
    executionPlan: {
      id: "plan-002-r2",
      taskSpecId: "task-002",
    name: "GitHub 热点项目重规划 v2",
      mode: "trial",
      status: "proposed",
      version: 2,
      approvalState: "pending_review",
      planBody: {
        steps: [
          { id: "collect_trending_repos", capability: "http" },
          { id: "assess_repository_scene", capability: "browser" },
          { id: "inspect_repository_pages", capability: "browser" },
          { id: "summarize_repositories", capability: "document" },
        ],
        instruction: "重新评估热点场景，再采集仓库上下文并完成摘要。",
        domain: "github_trends",
      },
      environmentRequirements: { requires_browser: true, requires_network: true, scene_assessment_required: true },
      checkpoints: [
        { kind: "scene_assessment", label: "提取前先确认仓库列表布局" },
        { kind: "approval", label: "复用前先审查更新后的摘要计划" },
      ],
      runtimeMetadata: { compiler: "runtime_replanner", trigger: "scene_drift" },
      compiledFromPatchId: "patch-001",
      createdAt: iso(-8),
      updatedAt: iso(-8),
    },
    status: "proposed",
    trigger: "scene_drift",
    summary: "已插入场景评估检查点，并把计划重心调整为先完成浏览器验证，再进行文档整理。",
    compilerNotes: [
      "仓库列表漂移主要集中在详情抓取这一段。",
      "输出约定保持不变，因此只调整了提取步骤和检查点顺序。",
    ],
    recommendedCapabilityKeys: ["browser.navigator", "http.harvest", "document.summarizer"],
    environmentAssessment: runtimeEnvironmentAssessments[1],
    patch: runtimePatches[0],
    createdAt: iso(-8),
  },
];

const domainPacks: DomainPackRecord[] = [
  {
    key: "general",
    name: "通用自动化",
    description: "适用于探索型网页或桌面任务的通用受监督场景画像。",
    version: "1.2.0",
    maturity: "beta",
    runtimeOnly: true,
    defaultCapabilities: ["analyze", "browser", "llm", "document"],
    sampleTasks: ["打开一个网站并完成摘要。", "在人工监督下试跑一条新工作流。"],
    defaultConstraints: { requires_human_supervision: true },
    defaultOutputContract: { kind: "summary", format: "markdown" },
    templateKeys: ["general_supervised_trial", "patch_review_loop"],
    compilerHints: ["优先要求明确目标、审批策略和输出约定，而不是依赖领域假设。"],
    qualityGates: { requires_goal: true, requires_output_contract: true, requires_approval_policy: true },
    sceneExpectations: ["当场景需要交互时，记录浏览器场景检查点。"],
    trialExpectations: { requires_supervised_trial: true, requires_scene_assessment_for_browser: true },
    templateCount: 2,
    activeTemplateCount: 1,
  },
  {
    key: "recruiting",
    name: "招聘",
    description: "寻找候选人、获取上下文、完成初筛，并准备经过批准的交接材料。",
    version: "1.1.0",
    maturity: "beta",
    runtimeOnly: true,
    defaultCapabilities: ["browser", "search", "document", "llm", "api"],
    sampleTasks: ["找到候选人并完成评分。", "获取简历并整理招聘备注。"],
    defaultConstraints: { requires_human_supervision: true, respect_messaging_approval: true },
    defaultOutputContract: { kind: "candidate_bundle" },
    templateKeys: ["recruiting_trial_screening"],
    compilerHints: ["把招聘网站视为运行时场景，并保留外联和上传动作的审批边界。"],
    qualityGates: { requires_candidate_criteria: true, requires_output_contract: true, enforce_write_approval: true },
    sceneExpectations: ["浏览器场景应确认列表页、详情页和简历获取检查点。"],
    trialExpectations: { requires_supervised_trial: true, requires_scene_assessment_for_browser: true },
    templateCount: 1,
    activeTemplateCount: 0,
  },
  {
    key: "market_news",
    name: "市场新闻",
    description: "采集最新市场新闻，并整理成简明摘要。",
    version: "0.4.0",
    maturity: "experimental",
    runtimeOnly: true,
    defaultCapabilities: ["search", "http", "browser", "llm", "document"],
    sampleTasks: ["查找最新股市新闻并完成摘要。"],
    defaultConstraints: { requires_source_links: true },
    defaultOutputContract: { kind: "news_digest" },
    templateKeys: ["market_news_digest"],
    compilerHints: ["优先选择最新来源，并保留明确的来源归属。"],
    qualityGates: { minimum_sources: 3, require_source_links: true, require_recency_window: true },
    sceneExpectations: ["在做摘要前，搜索和浏览器场景都应先确认发布时间可见。"],
    trialExpectations: { minimum_sources: 3, requires_scene_assessment_for_browser: true },
    templateCount: 1,
    activeTemplateCount: 0,
  },
  {
    key: "web_research",
    name: "网页研究",
    description: "在公开网络中搜索、比较并筛选工具或资源。",
    version: "0.4.0",
    maturity: "experimental",
    runtimeOnly: true,
    defaultCapabilities: ["search", "browser", "http", "llm", "document"],
    sampleTasks: ["找出好用的 PDF 转换工具并做对比。"],
    defaultConstraints: { requires_source_links: true },
    defaultOutputContract: { kind: "research_shortlist" },
    templateKeys: ["web_research_shortlist"],
    compilerHints: ["执行前要求明确候选清单标准和对比维度。"],
    qualityGates: { minimum_candidates: 3, require_comparison_axes: true, require_source_links: true },
    sceneExpectations: ["工具列表场景在抽取前应先记录对比证据检查点。"],
    trialExpectations: { minimum_candidates: 3, requires_scene_assessment_for_browser: true },
    templateCount: 1,
    activeTemplateCount: 0,
  },
  {
    key: "github_trends",
    name: "GitHub 热点",
    description: "追踪热门仓库，并总结它们为什么值得关注。",
    version: "0.4.0",
    maturity: "experimental",
    runtimeOnly: true,
    defaultCapabilities: ["http", "browser", "llm", "document"],
    sampleTasks: ["列出今天的 GitHub 热门仓库，并附上仓库链接。"],
    defaultConstraints: { requires_source_links: true },
    defaultOutputContract: { kind: "repository_digest" },
    templateKeys: ["github_trends_digest"],
    compilerHints: ["要求保留仓库链接、简明理由，并提供足够样本避免噪音。"],
    qualityGates: { minimum_repositories: 5, require_source_links: true, require_project_rationale: true },
    sceneExpectations: ["仓库列表场景在抓取详情前应先确认卡片布局。"],
    trialExpectations: { minimum_repositories: 5, requires_scene_assessment_for_browser: true },
    templateCount: 1,
    activeTemplateCount: 1,
  },
];

const runtimeCompilerContract: RuntimeCompilerContract = {
  contractVersion: "runtime-task-compiler-v4",
  strategy: "llm_first_structured_semantic_compiler",
  fallbackStrategy: "none",
  promptAsset: "tasks/runtime_task_compiler.md",
  requiredFields: ["goal", "domain", "constraints", "success_criteria", "approval_policy", "output_contract"],
  optionalFields: ["inputs", "preferred_capabilities", "preferred_domains", "environment_requirements", "checkpoints", "step_outline", "compiler_notes"],
  invariants: [
    "开发阶段不预设任何固定网站接入。",
    "编译器必须先生成结构化任务契约，再进入执行。",
    "当 LLM 编译失败时，应显式报错，而不是静默降级。",
  ],
  qualityGates: [
    "目标、审批策略、成功标准和输出约定都必须具体。",
    "浏览器类工作流必须生成场景检查点和环境要求。",
    "写入、同步、上传或本地命令动作必须保持审批感知。",
  ],
  repairPolicy: {
    maxAttempts: 1,
    fallback: "none",
    escalateToHumanOnCriticalGaps: true,
  },
  availableDomains: domainPacks,
  availableCapabilities: runtimeCapabilityDrivers,
};

export const desktopRuntimeMock: RuntimeWorkspaceData = {
  compilerContract: runtimeCompilerContract,
  domainPacks,
  taskSpecs: runtimeTasks,
  plans: runtimePlans,
  episodes: runtimeEpisodes,
  snapshots: runtimeSnapshots,
  capabilityDrivers: runtimeCapabilityDrivers,
  environmentAssessments: runtimeEnvironmentAssessments,
  templates: runtimeTemplates,
  patches: runtimePatches,
  replans: runtimeReplans,
};

export const desktopSyncBacklogMock: SyncBacklogItem[] = [
  {
    id: "sync-001",
    target: "intranet:candidate_bundle",
    entityType: "candidate_bundle",
    entityId: "cand-001",
    status: "pending",
    attemptCount: 2,
    protocolVersion: "2026-04-14",
    deliveryMode: "local_first",
    lastAttemptedAt: iso(-42),
    nextAttemptAt: iso(25),
    payloadSummary: "Candidate bundle for Mia Chen is waiting for intranet availability.",
    lastError: "Intranet endpoint unavailable during the last replay attempt.",
    payload: {
      protocol_version: "2026-04-14",
      target: { kind: "intranet", base_url: "https://intranet.local", api_path: "/sync/runtime" },
    },
    targetMetadata: { kind: "intranet", api_path: "/sync/runtime" },
    updatedAt: iso(-42),
  },
  {
    id: "sync-002",
    target: "intranet:runtime_template",
    entityType: "runtime_template",
    entityId: "template-001",
    status: "pending",
    attemptCount: 1,
    protocolVersion: "2026-04-14",
    deliveryMode: "local_first",
    lastAttemptedAt: iso(-18),
    payloadSummary: "Validated PDF converter template is queued for sync.",
    payload: {
      protocol_version: "2026-04-14",
      target: { kind: "intranet", base_url: "https://intranet.local", api_path: "/sync/runtime" },
    },
    targetMetadata: { kind: "intranet", api_path: "/sync/runtime" },
    updatedAt: iso(-18),
  },
];

export const desktopSyncStatusMock: SyncStatusSnapshot = {
  enabled: false,
  mode: "local_only",
  remoteAvailable: false,
  protocolVersion: "2026-04-14",
  source: "desktop_app",
  target: { kind: "intranet", api_path: "/sync/runtime" },
  pendingCount: desktopSyncBacklogMock.length,
  syncedCount: 1,
  failedDeliveryCount: 1,
  deferredCount: 1,
  backlogTotal: 3,
  lastAttemptAt: iso(-18),
  lastSuccessAt: iso(-320),
  latestError: "Intranet sync is disabled, so backlog remains local.",
  nextAttemptAt: iso(25),
  byStatus: { pending: 2, synced: 1 },
  recentErrors: ["Intranet sync is disabled, so backlog is retained locally."],
};

export const desktopAgentQueueMock: AgentQueueItem[] = [
  {
    taskId: "task-queue-001",
    taskType: "initial_screening",
    priority: 180,
    status: "pending",
    attempts: 1,
    candidateId: "cand-001",
    workflowNodeId: "initial_screening",
    payload: { candidate_id: "cand-001", workflow_node_id: "initial_screening" },
    queueAudit: [
      { kind: "enqueued", at: iso(-26), status: "pending", priority: 180 },
      { kind: "returned_to_queue", at: iso(-18), attempts: 1, error: "scene drift detected during supervised retry" },
    ],
    createdAt: iso(-30),
    updatedAt: iso(-18),
  },
  {
    taskId: "task-queue-002",
    taskType: "request_resume",
    priority: 300,
    status: "completed",
    attempts: 0,
    candidateId: "cand-001",
    workflowNodeId: "resume_capture",
    payload: { candidate_id: "cand-001", workflow_node_id: "resume_capture" },
    queueAudit: [
      { kind: "enqueued", at: iso(-90), status: "pending", priority: 300 },
      { kind: "claimed", at: iso(-84), attempts: 0, lockedBy: "scheduler" },
      { kind: "completed", at: iso(-82), attempts: 0 },
    ],
    createdAt: iso(-90),
    updatedAt: iso(-82),
  },
];

export const desktopReplayMockByEpisode: Record<string, RuntimeEpisodeReplay> = {
  "episode-001": {
    episode: runtimeEpisodes[0],
    taskSpec: runtimeTasks[0],
    executionPlan: runtimePlans[0],
    snapshots: [runtimeSnapshots[0]],
    patch: null,
    template: runtimeTemplates[0],
    approval: {
      id: "approval-episode-001",
      targetType: "workflow_template",
      targetId: "template-001",
      title: "激活 PDF 转换工具工作流版本",
      status: "pending",
      requestedBy: "runtime",
    },
    diagnostics: [
      {
        id: "diag-001",
        label: "编译器已生成受监督试跑计划",
        detail: "系统选择了网页研究场景画像，并要求在提升复用前先做人审。",
        at: iso(-72),
        tone: "positive",
      },
      {
        id: "diag-002",
        label: "浏览器探索已完成",
        detail: "这个工作流实例已经抓取工具列表页，并在未发生漂移的情况下提取出候选清单条目。",
        at: iso(-66),
        tone: "positive",
      },
      {
        id: "diag-003",
        label: "回放已可确认",
        detail: "已经产出可复用的工作流版本草稿，等待桌面端确认。",
        at: iso(-64),
        tone: "warning",
      },
    ],
    notes: [
      "这次回放保持在预期的环境模型内。",
      "系统已为新版本生成一条仅本地保留的同步 backlog 记录。",
    ],
  },
  "episode-002": {
    episode: runtimeEpisodes[1],
    taskSpec: runtimeTasks[1],
    executionPlan: runtimePlans[1],
    snapshots: [runtimeSnapshots[1]],
    patch: runtimePatches[0],
    template: runtimeTemplates[1],
    approval: {
      id: "approval-episode-002",
      targetType: "workflow_patch",
      targetId: "patch-001",
      title: "审查 GitHub 热点工作流修订建议",
      status: "pending",
      requestedBy: "runtime",
    },
    diagnostics: [
      {
        id: "diag-004",
        label: "HTTP 步骤已成功",
        detail: "热点仓库的元信息已顺利采集。",
        at: iso(-23),
        tone: "positive",
      },
      {
        id: "diag-005",
        label: "检测到仓库列表漂移",
        detail: "系统观测到页面结构变化，并提出了新的检查点修订建议。",
        at: iso(-19),
        tone: "critical",
      },
      {
        id: "diag-006",
        label: "修订建议等待桌面审查",
        detail: "在操作员确认修订计划之前，这条修订建议会继续保留在队列里。",
        at: iso(-18),
        tone: "warning",
      },
    ],
    notes: [
      "在再次复用这个版本前，应先刷新环境启发式。",
      "这次回放表明当前生产版本在人工监督下仍可继续使用。",
    ],
  },
};
