import type {
  ApprovalItem,
  AgentSnapshot,
  CandidateRecord,
  DashboardSummary,
  DomainPackRecord,
  RuntimeExecutionPlan,
  RuntimeEpisode,
  RuntimePatch,
  RuntimeSnapshot,
  RuntimeTaskSpec,
  RuntimeTemplate,
  RuntimeWorkspaceData,
  SettingsSnapshot,
  SkillRecord,
  TimelineEvent,
  WorkflowDefinition,
} from "./types";

const now = new Date();
const iso = (offsetMinutes: number): string => new Date(now.getTime() + offsetMinutes * 60_000).toISOString();

const candidates: CandidateRecord[] = [
  {
    id: "cand-001",
    name: "Mia Chen",
    title: "Senior Frontend Engineer",
    platform: "Boss直聘",
    location: "Shanghai",
    status: "screening",
    workflowNode: "initial_screening",
    jdTitle: "Frontend Platform Engineer",
    matchScore: 92,
    experienceYears: 8,
    nextAction: "Verify system design depth and React performance examples.",
    summary: "Strong product sense, clear ownership, and good balance of UI craft and engineering depth.",
    tags: ["React", "Design Systems", "Performance"],
    resumeAvailable: true,
    lastContactedAt: iso(-120),
  },
  {
    id: "cand-002",
    name: "Jason Li",
    title: "Backend Engineer",
    platform: "Boss直聘",
    location: "Hangzhou",
    status: "pending_communication",
    workflowNode: "initiate_communication",
    jdTitle: "Platform Engineer",
    matchScore: 84,
    experienceYears: 6,
    nextAction: "Send outreach message with salary range and team scope.",
    summary: "Reliable service design experience with strong ownership in backend operations.",
    tags: ["Go", "PostgreSQL", "APIs"],
    resumeAvailable: false,
  },
  {
    id: "cand-003",
    name: "Luna Wang",
    title: "Product Manager",
    platform: "Boss直聘",
    location: "Beijing",
    status: "cooldown",
    workflowNode: "cooldown",
    jdTitle: "Product Lead",
    matchScore: 73,
    experienceYears: 7,
    nextAction: "Respect cooldown until the next contact window opens.",
    summary: "Rejected after communication. Store on hold and avoid repeated outreach.",
    tags: ["Discovery", "Roadmap", "Analytics"],
    resumeAvailable: true,
    cooldownUntil: iso(60 * 24 * 18),
    lastContactedAt: iso(-1440),
  },
];

const workflows: WorkflowDefinition[] = [
  {
    id: "wf-screening",
    name: "Discovery to Screening",
    jdTitle: "Frontend Platform Engineer",
    status: "active",
    version: "v1.3",
    updatedAt: iso(-180),
    nodes: [
      { id: "discover", name: "Discover candidates", kind: "discover", status: "approved", owner: "Scheduler", description: "Search and ingest candidate profiles." },
      { id: "initial_screening", name: "Initial screening", kind: "screen", status: "running", owner: "Agent", description: "Read resumes and evaluate against JD criteria." },
      { id: "initiate_communication", name: "Initiate communication", kind: "communicate", status: "idle", owner: "Agent", description: "Send outreach using approved message templates." },
      { id: "request_resume", name: "Request resume", kind: "resume", status: "idle", owner: "Agent", description: "Collect structured resume artifacts." },
      { id: "candidate_scoring", name: "Candidate scoring", kind: "score", status: "idle", owner: "Agent", description: "Produce scoring and reasoning payloads." },
      { id: "hr_review", name: "HR review", kind: "review", status: "blocked", owner: "Human", description: "Await approval before talent pool sync." },
    ],
  },
  {
    id: "wf-talent-pool",
    name: "Talent Pool Handoff",
    jdTitle: "Platform Engineer",
    status: "draft",
    version: "v0.8",
    updatedAt: iso(-75),
    nodes: [
      { id: "screen", name: "Screen", kind: "screen", status: "approved", owner: "Agent", description: "Score against criteria." },
      { id: "talent_pool_upload", name: "Upload to talent pool", kind: "review", status: "idle", owner: "Human", description: "Push qualified candidates to the internal system." },
    ],
  },
];

const skills: SkillRecord[] = [
  {
    id: "skill-001",
    name: "Boss Outreach Drafting",
    version: "1.2.0",
    status: "active",
    boundNode: "initiate_communication",
    platform: "Boss直聘",
    health: "healthy",
    lastCheckedAt: iso(-30),
    summary: "Produces short, respectful outreach with role-specific context.",
  },
  {
    id: "skill-002",
    name: "Resume Screening",
    version: "1.0.4",
    status: "pending_review",
    boundNode: "initial_screening",
    platform: "Boss直聘",
    health: "warning",
    lastCheckedAt: iso(-90),
    summary: "Drafted from recent candidate examples and pending approval.",
  },
  {
    id: "skill-003",
    name: "Talent Pool Packaging",
    version: "0.9.1",
    status: "degraded",
    boundNode: "candidate_scoring",
    platform: "Boss直聘",
    health: "critical",
    lastCheckedAt: iso(-240),
    summary: "Selector drift detected in the last browser run.",
  },
];

const approvals: ApprovalItem[] = [
  {
    id: "apr-001",
    kind: "skill",
    title: "Approve resume screening Skill",
    detail: "Review the new initial screening strategy before it can become active.",
    requester: "Agent",
    status: "pending",
    createdAt: iso(-45),
  },
  {
    id: "apr-002",
    kind: "workflow",
    title: "Activate talent pool handoff",
    detail: "Enables the workflow path from scoring to human review.",
    requester: "Ops",
    status: "pending",
    createdAt: iso(-65),
  },
  {
    id: "apr-003",
    kind: "system_command",
    title: "Allow local package inspection command",
    detail: "Registers a safe command under whitelist control.",
    requester: "Agent",
    status: "rejected",
    createdAt: iso(-180),
  },
];

const agent: AgentSnapshot = {
  status: "running",
  activeTask: "Initial screening for Mia Chen",
  browserLock: "held",
  uptime: "03:12:41",
  queueDepth: 4,
  tokenBudgetUsed: 38,
  health: "warning",
};

const events: TimelineEvent[] = [
  {
    id: "evt-001",
    label: "Workflow node advanced",
    detail: "Moved Mia Chen into the screening step.",
    at: iso(-12),
    tone: "positive",
  },
  {
    id: "evt-002",
    label: "Approval pending",
    detail: "Resume screening Skill is waiting for review.",
    at: iso(-32),
    tone: "warning",
  },
  {
    id: "evt-003",
    label: "Cooldown applied",
    detail: "Luna Wang was marked to avoid repeat outreach.",
    at: iso(-48),
    tone: "neutral",
  },
];

const alerts: TimelineEvent[] = [
  {
    id: "alert-001",
    label: "Selector drift detected",
    detail: "Talent pool packaging requires a refresh before full automation.",
    at: iso(-22),
    tone: "critical",
  },
];

const settings: SettingsSnapshot = {
  locale: "en-US",
  timezone: "Asia/Shanghai",
  intranetEnabled: false,
  desktopApprovalsOnly: true,
  providers: [
    { kind: "openai-compatible", name: "Primary OpenAI API", model: "gpt-5.4", enabled: true, temperature: 0.2, baseUrl: "https://api.openai.com/v1" },
    { kind: "anthropic", name: "Fallback Anthropic", model: "claude-sonnet-4", enabled: false, temperature: 0.2, baseUrl: "https://api.anthropic.com" },
  ],
  platform: {
    name: "Boss直聘",
    account: "recruiter-01",
    cooldownDays: 18,
    allowOutboundMessaging: false,
  },
};

const metrics = [
  { label: "Candidates screened", value: "126", delta: "+14%", tone: "positive" as const, caption: "Past 7 days" },
  { label: "Reply rate", value: "41%", delta: "+6%", tone: "positive" as const, caption: "Outreach to response" },
  { label: "Budget used", value: "$182", delta: "-9%", tone: "neutral" as const, caption: "Token spend this week" },
  { label: "Manual approvals", value: "3", delta: "1 pending", tone: "warning" as const, caption: "Human gate queue" },
];

const pipeline = [
  { label: "Discovery", value: 18, target: 20 },
  { label: "Screening", value: 12, target: 16 },
  { label: "Communication", value: 7, target: 10 },
  { label: "Scoring", value: 4, target: 6 },
  { label: "Human review", value: 3, target: 4 },
];

export const desktopMockSnapshot: DashboardSummary = {
  metrics,
  pipeline,
  timeline: events,
  alerts,
  candidates,
  workflows,
  skills,
  approvals,
  agent,
  settings,
};

const runtimeTasks: RuntimeTaskSpec[] = [
  {
    id: "task-001",
    title: "Research PDF converters",
    description: "Compiled from natural language for Web Research.",
    goal: "Find useful PDF converters, compare them, and prepare a shortlist.",
    domain: "web_research",
    status: "trial_ready",
    sourceKind: "natural_language",
    sourceText: "Open the web and find useful PDF converters, compare them, and prepare a shortlist.",
    inputs: {},
    constraints: { requires_human_supervision: true },
    successCriteria: { minimum_candidates: 3, include_comparison: true },
    approvalPolicy: { mode: "desktop_review", trial_required: true },
    outputContract: { kind: "research_shortlist", format: "table" },
    preferredCapabilities: ["search", "browser", "http", "llm", "document"],
    preferredDomains: ["web_research"],
    compiledPayload: { domain_pack: "web_research", requires_trial: true },
    activePlanId: "plan-001",
    createdAt: iso(-200),
    updatedAt: iso(-120),
  },
  {
    id: "task-002",
    title: "Daily GitHub hot projects",
    description: "Compiled from natural language for GitHub Trends.",
    goal: "Find the hottest GitHub projects today and summarize them with repo links.",
    domain: "github_trends",
    status: "compiled",
    sourceKind: "natural_language",
    sourceText: "GitHub 上今天的热点项目是哪些，找到仓库地址和项目简介发给我。",
    inputs: {},
    constraints: { requires_source_links: true },
    successCriteria: { minimum_repositories: 5, include_repo_links: true },
    approvalPolicy: { mode: "desktop_review", trial_required: true },
    outputContract: { kind: "repository_digest", format: "table" },
    preferredCapabilities: ["http", "browser", "llm", "document"],
    preferredDomains: ["github_trends"],
    compiledPayload: { domain_pack: "github_trends", requires_trial: true },
    activePlanId: "plan-002",
    createdAt: iso(-90),
    updatedAt: iso(-60),
  },
];

const runtimePlans: RuntimeExecutionPlan[] = [
  {
    id: "plan-001",
    taskSpecId: "task-001",
    name: "Research PDF converters Trial Plan",
    mode: "trial",
    status: "validated",
    version: 2,
    approvalState: "template_candidate",
    planBody: {
      steps: [
        { id: "understand_task", capability: "analyze" },
        { id: "search_1", capability: "search" },
        { id: "browser_2", capability: "browser" },
        { id: "http_3", capability: "http" },
        { id: "summarize_result", capability: "document" },
      ],
      instruction: "Find useful PDF converters and prepare a shortlist.",
      domain: "web_research",
    },
    environmentRequirements: { requires_browser: true, requires_network: true },
    checkpoints: [{ kind: "approval", label: "Review shortlist before reuse" }],
    runtimeMetadata: { compiler: "heuristic", domain_pack: "web_research" },
    compiledFromPatchId: undefined,
    createdAt: iso(-200),
    updatedAt: iso(-30),
  },
  {
    id: "plan-002",
    taskSpecId: "task-002",
    name: "Daily GitHub hot projects Trial Plan",
    mode: "trial",
    status: "diverged",
    version: 1,
    approvalState: "pending_review",
    planBody: {
      steps: [
        { id: "collect_trending_repos", capability: "http" },
        { id: "inspect_repository_pages", capability: "browser" },
        { id: "summarize_repositories", capability: "llm" },
      ],
      instruction: "Find GitHub trending repositories and summarize them.",
      domain: "github_trends",
    },
    environmentRequirements: { requires_browser: true, requires_network: true },
    checkpoints: [{ kind: "approval", label: "Review divergence and patch proposal" }],
    runtimeMetadata: { compiler: "heuristic", domain_pack: "github_trends" },
    compiledFromPatchId: undefined,
    createdAt: iso(-90),
    updatedAt: iso(-18),
  },
];

const runtimeEpisodes: RuntimeEpisode[] = [
  {
    id: "episode-001",
    taskSpecId: "task-001",
    executionPlanId: "plan-001",
    mode: "trial",
    status: "awaiting_review",
    requestedBy: "desktop-user",
    requiresConfirmation: true,
    startedAt: iso(-70),
    finishedAt: iso(-65),
    resultSummary: "Trial run explored the web and produced a shortlist-oriented summary.",
    observations: [{ step_id: "browser_2", kind: "observation", summary: "Inspected the first batch of tools." }],
    actions: [{ step_id: "search_1", capability: "search", status: "completed" }],
    metrics: { step_count: 5, completion_rate: 1 },
    divergenceDetected: false,
    patchId: undefined,
    runtimeMetadata: { operator: "desktop-user" },
    createdAt: iso(-70),
    updatedAt: iso(-65),
  },
  {
    id: "episode-002",
    taskSpecId: "task-002",
    executionPlanId: "plan-002",
    mode: "trial",
    status: "diverged",
    requestedBy: "desktop-user",
    requiresConfirmation: true,
    startedAt: iso(-24),
    finishedAt: iso(-18),
    resultSummary: "Trial run gathered trending repositories but environment drift suggested a checkpoint update.",
    observations: [{ step_id: "inspect_repository_pages", kind: "observation", summary: "Trending layout drifted." }],
    actions: [{ step_id: "collect_trending_repos", capability: "http", status: "completed" }],
    metrics: { step_count: 3, completion_rate: 1 },
    divergenceDetected: true,
    patchId: "patch-001",
    runtimeMetadata: { operator: "desktop-user" },
    createdAt: iso(-24),
    updatedAt: iso(-18),
  },
];

const runtimeSnapshots: RuntimeSnapshot[] = [
  {
    id: "snapshot-001",
    taskSpecId: "task-001",
    executionPlanId: "plan-001",
    executionEpisodeId: "episode-001",
    source: "browser",
    environmentKey: "web_research:browser",
    status: "captured",
    url: "https://example.com/pdf-tools",
    title: "PDF tools comparison page",
    pageType: "tool_listing",
    capabilityHints: ["search", "browser"],
    observedEntities: [{ kind: "tool_card", label: "Converter A" }],
    affordances: [{ kind: "open_tool", label: "Open tool page" }],
    runtimeMetadata: { plan_name: "Research PDF converters Trial Plan" },
    createdAt: iso(-66),
    updatedAt: iso(-66),
  },
  {
    id: "snapshot-002",
    taskSpecId: "task-002",
    executionPlanId: "plan-002",
    executionEpisodeId: "episode-002",
    source: "browser",
    environmentKey: "github_trends:browser",
    status: "captured",
    url: "https://github.com/trending",
    title: "GitHub Trending",
    pageType: "repository_listing",
    capabilityHints: ["http", "browser"],
    observedEntities: [{ kind: "repository_card", label: "example/repo" }],
    affordances: [{ kind: "open_repository", label: "Open repository page" }],
    runtimeMetadata: { plan_name: "Daily GitHub hot projects Trial Plan" },
    createdAt: iso(-18),
    updatedAt: iso(-18),
  },
];

const runtimeTemplates: RuntimeTemplate[] = [
  {
    id: "template-001",
    templateKey: "web_research_research_pdf_converters",
    name: "Research PDF converters Template",
    domain: "web_research",
    status: "draft",
    version: 1,
    sourceTaskSpecId: "task-001",
    templateBody: { steps: runtimePlans[0].planBody.steps, checkpoints: runtimePlans[0].checkpoints },
    activationStrategy: { mode: "supervised_trial_first", requires_confirmation: true },
    validationSummary: "Validated during supervised trial execution.",
    lastValidatedAt: iso(-65),
    createdAt: iso(-64),
    updatedAt: iso(-64),
  },
  {
    id: "template-002",
    templateKey: "github_trends_digest",
    name: "GitHub Trends Digest",
    domain: "github_trends",
    status: "active",
    version: 1,
    sourceTaskSpecId: undefined,
    templateBody: { steps: runtimePlans[1].planBody.steps },
    activationStrategy: { mode: "trial_first" },
    validationSummary: "Seeded template for GitHub trends monitoring.",
    lastValidatedAt: iso(-320),
    createdAt: iso(-320),
    updatedAt: iso(-320),
  },
];

const runtimePatches: RuntimePatch[] = [
  {
    id: "patch-001",
    title: "Patch Daily GitHub hot projects",
    patchKind: "execution_divergence",
    status: "pending_review",
    templateId: "template-002",
    taskSpecId: "task-002",
    executionPlanId: "plan-002",
    executionEpisodeId: "episode-002",
    proposedBy: "runtime",
    divergenceSummary: "Trial execution diverged while handling repository_listing.",
    rationale: "The observed environment differed from the current execution plan.",
    patchBody: { operations: [{ op: "review_checkpoint", target: "repository_listing" }] },
    runtimeMetadata: { generatedFromEpisode: "episode-002" },
    createdAt: iso(-18),
    updatedAt: iso(-18),
  },
];

const domainPacks: DomainPackRecord[] = [
  {
    key: "general",
    name: "General Automation",
    description: "A generic supervised automation pack for exploratory browser or desktop tasks.",
    defaultCapabilities: ["analyze", "browser", "llm", "document"],
    sampleTasks: ["Open a site and summarize it.", "Try a new workflow under supervision."],
    defaultConstraints: { requires_human_supervision: true },
    defaultOutputContract: { kind: "summary", format: "markdown" },
    templateKeys: ["general_supervised_trial", "patch_review_loop"],
  },
  {
    key: "recruiting",
    name: "Recruiting",
    description: "Source candidates, capture context, screen, and prepare approved handoffs.",
    defaultCapabilities: ["browser", "search", "document", "llm", "api"],
    sampleTasks: ["Find candidates and score them.", "Capture resumes and prepare recruiter notes."],
    defaultConstraints: { requires_human_supervision: true, respect_messaging_approval: true },
    defaultOutputContract: { kind: "candidate_bundle" },
    templateKeys: ["recruiting_trial_screening"],
  },
  {
    key: "market_news",
    name: "Market News",
    description: "Collect fresh market news and assemble a concise digest.",
    defaultCapabilities: ["search", "http", "browser", "llm", "document"],
    sampleTasks: ["Find the latest stock market news and summarize it."],
    defaultConstraints: { requires_source_links: true },
    defaultOutputContract: { kind: "news_digest" },
    templateKeys: ["market_news_digest"],
  },
  {
    key: "web_research",
    name: "Web Research",
    description: "Search, compare, and shortlist tools or resources from the open web.",
    defaultCapabilities: ["search", "browser", "http", "llm", "document"],
    sampleTasks: ["Find useful PDF converters and compare them."],
    defaultConstraints: { requires_source_links: true },
    defaultOutputContract: { kind: "research_shortlist" },
    templateKeys: ["web_research_shortlist"],
  },
  {
    key: "github_trends",
    name: "GitHub Trends",
    description: "Track hot repositories and summarize why they matter.",
    defaultCapabilities: ["http", "browser", "llm", "document"],
    sampleTasks: ["List today's hot GitHub repositories with repo links."],
    defaultConstraints: { requires_source_links: true },
    defaultOutputContract: { kind: "repository_digest" },
    templateKeys: ["github_trends_digest"],
  },
];

export const desktopRuntimeMock: RuntimeWorkspaceData = {
  domainPacks,
  taskSpecs: runtimeTasks,
  plans: runtimePlans,
  episodes: runtimeEpisodes,
  snapshots: runtimeSnapshots,
  templates: runtimeTemplates,
  patches: runtimePatches,
};
