import type {
  ApprovalItem,
  AgentSnapshot,
  CandidateRecord,
  DashboardSummary,
  DomainPackRecord,
  RuntimeCapabilityDriver,
  RuntimeCompilerContract,
  RuntimeEnvironmentAssessment,
  RuntimeExecutionPlan,
  RuntimeEpisode,
  RuntimeEpisodeReplay,
  RuntimePatch,
  RuntimePlanReplanResult,
  RuntimeSnapshot,
  RuntimeTaskSpec,
  RuntimeTemplate,
  RuntimeWorkspaceData,
  SettingsSnapshot,
  SkillRecord,
  SyncBacklogItem,
  SyncStatusSnapshot,
  TimelineEvent,
  WorkflowDefinition,
} from "./types";

const now = new Date();
const iso = (offsetMinutes: number): string => new Date(now.getTime() + offsetMinutes * 60_000).toISOString();

const candidates: CandidateRecord[] = [
  {
    id: "cand-001",
    name: "Mia Chen",
    title: "Senior Frontend Engineer",
    platform: "Recruiting scene",
    location: "Shanghai",
    status: "screening",
    workflowNode: "initial_screening",
    jdTitle: "Frontend Platform Engineer",
    matchScore: 92,
    experienceYears: 8,
    nextAction: "Verify system design depth and React performance examples.",
    summary: "Strong product sense, clear ownership, and good balance of UI craft and engineering depth.",
    tags: ["React", "Design Systems", "Performance"],
    resumeAvailable: true,
    lastContactedAt: iso(-120),
  },
  {
    id: "cand-002",
    name: "Jason Li",
    title: "Backend Engineer",
    platform: "Recruiting scene",
    location: "Hangzhou",
    status: "pending_communication",
    workflowNode: "initiate_communication",
    jdTitle: "Platform Engineer",
    matchScore: 84,
    experienceYears: 6,
    nextAction: "Send outreach message with salary range and team scope.",
    summary: "Reliable service design experience with strong ownership in backend operations.",
    tags: ["Go", "PostgreSQL", "APIs"],
    resumeAvailable: false,
  },
  {
    id: "cand-003",
    name: "Luna Wang",
    title: "Product Manager",
    platform: "Recruiting scene",
    location: "Beijing",
    status: "cooldown",
    workflowNode: "cooldown",
    jdTitle: "Product Lead",
    matchScore: 73,
    experienceYears: 7,
    nextAction: "Respect cooldown until the next contact window opens.",
    summary: "Rejected after communication. Store on hold and avoid repeated outreach.",
    tags: ["Discovery", "Roadmap", "Analytics"],
    resumeAvailable: true,
    cooldownUntil: iso(60 * 24 * 18),
    lastContactedAt: iso(-1440),
  },
];

const workflows: WorkflowDefinition[] = [
  {
    id: "wf-screening",
    name: "Discovery to Screening",
    jdTitle: "Frontend Platform Engineer",
    status: "active",
    version: "v1.3",
    updatedAt: iso(-180),
    nodes: [
      { id: "discover", name: "Discover candidates", kind: "discover", status: "approved", owner: "Scheduler", description: "Search and ingest candidate profiles." },
      { id: "initial_screening", name: "Initial screening", kind: "screen", status: "running", owner: "Agent", description: "Read resumes and evaluate against JD criteria." },
      { id: "initiate_communication", name: "Initiate communication", kind: "communicate", status: "idle", owner: "Agent", description: "Send outreach using approved message templates." },
      { id: "request_resume", name: "Request resume", kind: "resume", status: "idle", owner: "Agent", description: "Collect structured resume artifacts." },
      { id: "candidate_scoring", name: "Candidate scoring", kind: "score", status: "idle", owner: "Agent", description: "Produce scoring and reasoning payloads." },
      { id: "hr_review", name: "HR review", kind: "review", status: "blocked", owner: "Human", description: "Await approval before talent pool sync." },
    ],
  },
  {
    id: "wf-talent-pool",
    name: "Talent Pool Handoff",
    jdTitle: "Platform Engineer",
    status: "draft",
    version: "v0.8",
    updatedAt: iso(-75),
    nodes: [
      { id: "screen", name: "Screen", kind: "screen", status: "approved", owner: "Agent", description: "Score against criteria." },
      { id: "talent_pool_upload", name: "Upload to talent pool", kind: "review", status: "idle", owner: "Human", description: "Push qualified candidates to the internal system." },
    ],
  },
];

const skills: SkillRecord[] = [
  {
    id: "skill-001",
    name: "Recruiting Scene Outreach Drafting",
    version: "1.2.0",
    status: "active",
    boundNode: "initiate_communication",
    platform: "Recruiting scene",
    health: "healthy",
    lastCheckedAt: iso(-30),
    summary: "Produces short, respectful outreach with role-specific context.",
  },
  {
    id: "skill-002",
    name: "Resume Screening",
    version: "1.0.4",
    status: "pending_review",
    boundNode: "initial_screening",
    platform: "Recruiting scene",
    health: "warning",
    lastCheckedAt: iso(-90),
    summary: "Drafted from recent candidate examples and pending approval.",
  },
  {
    id: "skill-003",
    name: "Talent Pool Packaging",
    version: "0.9.1",
    status: "degraded",
    boundNode: "candidate_scoring",
    platform: "Recruiting scene",
    health: "critical",
    lastCheckedAt: iso(-240),
    summary: "Selector drift detected in the last browser run.",
  },
];

const approvals: ApprovalItem[] = [
  {
    id: "apr-001",
    kind: "skill",
    title: "Approve resume screening Skill",
    detail: "Review the new initial screening strategy before it can become active.",
    requester: "Agent",
    status: "pending",
    createdAt: iso(-45),
  },
  {
    id: "apr-002",
    kind: "workflow",
    title: "Activate talent pool handoff",
    detail: "Enables the workflow path from scoring to human review.",
    requester: "Ops",
    status: "pending",
    createdAt: iso(-65),
  },
  {
    id: "apr-003",
    kind: "system_command",
    title: "Allow local package inspection command",
    detail: "Registers a safe command under whitelist control.",
    requester: "Agent",
    status: "rejected",
    createdAt: iso(-180),
  },
];

const agent: AgentSnapshot = {
  status: "running",
  activeTask: "Initial screening for Mia Chen",
  browserLock: "held",
  uptime: "03:12:41",
  queueDepth: 4,
  tokenBudgetUsed: 38,
  health: "warning",
};

const events: TimelineEvent[] = [
  {
    id: "evt-001",
    label: "Workflow node advanced",
    detail: "Moved Mia Chen into the screening step.",
    at: iso(-12),
    tone: "positive",
  },
  {
    id: "evt-002",
    label: "Approval pending",
    detail: "Resume screening Skill is waiting for review.",
    at: iso(-32),
    tone: "warning",
  },
  {
    id: "evt-003",
    label: "Cooldown applied",
    detail: "Luna Wang was marked to avoid repeat outreach.",
    at: iso(-48),
    tone: "neutral",
  },
];

const alerts: TimelineEvent[] = [
  {
    id: "alert-001",
    label: "Selector drift detected",
    detail: "Talent pool packaging requires a refresh before full automation.",
    at: iso(-22),
    tone: "critical",
  },
];

const settings: SettingsSnapshot = {
  locale: "en-US",
  timezone: "Asia/Shanghai",
  intranetEnabled: false,
  desktopApprovalsOnly: true,
  skillHealthAutonomyEnabled: false,
  skillHealthAutonomyIntervalSeconds: 300,
  providers: [
    { kind: "openai-compatible", name: "Primary OpenAI API", model: "gpt-5.4", enabled: true, temperature: 0.2, baseUrl: "https://api.openai.com/v1" },
    { kind: "anthropic", name: "Fallback Anthropic", model: "claude-sonnet-4", enabled: false, temperature: 0.2, baseUrl: "https://api.anthropic.com" },
  ],
  platform: {
    name: "Recruiting scene profile",
    account: "runtime-scene-01",
    cooldownDays: 18,
    allowOutboundMessaging: false,
  },
};

const metrics = [
  { label: "Candidates screened", value: "126", delta: "+14%", tone: "positive" as const, caption: "Past 7 days" },
  { label: "Reply rate", value: "41%", delta: "+6%", tone: "positive" as const, caption: "Outreach to response" },
  { label: "Budget used", value: "$182", delta: "-9%", tone: "neutral" as const, caption: "Token spend this week" },
  { label: "Manual approvals", value: "3", delta: "1 pending", tone: "warning" as const, caption: "Human gate queue" },
];

const pipeline = [
  { label: "Discovery", value: 18, target: 20 },
  { label: "Screening", value: 12, target: 16 },
  { label: "Communication", value: 7, target: 10 },
  { label: "Scoring", value: 4, target: 6 },
  { label: "Human review", value: 3, target: 4 },
];

export const desktopMockSnapshot: DashboardSummary = {
  metrics,
  pipeline,
  timeline: events,
  alerts,
  candidates,
  workflows,
  skills,
  approvals,
  agent,
  settings,
};

const runtimeTasks: RuntimeTaskSpec[] = [
  {
    id: "task-001",
    title: "Research PDF converters",
    description: "Compiled from natural language for Web Research.",
    goal: "Find useful PDF converters, compare them, and prepare a shortlist.",
    domain: "web_research",
    status: "trial_ready",
    sourceKind: "natural_language",
    sourceText: "Open the web and find useful PDF converters, compare them, and prepare a shortlist.",
    inputs: {},
    constraints: { requires_human_supervision: true },
    successCriteria: { minimum_candidates: 3, include_comparison: true },
    approvalPolicy: { mode: "desktop_review", trial_required: true },
    outputContract: { kind: "research_shortlist", format: "table" },
    preferredCapabilities: ["search", "browser", "http", "llm", "document"],
    preferredDomains: ["web_research"],
    compiledPayload: { domain_pack: "web_research", requires_trial: true },
    activePlanId: "plan-001",
    createdAt: iso(-200),
    updatedAt: iso(-120),
  },
  {
    id: "task-002",
    title: "Daily GitHub hot projects",
    description: "Compiled from natural language for GitHub Trends.",
    goal: "Find the hottest GitHub projects today and summarize them with repo links.",
    domain: "github_trends",
    status: "compiled",
    sourceKind: "natural_language",
    sourceText: "GitHub 上今天的热点项目是哪些，找到仓库地址和项目简介发给我。",
    inputs: {},
    constraints: { requires_source_links: true },
    successCriteria: { minimum_repositories: 5, include_repo_links: true },
    approvalPolicy: { mode: "desktop_review", trial_required: true },
    outputContract: { kind: "repository_digest", format: "table" },
    preferredCapabilities: ["http", "browser", "llm", "document"],
    preferredDomains: ["github_trends"],
    compiledPayload: { domain_pack: "github_trends", requires_trial: true },
    activePlanId: "plan-002",
    createdAt: iso(-90),
    updatedAt: iso(-60),
  },
];

const runtimePlans: RuntimeExecutionPlan[] = [
  {
    id: "plan-001",
    taskSpecId: "task-001",
    name: "Research PDF converters Trial Plan",
    mode: "trial",
    status: "validated",
    version: 2,
    approvalState: "template_candidate",
    planBody: {
      steps: [
        { id: "understand_task", capability: "analyze" },
        { id: "search_1", capability: "search" },
        { id: "browser_2", capability: "browser" },
        { id: "http_3", capability: "http" },
        { id: "summarize_result", capability: "document" },
      ],
      instruction: "Find useful PDF converters and prepare a shortlist.",
      domain: "web_research",
    },
    environmentRequirements: { requires_browser: true, requires_network: true },
    checkpoints: [{ kind: "approval", label: "Review shortlist before reuse" }],
    runtimeMetadata: { compiler: "heuristic", domain_pack: "web_research" },
    compiledFromPatchId: undefined,
    createdAt: iso(-200),
    updatedAt: iso(-30),
  },
  {
    id: "plan-002",
    taskSpecId: "task-002",
    name: "Daily GitHub hot projects Trial Plan",
    mode: "trial",
    status: "diverged",
    version: 1,
    approvalState: "pending_review",
    planBody: {
      steps: [
        { id: "collect_trending_repos", capability: "http" },
        { id: "inspect_repository_pages", capability: "browser" },
        { id: "summarize_repositories", capability: "llm" },
      ],
      instruction: "Find GitHub trending repositories and summarize them.",
      domain: "github_trends",
    },
    environmentRequirements: { requires_browser: true, requires_network: true },
    checkpoints: [{ kind: "approval", label: "Review divergence and patch proposal" }],
    runtimeMetadata: { compiler: "heuristic", domain_pack: "github_trends" },
    compiledFromPatchId: undefined,
    createdAt: iso(-90),
    updatedAt: iso(-18),
  },
];

const runtimeEpisodes: RuntimeEpisode[] = [
  {
    id: "episode-001",
    taskSpecId: "task-001",
    executionPlanId: "plan-001",
    mode: "trial",
    status: "awaiting_review",
    requestedBy: "desktop-user",
    requiresConfirmation: true,
    startedAt: iso(-70),
    finishedAt: iso(-65),
    resultSummary: "Trial run explored the web and produced a shortlist-oriented summary.",
    observations: [{ step_id: "browser_2", kind: "observation", summary: "Inspected the first batch of tools." }],
    actions: [{ step_id: "search_1", capability: "search", status: "completed" }],
    metrics: { step_count: 5, completion_rate: 1 },
    divergenceDetected: false,
    patchId: undefined,
    runtimeMetadata: { operator: "desktop-user" },
    createdAt: iso(-70),
    updatedAt: iso(-65),
  },
  {
    id: "episode-002",
    taskSpecId: "task-002",
    executionPlanId: "plan-002",
    mode: "trial",
    status: "diverged",
    requestedBy: "desktop-user",
    requiresConfirmation: true,
    startedAt: iso(-24),
    finishedAt: iso(-18),
    resultSummary: "Trial run gathered trending repositories but environment drift suggested a checkpoint update.",
    observations: [{ step_id: "inspect_repository_pages", kind: "observation", summary: "Trending layout drifted." }],
    actions: [{ step_id: "collect_trending_repos", capability: "http", status: "completed" }],
    metrics: { step_count: 3, completion_rate: 1 },
    divergenceDetected: true,
    patchId: "patch-001",
    runtimeMetadata: { operator: "desktop-user" },
    createdAt: iso(-24),
    updatedAt: iso(-18),
  },
];

const runtimeSnapshots: RuntimeSnapshot[] = [
  {
    id: "snapshot-001",
    taskSpecId: "task-001",
    executionPlanId: "plan-001",
    executionEpisodeId: "episode-001",
    source: "browser",
    environmentKey: "web_research:browser",
    status: "captured",
    url: "https://example.com/pdf-tools",
    title: "PDF tools comparison page",
    pageType: "tool_listing",
    capabilityHints: ["search", "browser"],
    observedEntities: [{ kind: "tool_card", label: "Converter A" }],
    affordances: [{ kind: "open_tool", label: "Open tool page" }],
    runtimeMetadata: { plan_name: "Research PDF converters Trial Plan" },
    createdAt: iso(-66),
    updatedAt: iso(-66),
  },
  {
    id: "snapshot-002",
    taskSpecId: "task-002",
    executionPlanId: "plan-002",
    executionEpisodeId: "episode-002",
    source: "browser",
    environmentKey: "github_trends:browser",
    status: "captured",
    url: "https://github.com/trending",
    title: "GitHub Trending",
    pageType: "repository_listing",
    capabilityHints: ["http", "browser"],
    observedEntities: [{ kind: "repository_card", label: "example/repo" }],
    affordances: [{ kind: "open_repository", label: "Open repository page" }],
    runtimeMetadata: { plan_name: "Daily GitHub hot projects Trial Plan" },
    createdAt: iso(-18),
    updatedAt: iso(-18),
  },
];

const runtimeCapabilityDrivers: RuntimeCapabilityDriver[] = [
  {
    id: "driver-001",
    key: "browser.navigator",
    name: "Browser Navigator",
    category: "browser",
    status: "ready",
    scope: "Navigate, inspect DOM state, and capture supervised actions in web scenes.",
    description: "Preferred when the runtime needs direct page observation, click targets, or scene screenshots.",
    safetyMode: "supervised_write",
    supportsWrite: true,
    sceneTypes: ["candidate_listing", "repository_listing", "tool_listing", "detail_page"],
    signalLabels: ["dom_affordances", "scene_classifier", "selector_confidence"],
    updatedAt: iso(-15),
  },
  {
    id: "driver-002",
    key: "search.discovery",
    name: "Search Discovery",
    category: "search",
    status: "ready",
    scope: "Query the public web and feed ranked result candidates into trial plans.",
    description: "Used for exploratory tasks that need broad discovery before browser or HTTP inspection.",
    safetyMode: "read_only",
    supportsWrite: false,
    sceneTypes: ["search_results", "research_seed"],
    signalLabels: ["ranking_score", "source_diversity", "query_rewrite"],
    updatedAt: iso(-22),
  },
  {
    id: "driver-003",
    key: "http.harvest",
    name: "HTTP Harvest",
    category: "http",
    status: "degraded",
    scope: "Fetch structured pages or APIs before escalating to browser inspection.",
    description: "Useful when a scene can be resolved through lightweight requests, but currently seeing partial schema drift.",
    safetyMode: "read_only",
    supportsWrite: false,
    sceneTypes: ["repository_listing", "news_feed", "api_resource"],
    signalLabels: ["schema_match", "response_latency", "rate_limit"],
    updatedAt: iso(-18),
  },
  {
    id: "driver-004",
    key: "document.summarizer",
    name: "Document Summarizer",
    category: "document",
    status: "ready",
    scope: "Normalize gathered evidence into operator-facing outputs and replay artifacts.",
    description: "Turns browser and HTTP evidence into digests, scorecards, and approval-ready summaries.",
    safetyMode: "local_only",
    supportsWrite: true,
    sceneTypes: ["summary", "scorecard", "handoff_bundle"],
    signalLabels: ["output_contract", "coverage_score", "citation_density"],
    updatedAt: iso(-11),
  },
];

const runtimeEnvironmentAssessments: RuntimeEnvironmentAssessment[] = [
  {
    id: "assessment-001",
    taskSpecId: "task-001",
    executionPlanId: "plan-001",
    executionEpisodeId: "episode-001",
    snapshotId: "snapshot-001",
    environmentKey: "web_research:browser",
    sceneLabel: "PDF converter comparison listing",
    sceneType: "tool_listing",
    status: "aligned",
    confidence: 0.94,
    summary: "Observed tool cards and comparison affordances still match the current supervised research plan.",
    observedEntities: [
      {
        kind: "tool_card",
        label: "PDF converter card",
        entityId: "tool-card-1",
        role: "result",
        confidence: 0.94,
        state: "visible",
        interactive: true,
        signals: ["listing_surface"],
        locator: { selector: "[data-tool-card]" },
        attributes: { count: 8 },
      },
    ],
    affordances: [
      {
        kind: "link",
        label: "Open tool",
        action: "navigate",
        target: "detail_page",
        confidence: 0.9,
        enabled: true,
        requiresConfirmation: false,
        signals: ["navigation_target"],
        locator: { selector: "a[data-open-tool]" },
        metadata: {},
      },
    ],
    sceneProfile: {
      source: "browser",
      sceneType: "tool_listing",
      interactionMode: "navigate",
      volatility: "low",
      authState: "clear",
      entityCount: 3,
      affordanceCount: 3,
      primaryTargets: ["PDF converter card"],
      signals: ["listing_surface", "well_observed_scene"],
      blockers: [],
      evidence: { observed_entity_kinds: ["tool_card", "pricing_badge", "feature_table"] },
    },
    plannerGuidance: {
      posture: "verify",
      requiredCapabilities: ["search.discovery", "browser.navigator", "document.summarizer"],
      insertedCapabilities: ["browser.navigator"],
      preferredNextActions: ["Confirm the listing layout before capturing detailed tool notes."],
      requiresSceneAssessment: true,
      requiresHumanReview: false,
      shouldCheckpoint: true,
      rationale: ["The scene is healthy, but the runtime should verify the comparison layout before extraction."],
    },
    capabilityKeys: ["search.discovery", "browser.navigator", "document.summarizer"],
    observedLabels: ["tool_card", "pricing_badge", "feature_table"],
    affordanceLabels: ["open_tool", "compare_features", "capture_notes"],
    driftSignals: [],
    recommendedActions: ["Keep the existing trial template active.", "Promote the template after confirmation if the shortlist still looks correct."],
    updatedAt: iso(-14),
  },
  {
    id: "assessment-002",
    taskSpecId: "task-002",
    executionPlanId: "plan-002",
    executionEpisodeId: "episode-002",
    snapshotId: "snapshot-002",
    environmentKey: "github_trends:browser",
    sceneLabel: "GitHub Trending repository feed",
    sceneType: "repository_listing",
    status: "drift_detected",
    confidence: 0.72,
    summary: "The listing is still recognizable, but repository cards moved key metadata behind an extra interaction layer.",
    observedEntities: [
      {
        kind: "repository_card",
        label: "Repository card",
        entityId: "repo-card-1",
        role: "result",
        confidence: 0.83,
        state: "partial",
        interactive: true,
        signals: ["listing_surface", "detail_surface"],
        locator: { selector: "[data-repo-card]" },
        attributes: { expanded: false },
      },
    ],
    affordances: [
      {
        kind: "button",
        label: "Expand details",
        action: "click",
        target: "repository_metadata",
        confidence: 0.76,
        enabled: true,
        requiresConfirmation: false,
        signals: ["navigation_target"],
        locator: { selector: "button[data-expand]" },
        metadata: {},
      },
    ],
    sceneProfile: {
      source: "browser",
      sceneType: "repository_listing",
      interactionMode: "navigate",
      volatility: "medium",
      authState: "clear",
      entityCount: 3,
      affordanceCount: 3,
      primaryTargets: ["Repository card"],
      signals: ["listing_surface", "detail_surface"],
      blockers: ["scene_needs_reassessment"],
      evidence: { observed_entity_kinds: ["repository_card", "language_badge", "star_delta"] },
    },
    plannerGuidance: {
      posture: "recover",
      requiredCapabilities: ["http.harvest", "browser.navigator", "document.summarizer"],
      insertedCapabilities: ["browser.navigator"],
      preferredNextActions: [
        "Reassess the repository listing layout before detail extraction.",
        "Bias the next replan toward mixed HTTP plus browser extraction.",
      ],
      requiresSceneAssessment: true,
      requiresHumanReview: true,
      shouldCheckpoint: true,
      rationale: ["Scene drift suggests the planner should recover with a fresh browser assessment before continuing."],
    },
    capabilityKeys: ["http.harvest", "browser.navigator", "document.summarizer"],
    observedLabels: ["repository_card", "language_badge", "star_delta"],
    affordanceLabels: ["open_repository", "expand_details", "capture_digest"],
    driftSignals: ["Metadata collapsed behind dynamic expansion.", "Star delta moved to a secondary row."],
    recommendedActions: ["Insert a scene assessment checkpoint before repository detail capture.", "Bias the next replan toward mixed HTTP plus browser extraction."],
    updatedAt: iso(-10),
  },
];

const runtimeTemplates: RuntimeTemplate[] = [
  {
    id: "template-001",
    templateKey: "web_research_research_pdf_converters",
    name: "Research PDF converters Template",
    domain: "web_research",
    status: "draft",
    version: 1,
    sourceTaskSpecId: "task-001",
    templateBody: { steps: runtimePlans[0].planBody.steps, checkpoints: runtimePlans[0].checkpoints },
    activationStrategy: { mode: "supervised_trial_first", requires_confirmation: true },
    validationSummary: "Validated during supervised trial execution.",
    lastValidatedAt: iso(-65),
    createdAt: iso(-64),
    updatedAt: iso(-64),
  },
  {
    id: "template-002",
    templateKey: "github_trends_digest",
    name: "GitHub Trends Digest",
    domain: "github_trends",
    status: "active",
    version: 1,
    sourceTaskSpecId: undefined,
    templateBody: { steps: runtimePlans[1].planBody.steps },
    activationStrategy: { mode: "trial_first" },
    validationSummary: "Seeded template for GitHub trends monitoring.",
    lastValidatedAt: iso(-320),
    createdAt: iso(-320),
    updatedAt: iso(-320),
  },
];

const runtimePatches: RuntimePatch[] = [
  {
    id: "patch-001",
    title: "Patch Daily GitHub hot projects",
    patchKind: "execution_divergence",
    status: "pending_review",
    templateId: "template-002",
    taskSpecId: "task-002",
    executionPlanId: "plan-002",
    executionEpisodeId: "episode-002",
    proposedBy: "runtime",
    divergenceSummary: "Trial execution diverged while handling repository_listing.",
    rationale: "The observed environment differed from the current execution plan.",
    patchBody: { operations: [{ op: "review_checkpoint", target: "repository_listing" }] },
    runtimeMetadata: { generatedFromEpisode: "episode-002" },
    createdAt: iso(-18),
    updatedAt: iso(-18),
  },
];

const runtimeReplans: RuntimePlanReplanResult[] = [
  {
    id: "replan-001",
    taskSpecId: "task-002",
    baseExecutionPlanId: "plan-002",
    executionPlan: {
      id: "plan-002-r2",
      taskSpecId: "task-002",
      name: "Daily GitHub hot projects Replan v2",
      mode: "trial",
      status: "proposed",
      version: 2,
      approvalState: "pending_review",
      planBody: {
        steps: [
          { id: "collect_trending_repos", capability: "http" },
          { id: "assess_repository_scene", capability: "browser" },
          { id: "inspect_repository_pages", capability: "browser" },
          { id: "summarize_repositories", capability: "document" },
        ],
        instruction: "Reassess the trending scene, then gather repository context and summarize it.",
        domain: "github_trends",
      },
      environmentRequirements: { requires_browser: true, requires_network: true, scene_assessment_required: true },
      checkpoints: [
        { kind: "scene_assessment", label: "Confirm repository listing layout before extraction" },
        { kind: "approval", label: "Review the updated digest plan before reuse" },
      ],
      runtimeMetadata: { compiler: "runtime_replanner", trigger: "scene_drift" },
      compiledFromPatchId: "patch-001",
      createdAt: iso(-8),
      updatedAt: iso(-8),
    },
    status: "proposed",
    trigger: "scene_drift",
    summary: "Inserted a scene assessment checkpoint and rebalanced the plan toward browser validation before document synthesis.",
    compilerNotes: [
      "Repository listing drift was localized to the detail capture portion of the plan.",
      "The output contract remains unchanged, so only extraction and checkpoint sequencing were updated.",
    ],
    recommendedCapabilityKeys: ["browser.navigator", "http.harvest", "document.summarizer"],
    environmentAssessment: runtimeEnvironmentAssessments[1],
    patch: runtimePatches[0],
    createdAt: iso(-8),
  },
];

const domainPacks: DomainPackRecord[] = [
  {
    key: "general",
    name: "General Automation",
    description: "A generic supervised automation pack for exploratory browser or desktop tasks.",
    version: "1.2.0",
    maturity: "beta",
    runtimeOnly: true,
    defaultCapabilities: ["analyze", "browser", "llm", "document"],
    sampleTasks: ["Open a site and summarize it.", "Try a new workflow under supervision."],
    defaultConstraints: { requires_human_supervision: true },
    defaultOutputContract: { kind: "summary", format: "markdown" },
    templateKeys: ["general_supervised_trial", "patch_review_loop"],
  },
  {
    key: "recruiting",
    name: "Recruiting",
    description: "Source candidates, capture context, screen, and prepare approved handoffs.",
    version: "1.1.0",
    maturity: "beta",
    runtimeOnly: true,
    defaultCapabilities: ["browser", "search", "document", "llm", "api"],
    sampleTasks: ["Find candidates and score them.", "Capture resumes and prepare recruiter notes."],
    defaultConstraints: { requires_human_supervision: true, respect_messaging_approval: true },
    defaultOutputContract: { kind: "candidate_bundle" },
    templateKeys: ["recruiting_trial_screening"],
  },
  {
    key: "market_news",
    name: "Market News",
    description: "Collect fresh market news and assemble a concise digest.",
    version: "0.4.0",
    maturity: "experimental",
    runtimeOnly: true,
    defaultCapabilities: ["search", "http", "browser", "llm", "document"],
    sampleTasks: ["Find the latest stock market news and summarize it."],
    defaultConstraints: { requires_source_links: true },
    defaultOutputContract: { kind: "news_digest" },
    templateKeys: ["market_news_digest"],
  },
  {
    key: "web_research",
    name: "Web Research",
    description: "Search, compare, and shortlist tools or resources from the open web.",
    version: "0.4.0",
    maturity: "experimental",
    runtimeOnly: true,
    defaultCapabilities: ["search", "browser", "http", "llm", "document"],
    sampleTasks: ["Find useful PDF converters and compare them."],
    defaultConstraints: { requires_source_links: true },
    defaultOutputContract: { kind: "research_shortlist" },
    templateKeys: ["web_research_shortlist"],
  },
  {
    key: "github_trends",
    name: "GitHub Trends",
    description: "Track hot repositories and summarize why they matter.",
    version: "0.4.0",
    maturity: "experimental",
    runtimeOnly: true,
    defaultCapabilities: ["http", "browser", "llm", "document"],
    sampleTasks: ["List today's hot GitHub repositories with repo links."],
    defaultConstraints: { requires_source_links: true },
    defaultOutputContract: { kind: "repository_digest" },
    templateKeys: ["github_trends_digest"],
  },
];

const runtimeCompilerContract: RuntimeCompilerContract = {
  strategy: "llm_first_structured_semantic_compiler",
  fallbackStrategy: "heuristic_domain_and_capability_inference",
  promptAsset: "tasks/runtime_task_compiler.md",
  requiredFields: ["goal", "domain", "constraints", "success_criteria", "approval_policy", "output_contract"],
  optionalFields: ["inputs", "preferred_capabilities", "preferred_domains", "environment_requirements", "checkpoints", "step_outline", "compiler_notes"],
  invariants: [
    "No fixed-site integration is assumed during development.",
    "The compiler must emit a structured task contract before execution.",
    "Fallbacks must be recorded explicitly.",
  ],
  availableDomains: domainPacks,
  availableCapabilities: runtimeCapabilityDrivers,
};

export const desktopRuntimeMock: RuntimeWorkspaceData = {
  compilerContract: runtimeCompilerContract,
  domainPacks,
  taskSpecs: runtimeTasks,
  plans: runtimePlans,
  episodes: runtimeEpisodes,
  snapshots: runtimeSnapshots,
  capabilityDrivers: runtimeCapabilityDrivers,
  environmentAssessments: runtimeEnvironmentAssessments,
  templates: runtimeTemplates,
  patches: runtimePatches,
  replans: runtimeReplans,
};

export const desktopSyncBacklogMock: SyncBacklogItem[] = [
  {
    id: "sync-001",
    target: "intranet:candidate_bundle",
    entityType: "candidate_bundle",
    entityId: "cand-001",
    status: "pending",
    attemptCount: 2,
    payloadSummary: "Candidate bundle for Mia Chen is waiting for intranet availability.",
    lastError: "Intranet endpoint unavailable during the last replay attempt.",
    updatedAt: iso(-42),
  },
  {
    id: "sync-002",
    target: "intranet:runtime_template",
    entityType: "runtime_template",
    entityId: "template-001",
    status: "pending",
    attemptCount: 1,
    payloadSummary: "Validated PDF converter template is queued for sync.",
    updatedAt: iso(-18),
  },
];

export const desktopSyncStatusMock: SyncStatusSnapshot = {
  enabled: false,
  mode: "local_only",
  remoteAvailable: false,
  pendingCount: desktopSyncBacklogMock.length,
  lastAttemptAt: iso(-18),
  lastSuccessAt: iso(-320),
  recentErrors: ["Intranet sync is disabled, so backlog is retained locally."],
};

export const desktopReplayMockByEpisode: Record<string, RuntimeEpisodeReplay> = {
  "episode-001": {
    episode: runtimeEpisodes[0],
    taskSpec: runtimeTasks[0],
    executionPlan: runtimePlans[0],
    snapshots: [runtimeSnapshots[0]],
    patch: null,
    template: runtimeTemplates[0],
    approval: {
      id: "approval-episode-001",
      targetType: "workflow_template",
      targetId: "template-001",
      title: "Activate PDF converter research template",
      status: "pending",
      requestedBy: "runtime",
    },
    diagnostics: [
      {
        id: "diag-001",
        label: "Compiler seeded a supervised trial plan",
        detail: "The runtime selected the Web Research pack and required human review before promotion.",
        at: iso(-72),
        tone: "positive",
      },
      {
        id: "diag-002",
        label: "Browser exploration completed",
        detail: "The episode captured a tool listing page and extracted shortlist candidates without drift.",
        at: iso(-66),
        tone: "positive",
      },
      {
        id: "diag-003",
        label: "Replay ready for confirmation",
        detail: "A reusable template draft was derived and is waiting for desktop confirmation.",
        at: iso(-64),
        tone: "warning",
      },
    ],
    notes: [
      "The replay remained within the expected environment model.",
      "A local-only sync backlog entry was created for the derived template.",
    ],
  },
  "episode-002": {
    episode: runtimeEpisodes[1],
    taskSpec: runtimeTasks[1],
    executionPlan: runtimePlans[1],
    snapshots: [runtimeSnapshots[1]],
    patch: runtimePatches[0],
    template: runtimeTemplates[1],
    approval: {
      id: "approval-episode-002",
      targetType: "workflow_patch",
      targetId: "patch-001",
      title: "Review GitHub trending drift patch",
      status: "pending",
      requestedBy: "runtime",
    },
    diagnostics: [
      {
        id: "diag-004",
        label: "HTTP step succeeded",
        detail: "Trending repository metadata was collected without issue.",
        at: iso(-23),
        tone: "positive",
      },
      {
        id: "diag-005",
        label: "Repository listing drift detected",
        detail: "The runtime observed a changed page structure and proposed a checkpoint review patch.",
        at: iso(-19),
        tone: "critical",
      },
      {
        id: "diag-006",
        label: "Patch held for desktop review",
        detail: "The proposed patch is queued until an operator confirms the revised plan.",
        at: iso(-18),
        tone: "warning",
      },
    ],
    notes: [
      "Environment heuristics should be refreshed before reusing this template.",
      "The replay indicates the current production template is still usable with supervision.",
    ],
  },
};
