export const theme = {
  colors: {
    background: "var(--bg-page)",
    page: "var(--bg-page)",
    panel: "var(--bg-card)",
    panelElevated: "var(--bg-card)",
    border: "var(--border-line)",
    borderInput: "var(--border-input)",
    borderFocus: "var(--border-focus)",
    text: "var(--text-primary)",
    regular: "var(--text-regular)",
    muted: "var(--text-secondary)",
    placeholder: "var(--text-placeholder)",
    inverse: "var(--text-inverse)",
    positive: "var(--success)",
    warning: "var(--warning)",
    critical: "var(--danger)",
    info: "var(--info)",
    accent: "var(--brand-primary)",
    accentSoft: "var(--brand-primary-soft)",
    hover: "var(--bg-hover)",
    subtle: "var(--bg-subtle)",
    sider: "var(--bg-sider)",
    siderHover: "var(--bg-sider-hover)",
    siderActive: "var(--bg-sider-active)",
  },
  radius: {
    xl: "var(--radius-lg)",
    lg: "var(--radius-md)",
    md: "var(--radius-sm)",
    sm: "var(--radius-xs)",
  },
  shadow: "var(--shadow-pop)",
};
