from __future__ import annotations

from copy import deepcopy
from typing import Any, Literal

StateColor = Literal["default", "warning", "success", "danger", "info"]
WaitingParty = Literal["AI", "CANDIDATE", "HUMAN", "AUTO"]
Trigger = Literal["auto", "agent", "human", "system"]

NONTERMINAL_EXCEPTION_CLOSE_SOURCES = (
    "discovered",
    "online_resume_fetching",
    "online_resume_acquired",
    "online_resume_passed",
    "offline_resume_fetching",
    "offline_resume_acquired",
    "offline_resume_passed",
    "human_screening",
    "human_screening_passed",
    "profile_ready",
    "interview_pending",
    "interview_scheduled",
    "interview_passed",
    "offer_sent",
)


def _node(
    *,
    node_id: str,
    label: str,
    phase: str,
    phase_label: str,
    waiting_party: WaitingParty,
    sort_order: int,
    terminal: bool = False,
    success: bool = False,
    soft_terminal: bool = False,
    transient: bool = False,
    milestone_id: str | None = None,
    description: str = "",
    color: StateColor = "default",
    show_in_kanban: bool = True,
    show_in_funnel: bool = True,
    execution_config: dict[str, Any] | None = None,
    retry_policy: dict[str, Any] | None = None,
) -> dict[str, Any]:
    node: dict[str, Any] = {
        "id": node_id,
        "label": label,
        "phase": phase,
        "phaseLabel": phase_label,
        "defaultWaitingParty": waiting_party,
        "isTerminal": terminal,
        "isSuccess": success,
        "isSoftTerminal": soft_terminal,
        "isTransient": transient,
        "sortOrder": sort_order,
        "description": description,
        "uiConfig": {
            "color": color,
            "showInKanban": show_in_kanban,
            "showInFunnel": show_in_funnel,
        },
    }
    if milestone_id:
        node["milestoneId"] = milestone_id
    if execution_config:
        node["executionConfig"] = execution_config
    if retry_policy:
        node["retryPolicy"] = retry_policy
    return node


def _transition(
    from_state: str,
    to_state: str,
    *,
    trigger: Trigger,
    label: str,
    condition: str | None = None,
    requires_note: bool = False,
    allowed_actors: list[str] | None = None,
) -> dict[str, Any]:
    transition: dict[str, Any] = {
        "id": f"{from_state}_to_{to_state}",
        "fromState": from_state,
        "toState": to_state,
        "trigger": trigger,
        "label": label,
        "allowedActors": list(allowed_actors or ["agent", "recruiter"]),
    }
    if condition:
        transition["condition"] = condition
    if requires_note:
        transition["requiresNote"] = True
    return transition


def _exception_close_transition(from_state: str) -> dict[str, Any]:
    return _transition(
        from_state,
        "exception_closed",
        trigger="human",
        label="异常关闭",
        requires_note=True,
        allowed_actors=["recruiter"],
    )


def _nodes() -> list[dict[str, Any]]:
    return [
        _node(
            node_id="discovered",
            label="已发现",
            phase="A",
            phase_label="发现",
            waiting_party="AI",
            milestone_id="M01",
            sort_order=10,
            description="Agent 已发现候选人，等待进入在线简历获取与评估。",
        ),
        _node(
            node_id="online_resume_fetching",
            label="在线简历获取中",
            phase="B",
            phase_label="在线简历",
            waiting_party="AI",
            milestone_id="M02",
            sort_order=20,
            description="Agent 正在读取候选人的在线简历、主页或平台资料。",
            color="info",
            execution_config={
                "mode": "ai_auto",
                "criteriaRef": {"type": "skill", "skillId": "online_resume_intake_v1"},
            },
        ),
        _node(
            node_id="online_resume_acquired",
            label="在线简历获取成功",
            phase="B",
            phase_label="在线简历",
            waiting_party="AI",
            milestone_id="M03",
            sort_order=30,
            description="在线简历已入库，等待在线简历评估。",
            color="success",
            execution_config={
                "mode": "ai_auto",
                "criteriaRef": {
                    "type": "skill",
                    "skillId": "online_resume_evaluation_v1",
                    "passThreshold": 70,
                },
                "humanActions": [
                    {"label": "在线评估通过", "toStatus": "online_resume_passed", "style": "primary"},
                    {
                        "label": "在线评估淘汰",
                        "toStatus": "online_resume_rejected",
                        "style": "danger",
                        "requiresNote": True,
                    },
                ],
            },
        ),
        _node(
            node_id="online_resume_passed",
            label="在线简历评估通过",
            phase="B",
            phase_label="在线简历",
            waiting_party="AUTO",
            milestone_id="M04",
            sort_order=40,
            success=True,
            transient=True,
            description="在线简历评估通过，流程继续获取离线简历。",
            color="success",
        ),
        _node(
            node_id="online_resume_rejected",
            label="在线简历评估淘汰",
            phase="B",
            phase_label="在线简历",
            waiting_party="AUTO",
            milestone_id="M05",
            sort_order=50,
            terminal=True,
            description="在线简历评估未通过，流程终止。",
            color="danger",
            show_in_funnel=False,
        ),
        _node(
            node_id="offline_resume_fetching",
            label="离线简历获取中",
            phase="D",
            phase_label="离线简历",
            waiting_party="CANDIDATE",
            milestone_id="M06",
            sort_order=60,
            transient=True,
            description="Agent 正在通过沟通索要 PDF、Word 或其他离线简历附件。",
            color="warning",
            retry_policy={"maxRetries": 2, "retryAfterHours": 48, "closeAfterHours": 120},
        ),
        _node(
            node_id="offline_resume_acquired",
            label="离线简历获取成功",
            phase="D",
            phase_label="离线简历",
            waiting_party="AI",
            milestone_id="M07",
            sort_order=70,
            transient=True,
            description="离线简历附件已获取并入库，等待离线简历评估。",
            color="success",
            execution_config={
                "mode": "ai_auto",
                "criteriaRef": {
                    "type": "skill",
                    "skillId": "offline_resume_evaluation_v1",
                    "passThreshold": 70,
                },
                "humanActions": [
                    {"label": "离线评估通过", "toStatus": "offline_resume_passed", "style": "primary"},
                    {
                        "label": "离线评估淘汰",
                        "toStatus": "offline_resume_rejected",
                        "style": "danger",
                        "requiresNote": True,
                    },
                ],
            },
        ),
        _node(
            node_id="offline_resume_passed",
            label="离线简历评估通过",
            phase="D",
            phase_label="离线简历",
            waiting_party="AUTO",
            milestone_id="M08",
            sort_order=80,
            success=True,
            transient=True,
            description="离线简历评估通过，进入人工筛选。",
            color="success",
        ),
        _node(
            node_id="offline_resume_rejected",
            label="离线简历评估淘汰",
            phase="D",
            phase_label="离线简历",
            waiting_party="AUTO",
            milestone_id="M09",
            sort_order=90,
            terminal=True,
            description="离线简历评估未通过，流程终止。",
            color="danger",
            show_in_funnel=False,
        ),
        _node(
            node_id="human_screening",
            label="人工筛选中",
            phase="E",
            phase_label="人工筛选",
            waiting_party="HUMAN",
            milestone_id="M10",
            sort_order=100,
            transient=True,
            description="系统必须先基于在线简历、离线简历和沟通记录产出 AI 综合评分，再由人工决定是否通过。",
            color="warning",
            execution_config={
                "mode": "human_required",
                "criteriaRef": {"type": "skill", "skillId": "composite_candidate_scoring_v1"},
                "humanActions": [
                    {"label": "筛选通过", "toStatus": "human_screening_passed", "style": "primary"},
                    {
                        "label": "筛选未通过",
                        "toStatus": "human_screening_rejected",
                        "style": "danger",
                        "requiresNote": True,
                    },
                ],
            },
        ),
        _node(
            node_id="human_screening_passed",
            label="人工筛选通过",
            phase="E",
            phase_label="人工筛选",
            waiting_party="AUTO",
            milestone_id="M11",
            sort_order=110,
            success=True,
            transient=True,
            description="人工筛选通过，进入候选人资料准备。",
            color="success",
        ),
        _node(
            node_id="human_screening_rejected",
            label="人工筛选未通过",
            phase="E",
            phase_label="人工筛选",
            waiting_party="HUMAN",
            milestone_id="M12",
            sort_order=120,
            terminal=True,
            description="人工筛选未通过，流程终止。",
            color="danger",
            show_in_funnel=False,
        ),
        _node(
            node_id="profile_ready",
            label="候选人资料准备完毕",
            phase="F",
            phase_label="资料准备",
            waiting_party="AUTO",
            milestone_id="M13",
            sort_order=130,
            success=True,
            transient=True,
            description="在线简历、在线简历评估、离线简历、离线简历评估与 AI 综合评分均已准备完成。",
            color="success",
        ),
        _node(
            node_id="interview_pending",
            label="待预约面试",
            phase="G",
            phase_label="面试",
            waiting_party="HUMAN",
            milestone_id="M14",
            sort_order=140,
            transient=True,
            description="候选人资料已准备完毕，等待安排面试。",
            color="warning",
            execution_config={
                "mode": "human_required",
                "humanActions": [
                    {"label": "面试已预约", "toStatus": "interview_scheduled", "style": "primary"},
                    {
                        "label": "异常关闭",
                        "toStatus": "exception_closed",
                        "style": "danger",
                        "requiresNote": True,
                    },
                ],
            },
        ),
        _node(
            node_id="interview_scheduled",
            label="面试已预约",
            phase="G",
            phase_label="面试",
            waiting_party="HUMAN",
            milestone_id="M15",
            sort_order=150,
            transient=True,
            description="面试已预约，等待面试结果。",
            color="info",
            execution_config={
                "mode": "human_required",
                "humanActions": [
                    {"label": "面试通过", "toStatus": "interview_passed", "style": "primary"},
                    {
                        "label": "面试未通过",
                        "toStatus": "interview_rejected",
                        "style": "danger",
                        "requiresNote": True,
                    },
                ],
            },
        ),
        _node(
            node_id="interview_passed",
            label="面试通过",
            phase="G",
            phase_label="面试",
            waiting_party="AUTO",
            milestone_id="M16",
            sort_order=160,
            success=True,
            transient=True,
            description="面试通过，进入 Offer 阶段。",
            color="success",
        ),
        _node(
            node_id="interview_rejected",
            label="面试未通过",
            phase="G",
            phase_label="面试",
            waiting_party="HUMAN",
            milestone_id="M17",
            sort_order=170,
            terminal=True,
            description="面试未通过，流程终止。",
            color="danger",
            show_in_funnel=False,
        ),
        _node(
            node_id="offer_sent",
            label="Offer已发出",
            phase="H",
            phase_label="Offer",
            waiting_party="CANDIDATE",
            milestone_id="M18",
            sort_order=180,
            transient=True,
            description="Offer 已发送，等待候选人确认。",
            color="warning",
            retry_policy={"maxRetries": 2, "retryAfterHours": 72, "closeAfterHours": 168},
            execution_config={
                "mode": "human_required",
                "humanActions": [
                    {"label": "Offer已接受", "toStatus": "offer_accepted", "style": "primary"},
                    {
                        "label": "Offer被拒",
                        "toStatus": "offer_rejected",
                        "style": "danger",
                        "requiresNote": True,
                    },
                ],
            },
        ),
        _node(
            node_id="offer_accepted",
            label="Offer已接受",
            phase="H",
            phase_label="Offer",
            waiting_party="AUTO",
            milestone_id="M19",
            sort_order=190,
            terminal=True,
            success=True,
            description="候选人接受 Offer，流程成功结束。",
            color="success",
        ),
        _node(
            node_id="offer_rejected",
            label="Offer被拒",
            phase="H",
            phase_label="Offer",
            waiting_party="CANDIDATE",
            milestone_id="M20",
            sort_order=200,
            terminal=True,
            description="候选人拒绝 Offer，流程终止。",
            color="danger",
            show_in_funnel=False,
        ),
        _node(
            node_id="exception_closed",
            label="异常关闭",
            phase="I",
            phase_label="异常关闭",
            waiting_party="HUMAN",
            milestone_id="M21",
            sort_order=210,
            terminal=True,
            description="仅用于处理异常、撤回、重复数据或无法继续推进的兜底关闭状态。",
            color="danger",
            show_in_funnel=False,
        ),
    ]


def _transitions() -> list[dict[str, Any]]:
    main_transitions = [
        _transition("discovered", "online_resume_fetching", trigger="agent", label="开始获取在线简历"),
        _transition("online_resume_fetching", "online_resume_acquired", trigger="agent", label="在线简历获取成功"),
        _transition(
            "online_resume_acquired",
            "online_resume_passed",
            trigger="agent",
            label="在线简历评估通过",
            condition="online_resume_score >= pass_threshold",
        ),
        _transition(
            "online_resume_acquired",
            "online_resume_rejected",
            trigger="agent",
            label="在线简历评估淘汰",
            condition="online_resume_score < pass_threshold",
            requires_note=True,
        ),
        _transition("online_resume_passed", "offline_resume_fetching", trigger="agent", label="开始获取离线简历"),
        _transition("offline_resume_fetching", "offline_resume_acquired", trigger="agent", label="离线简历获取成功"),
        _transition(
            "offline_resume_acquired",
            "offline_resume_passed",
            trigger="agent",
            label="离线简历评估通过",
            condition="offline_resume_score >= pass_threshold",
        ),
        _transition(
            "offline_resume_acquired",
            "offline_resume_rejected",
            trigger="agent",
            label="离线简历评估淘汰",
            condition="offline_resume_score < pass_threshold",
            requires_note=True,
        ),
        _transition(
            "offline_resume_passed",
            "human_screening",
            trigger="agent",
            label="进入人工筛选",
            condition="composite_score_ready",
        ),
        _transition(
            "human_screening",
            "human_screening_passed",
            trigger="human",
            label="人工筛选通过",
            condition="composite_score_ready",
            allowed_actors=["recruiter"],
        ),
        _transition(
            "human_screening",
            "human_screening_rejected",
            trigger="human",
            label="人工筛选未通过",
            condition="composite_score_ready",
            requires_note=True,
            allowed_actors=["recruiter"],
        ),
        _transition(
            "human_screening_passed",
            "profile_ready",
            trigger="auto",
            label="资料准备完毕",
            condition="online_resume + online_evaluation + offline_resume + offline_evaluation + composite_score are ready",
            allowed_actors=["agent", "system"],
        ),
        _transition("profile_ready", "interview_pending", trigger="agent", label="进入面试预约"),
        _transition(
            "interview_pending",
            "interview_scheduled",
            trigger="human",
            label="面试已预约",
            allowed_actors=["recruiter"],
        ),
        _transition(
            "interview_scheduled",
            "interview_passed",
            trigger="human",
            label="面试通过",
            allowed_actors=["recruiter"],
        ),
        _transition(
            "interview_scheduled",
            "interview_rejected",
            trigger="human",
            label="面试未通过",
            requires_note=True,
            allowed_actors=["recruiter"],
        ),
        _transition(
            "interview_passed",
            "offer_sent",
            trigger="human",
            label="Offer已发出",
            allowed_actors=["recruiter"],
        ),
        _transition(
            "offer_sent",
            "offer_accepted",
            trigger="human",
            label="Offer已接受",
            allowed_actors=["recruiter"],
        ),
        _transition(
            "offer_sent",
            "offer_rejected",
            trigger="human",
            label="Offer被拒",
            requires_note=True,
            allowed_actors=["recruiter"],
        ),
    ]
    return [*main_transitions, *[_exception_close_transition(state) for state in NONTERMINAL_EXCEPTION_CLOSE_SOURCES]]


def default_recruitment_state_machine_payload() -> dict[str, Any]:
    return {
        "version": 2,
        "updatedAt": "2026-05-13T00:00:00.000Z",
        "updatedBy": "product:2026-05-13-recruiting-state-machine-v2",
        "changeSummary": (
            "Replace the recruiting lifecycle with the online resume, offline resume, "
            "human screening, interview, offer, and exception-close chain."
        ),
        "nodes": deepcopy(_nodes()),
        "transitions": deepcopy(_transitions()),
        "globalTransitions": [],
        "versionMetadata": {
            "source": "recruit_agent.product_adapters.recruitment_state_machine",
            "designIntent": "transient means process state, not hidden state",
            "exceptionClosePolicy": "exception_closed is available only from explicit nonterminal states",
        },
    }
